### ISSUE TITLE
新版本的sdk 3.1 新申请bundle id 无法sso 使用

### ISSUE THREAD

**Issue by baxiang** [sinaweibosdk/weibo_ios_sdk#100]
最新版的sdk  在请求sso 时是可以回调到客户端应用 但是不会调用- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation

换成旧的的bundle id 和 key 可以，但是我们刚申请的 bundle id  是不行的。可以挑战到我们已用 但是没有调用 application openURL:是不是新浪微博对最新的bundle  id 需要审核才能生效。？

**Comment by dannion** [comment]
查看下url scheme是否配置正确？

**Comment by baxiang** [comment]
原因找到了 是因为我手机里面在不停的更换bundle id , 造成测试手机里面有好几个相同应用（只是bundle id 不同）。所以微博无法回调，把废弃的bundle id 应用删除 问题已经解决 非常感谢。
