### ISSUE TITLE
太慢

### ISSUE THREAD

**Issue by ZYCoderIOS** [sinaweibosdk/weibo_ios_sdk#105]
github上面下载太慢了,为什么不放在官网上呢,效率太低了,不像大公司所为啊

**Comment by guoshencheng** [comment]
可以使用pod来管理第三方，我倒觉得像其他那种放官网上下的才不像大公司所为，放一个包在自己服务器上给别人下就是大公司所为了么

**Comment by ZYCoderIOS** [comment]
的确,放在这个上面是可以使用pod,可是API文档,能pod吗?21M的东西,下下来要个把小时,你受的了,而且还断了好几次,为什么不官方git上都放呢?
