### ISSUE TITLE
为什么提示未识别的标识符：WeiboSDK？

### ISSUE THREAD

**Issue by clarifysky** [sinaweibosdk/weibo_ios_sdk#107]
我使用pod安装的，按照示例，在App.delegate启动后的代码(application ... didFinishLaunchingWithOptions)里面注册AppKey，但是提示WeiboSDK无法识别，我在头部import WeiboSDK，也提示无法识别的模块。
Xcode6.4+Swift
<img width="647" alt="screen shot 2015-08-06 at 18 17 40" src="https://cloud.githubusercontent.com/assets/5001145/9109417/1722e49c-3c68-11e5-8af5-945133586b39.png">
<img width="688" alt="screen shot 2015-08-06 at 18 18 23" src="https://cloud.githubusercontent.com/assets/5001145/9109416/15a80afc-3c68-11e5-9462-fe3461a9cc72.png">

**Comment by yunlzheng** [comment]
同样的问题，使用pod 安装后 pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'

找不到模块

**Comment by yunlzheng** [comment]
暂时直接导入的源代码用header加载

**Comment by jonauz** [comment]
Same happens to me, had to use Bridging Headers and add WeiboSDK.h file. This works, but there is other problem, throws a lot of warnings.
To fix those warnings, WeibSDK should be updated to modern ways of development.
Here is related possible fix, or more like a workaround:
http://stackoverflow.com/questions/8994911/cannot-find-interface-declaration-for-nsobject
But this is not a solution.
Problem is with the setup of Cocoa Pods and SDK. Please, can you renew this SDK and everything inside, so it would be compatible with current Xcode, Swift and iOS. It needs complete renovation, it is outdated.

**Comment by clwm01** [comment]
I ran 'pod install' to update pods, then pod show me 'using WeiboSDK(3.1.1)', but it still not work for me.
