### ISSUE TITLE
scope里面写了all或 follow_app_official_microblog但是授权页面并没有显示关注官方账号

### ISSUE THREAD

**Issue by pinguo-tanglei** [sinaweibosdk/weibo_ios_sdk#114]
代码:
WBAuthorizeRequest *request = [WBAuthorizeRequest request];
request.redirectURI = kSinaSsoRedirectURL;
request.scope = @"all";

但是在授权页面并没显示 "关注xxx的微博"

**Comment by junjielu** [comment]
是因为你已经关注了xxx，你取关试试看
