### ISSUE TITLE
-[NSConcreteMutableData wbsdk_base64EncodedString]: unrecognized selector sent to instance 0x168babb0

### ISSUE THREAD

**Issue by dollarfromchina** [sinaweibosdk/weibo_ios_sdk#115]
调用    [WeiboSDK registerApp:SocialShareWeiBoID];后崩溃

**Comment by devjia** [comment]
我也遇到同样问题.

**Comment by shiguol** [comment]
已解决，请加链接参数：[-all_load](https://github.com/sinaweibosdk/weibo_ios_sdk/issues/117)

**Comment by GWesley** [comment]
Target->Buid Settings->Linking 下 Other Linker Flags 项添加-ObjC。

注意看文档呀

**Comment by tuyuanyou** [comment]
我在Target->Buid Settings->Linking 下 Other Linker Flags 项添加-all_load后， 与我自己的工程冲突了，怎么办

**Comment by Verchen** [comment]
我也是加上-ObjC后直接编译就报错了，怎么解决

**Comment by ChengHuiHe** [comment]
@Verchen 你选择的版本过低，调高点，例如：8.2

**Comment by ChengHuiHe** [comment]
@Verchen 在other linker flags增加-ObjC 选项，并添加ImageIO 系统framework（实现新浪微博必须完成的步骤），然后手动添加对应的库就可以了。
