### ISSUE TITLE
registerApp崩溃

### ISSUE THREAD

**Issue by devjia** [sinaweibosdk/weibo_ios_sdk#117]
Xcode6.4+iOS8.4 
应用启动的时候调用registerApp必现崩溃
-[NSConcreteMutableData wbsdk_base64EncodedString]: unrecognized selector sent to instance 0x7fb71ad478f0

**Comment by devjia** [comment]
已解决,other link flag   添加-all_load

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。
