### ISSUE TITLE
WeiboSDK_iOS版 Xcode7 真机 bitcode

### ISSUE THREAD

**Issue by zeekx** [sinaweibosdk/weibo_ios_sdk#119]
weibo_ios_sdk/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7

**Comment by zhudengdengdeng** [comment]
+1
