### ISSUE TITLE
不支持Bitcode导致项目无法使用新特性，微博SDK需要用新版XCode 7重新打包。

### ISSUE THREAD

**Issue by BingLiuBing** [sinaweibosdk/weibo_ios_sdk#124]
编译时报错：
ld: '/Users/abc/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by BenjaminX** [comment]
ld: 'Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zhudengdengdeng** [comment]
+1
