### ISSUE TITLE
swift编写，sso登录代码提示request immutable

### ISSUE THREAD

**Issue by alwaystrong** [sinaweibosdk/weibo_ios_sdk#127]
var request = WBAuthorizeRequest.request()
request.redirectURI = "http://www.sina.com"
报错：
 Cannot assign to property: 'request' is immutable

这个是要怎么修改呢？
![8 pic](https://cloud.githubusercontent.com/assets/12870849/9897685/f53fff5a-5c7d-11e5-9442-f17a738bfa14.jpg)

**Comment by xchenLee** [comment]
直接返回的是AnyObject , var的时候 指定一下类型 ：WBAuthorizeRequest，可以用guard
