### ISSUE TITLE
微博授权，没有安装微博客户端，进行SDK自带的Webview进行授权界面，response.requestUserInfo 为nil

### ISSUE THREAD

**Issue by webcrawler** [sinaweibosdk/weibo_ios_sdk#128]
微博授权，没有安装微博客户端，进行SDK自带的Webview进行授权界面，不输账号点击关闭返回。在didReceiveWeiboResponse接收到的response.requestUserInfo 为nil。如果输入账号密码授权成功返回则正常。是sdk本身就这样吗

**Comment by bill666500** [comment]
我想问下遇到过没有安装客户端，在分享的时候跳转了两次登录界面
