### ISSUE TITLE
微博WebView授权页面的UI问题

### ISSUE THREAD

**Issue by captain-black** [sinaweibosdk/weibo_ios_sdk#131]
![ios simulator screen shot 2015 9 22 4 17 33](https://cloud.githubusercontent.com/assets/1026515/10013718/720a933e-6146-11e5-888f-5244cfe789d0.png)
![ios simulator screen shot 2015 9 22 4 21 22](https://cloud.githubusercontent.com/assets/1026515/10013719/75c5654e-6146-11e5-8750-1de23edee1cf.png)

**Comment by captain-black** [comment]
SDK版本是3.1.1

**Comment by bill666500** [comment]
我想问下遇到过没有安装客户端，在分享的时候跳转了两次登录界面

**Comment by upworldcjw** [comment]
我也遇到蓝条问题，如何解决。不想重写一个授权界面。为什么不想qq分享，调浏览器啊？

**Comment by upworldcjw** [comment]
fix 蓝条问题。 

@implementation UIViewController (Tracking)
+ (void)load {
   static dispatch_once_t onceToken;
   dispatch_once(&onceToken, ^{
           Class class = [self class];
           // When swizzling a class method, use the following:
           // Class class = object_getClass((id)self);
           SEL originalSelector = @selector(viewWillAppear:);
           SEL swizzledSelector = @selector(xxx_viewWillAppear:);
           Method originalMethod = class_getInstanceMethod(class, originalSelector);
           Method swizzledMethod = class_getInstanceMethod(class, swizzledSelector);
           BOOL didAddMethod =
               class_addMethod(class,
                              originalSelector,
                              method_getImplementation(swizzledMethod),
                              method_getTypeEncoding(swizzledMethod));
  
           if (didAddMethod) {
                  class_replaceMethod(class,
                                       swizzledSelector,
                                       method_getImplementation(originalMethod),
                                       method_getTypeEncoding(originalMethod));
              } else {
                      method_exchangeImplementations(originalMethod, swizzledMethod);
            }
       });
}

#pragma mark - Method Swizzling
- (void)xxx_viewWillAppear:(BOOL)animated {
    [self xxx_viewWillAppear:animated];
    NSLog(@"viewWillAppear: %@", self);
     if ([self isKindOfClass:NSClassFromString(@"WBSDKComposerWebViewController")]) {
         for (UIView *view in self.view.subviews) {
             if ([view isKindOfClass:NSClassFromString(@"WBSDKWebView")]) {
                 for (UIView *subView in view.subviews) {
                     if ([subView isKindOfClass:NSClassFromString(@"WBSDKWebViewProgressView")]) {
                         NSLog(@"WBSDKWebViewProgressView hidden");
                         subView.hidden = YES;
                         subView.alpha = 0;
                     }
                 }
             }
         }
     }
}

**Comment by githubTyd** [comment]
楼上的写的这个方法 ，在哪里调用啊

**Comment by TooWalker** [comment]
here is a solution(http://www.jianshu.com/p/de9ff5a435d1)
