### ISSUE TITLE
IOS9启动就崩溃，已更新至3.1.1，注销“WeiboSDK registerApp”就不崩溃

### ISSUE THREAD

**Issue by F2EVarMan** [sinaweibosdk/weibo_ios_sdk#133]
![39ba888f-a163-4532-8cf3-f18a948b389e](https://cloud.githubusercontent.com/assets/10355060/10014774/392e2578-614e-11e5-8a34-cc2a8b9f7eb6.png)

**Comment by gitcalmlyhub** [comment]
我也遇到这个问题了，急急急啊，如果你解决了麻烦告诉我一声。多谢。

**Comment by Whirlwind** [comment]
same problem.

**Comment by panxianyue** [comment]
有人解决这个问题嘛?

**Comment by rpplusplus** [comment]
我解决了，见代码

在注册 微博 sdk 之前
```objc
[NSDictionary aspect_hookSelector:NSSelectorFromString(@"weibosdk_WBSDKJSONString")
                          withOptions:AspectPositionInstead
                           usingBlock:^(id<AspectInfo> info)
     {
         return [(NSDictionary*)[info instance] tt_jsonString];
     }
                                error:nil];
```

**Comment by Whirlwind** [comment]
@rpplusplus 是 JSON 转换出错？话说我昨天还正常的，今天突然就崩了，一直用 XCode7 编译啊。

**Comment by rpplusplus** [comment]
@Whirlwind 因为如果 register 过 他就不会生成对应文件了，你应该是这两天删除过 ipa....

**Comment by Whirlwind** [comment]
我感觉是服务器下发了什么配置，我也是今天才出现的

**Comment by xdh725** [comment]
same problem.  应该是WBSDKJSONKIT 序列化时 报错了   似乎jsonkit在iOS9上也有同样的问题.. 猜测weibosdk使用了旧版本的jsonkit..需要更新

**Comment by rpplusplus** [comment]
@Whirlwind 最终原因还是 JSONKIT 的兼容性问题导致的....

不光 微博 我这里还有其他的 第三方 SDK 也出了这个问题

**Comment by lhyhsx** [comment]
@rpplusplus 能发下这个`tt_jsonString`方法么？

**Comment by Whirlwind** [comment]
@lhyhsx  用系统的 JSON 解析就行

**Comment by fingerplay** [comment]
这个问题weiboSDK现在解决没有？

**Comment by dongdong204hn** [comment]
我这边用jsonkit没发现问题啊

**Comment by gitcalmlyhub** [comment]
最新的SDK是OK的了。

**Comment by wenmingtang** [comment]
最新的还是不行啊，一样奔溃。

**Comment by hcxiong** [comment]
请问这个问题新的ＳＤＫ解决了吗？

**Comment by linshaolie** [comment]
怎么我使用了最新的，没有发现crash的现象？上一次用了旧版本，提交到了App Store，然后iOS9出来了，苹果审核的时候说一打开就崩，后来通过crash日志发现是微博SDK的问题，然后在这下载了最新的SDK，并根据提示做了设置就没事了。目前使用的只有微博的分享功能。

**Comment by littlepriest** [comment]
这个demo直接跑没事,引库到工程里,一编译就崩...什么情况...友盟那个也是..我哪里没设置吗

**Comment by michaelMaoMao** [comment]
@rpplusplus 灰常感谢大神，问题已解决.

**Comment by crossPQW** [comment]
最新的003013000版本的SDK还是出现同样的crash问题

**Comment by w1317** [comment]
[WeiboSDK registerApp:appkey]; 程序直接exc_bad_excess  如何解决

**Comment by huang1988519** [comment]
应该用的都是    
 ```
 pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
```
这个版本。
这个版本是因为缺少bundle内容引起的崩溃，在不更改pod地址的情况下，把WeboSDK.bundle 复制到 main bundle下就可以了。

**Comment by CG-Kerr** [comment]
启动项目后会自动打印Reachability Flag Status: -R ------- networkStatusForFlags,过几秒后崩溃,,如何解决哇

**Comment by CG-Kerr** [comment]
@bigjar 请问你解决了嘛?盼回,qq496547676

**Comment by zphui5409** [comment]
@CG-Kerr 你好,我也遇到了这个问题,希望你指点一下,可以的话麻烦加qq361598979,盼回复

**Comment by channingwei** [comment]
@zphui5409 遇到了同样的问题，请问你是如何解决这个问题的

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。
