### ISSUE TITLE
pod 安装WeiboSDK失败

### ISSUE THREAD

**Issue by devjia** [sinaweibosdk/weibo_ios_sdk#135]
详情:
Pre-downloading: `WeiboSDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk`
Downloading dependencies
Installing WeiboSDK (3.1.1)
Generating Pods project
2015-09-25 09:39:11.904 ruby[571:23989] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fb57c11a190>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000105c49a5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:](in DVTFoundation)
  1  0x0000000105c491e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000105c49455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000105c493b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x0000000107042f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x0000000109c9aeb9 +[PBXProject projectWithFile:errorHandler:readOnly:](in DevToolsCore)
  6  0x0000000109c9ca3e +[PBXProject projectWithFile:errorHandler:](in DevToolsCore)
  7  0x00007fff8728af44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by devjia** [comment]
已解决,是cocoapod的问题.

**Comment by chenzhijie** [comment]
有同样问题 是怎么解决的@devjia
