### ISSUE TITLE
如何设置回调的 delegate 不是指向 AppDelegate，而是发起这个 Request 的 Controller

### ISSUE THREAD

**Issue by gztchan** [sinaweibosdk/weibo_ios_sdk#136]
因为我的登录不是全局的，只会在需要的时候弹出，如何设置呢？

**Comment by linshaolie** [comment]
你在回调的时候发送一个notification，然后controller接收进行处理。我是这样做的

**Comment by linshaolie** [comment]
@allabttony 你在回调的时候发送一个notification，然后controller接收进行处理。我是这样做的

**Comment by wy1024** [comment]
顶楼上 swift可参考
[https://stackoverflow.com/questions/36910965/how-to-pass-data-using-notificationcentre-in-swift-3-0-and-nsnotificationcenter/36911168#36911168](url)
