### ISSUE TITLE
需要尽快支持 ios9/ios9.0.1

### ISSUE THREAD

**Issue by wenmingtang** [sinaweibosdk/weibo_ios_sdk#137]
调用 `[WeiboSDK registerApp:SINA_WEIBO_APPID];`  方法立即就会崩溃

**Comment by backslash112** [comment]
同样的问题
xcode version: 7.2
swift 2
device version: iOS 9.2

**Comment by johnlui** [comment]
https://github.com/sinaweibosdk/weibo_ios_sdk/issues/117
