### ISSUE TITLE
ios 9 编译后全是Warning

### ISSUE THREAD

**Issue by fuchanglin** [sinaweibosdk/weibo_ios_sdk#138]
![snip20150929_1](https://cloud.githubusercontent.com/assets/3982489/10143193/7e6eaf0e-6649-11e5-8a25-9d1d23872a65.png)

**Comment by wenmingtang** [comment]
貌似作者是业余维护这个项目，没有精力打理这些问题。

**Comment by fuchanglin** [comment]
这不是官方项目么？

**Comment by wenmingtang** [comment]
@fuchanglin 应该不是，如果是，fuck sina

**Comment by gitcalmlyhub** [comment]
我跟你一样的情况，一直没有解决。你解决了麻烦说一下。
另外，这个就是新浪官方的项目。我就是从新浪官方文档找过来的。

**Comment by ji-chang-an** [comment]
同样一堆警告，希望新浪能尽快解决。

**Comment by looping** [comment]
好像是 aedc6250f15bd9d12c36693a119304a5d34ecdf9 `添加对bitcode的支持`导致的。
如果现在不想支持`bitcode`，可以用
```
pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git', :commit => '5f22555f1d23ff834b2f3c3b93b0fe1916141649'
```

**Comment by GitHubNormalUser** [comment]
嗯，知道呢，但是像友盟、微信这类同样支持bitcode的包就没有那么多警告的问题哦。

**Comment by looping** [comment]
@GitHubNormalUser 把CocoaPods升级到`0.39.0`也可以解决问题。

**Comment by chisj** [comment]
应该是官方维护的啊，从open.weibo.cn的文档有链接过来

**Comment by kvting** [comment]
+1

**Comment by jinbo0122** [comment]
希望能尽快解决，看到这么多warning实在受不了，微信，qq，友盟加了bitcode支持之后都没有问题

**Comment by chisj** [comment]
我是这样解决的，给你提供一些思路：

1) 找到 Build Settings -> Build Options -> Debug Information Format

2) 把 Debug 模式从 "DWARF with dSYM File" 修改为 "DWARF"

3) Release 模式设置保留 "DWARF with dSYM File"

希望能帮到你。

**Comment by youngshook** [comment]
@chisj  Archive 的时候同样还会遇到，这个方式似乎不行

**Comment by coldmn3** [comment]
16年了，还没解决啊，200+warning

**Comment by Sum123** [comment]
200+的waring  确实有点太扎眼了

**Comment by zhudengdengdeng** [comment]
+1
