### ISSUE TITLE
微博登陆在iOS 9.0下跳转到了Webview的登陆页面。

### ISSUE THREAD

**Issue by jerry-sl** [sinaweibosdk/weibo_ios_sdk#143]
微博登陆在iOS 9.0下跳转到了Webview的登陆页面。我的机器上安装了微博客户端并且有账号登陆，登陆的状态也没有过期。 在iOS 8的机器上是没有问题。期待大家的回复和解决方案。

**Comment by jerry-sl** [comment]
补充上面的情况：iOS 9在调试模式下可以唤起客户端，TestFlight中安装的文件不能唤起app  跳到了Webview页面。

**Comment by bill666500** [comment]
我想问下遇到过没有安装客户端，在分享的时候跳转了两次登录界面
