### ISSUE TITLE
Xcode 7 & Swift 2 can't locate WeiboSDK library

### ISSUE THREAD

**Issue by jonauz** [sinaweibosdk/weibo_ios_sdk#146]
I'm using Xcode 7 (with Swift 2), and can't make this pods to work. It can't find WeiboSDK library.
I do `import WeiboSDK` but doesn't work.
My Podfile containts

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
pod 'WeiboSDK', '~> 3.1.1'
```

Cocoapods version 0.39.0
What do I miss? Or is this a bug on this SDK?

**Comment by monzy613** [comment]
you need a bridge from objective-c to swift 
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by harryblam** [comment]
This shouldn't be the case as of http://blog.cocoapods.org/CocoaPods-0.36/

By adding the use_frameworks! tag, we should be able to access the SDK directly by just typing `import WeiboSDK`at the top of your class.

Have you got any further update on this?
