### ISSUE TITLE
希望能够去除ADsupport.framework的依赖

### ISSUE THREAD

**Issue by gq630960023** [sinaweibosdk/weibo_ios_sdk#147]
因为应用中没有任何广告, 所以在添加了最新的 SDK 后会被苹果提示内嵌广告 并且要求 提供使用广告的作用.
同胞有被拒绝的情况, 无论如何去选择.于是加入SDK成了一件让人很纠结的事情.

SDK是大众开发者和新浪开发者之间衔接的最好纽带, 也是新浪和绝大部分希望用户能够在应用中进行新浪操作的APP能够选择的最好工具.

所以, 无论出于什么目的. 请SDK的开发者能够去除ADsupport.framework, 为双方的合作打通道路.

**Comment by neufeng** [comment]
＋1

**Comment by dapenggao** [comment]
+1

**Comment by billy55555** [comment]
+1 现在被这个问题困扰
