### ISSUE TITLE
强烈要求去掉adsupport.framework依赖

### ISSUE THREAD

**Issue by neufeng** [sinaweibosdk/weibo_ios_sdk#149]
新浪微博的大大们，你们强制要加了adsupport.framework这玩意，导致审核通不过啊，没法玩了，以后ios应用都不能集成sina sdk了

**Comment by bawn** [comment]
+1，希望去掉 adsupport.framework，或者请说明下用这个framework会不会导致被苹果拒绝的问题

**Comment by charleslinkn** [comment]
+1，希望去掉 adsupport.framework

**Comment by KyleXie** [comment]
什么？ 新的 SDK 里用了 adsupport？ 是不是我前两天提交的版本会悲剧啊？！

**Comment by ytqiu** [comment]
建议依赖adsupport要声明一下，同时想请教各位朋友有没有应对的策略？
