### ISSUE TITLE
3.1.3 Bitcode error when archiving

### ISSUE THREAD

**Issue by devxoul** [sinaweibosdk/weibo_ios_sdk#152]
**Environment**
- Xcode 7.1
- OS X 10.11.1
- Archiving iOS with minimum target requirement 7.0

**Podfile**

``` ruby
pod 'WeiboSDK', '3.1.3'
```

**Error Message**

> ld: bitcode bundle could not be generated because '/Users/xxx/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)' was built without **full** bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

It appeared when I tried to archive.

**Comment by bird-xiong** [comment]
i have same problem ,it can be archive in xcode7.0 with warning,but it will be failed in xcode 7.1

**Comment by bird-xiong** [comment]
hope sina fix it soon

**Comment by ybbaigo** [comment]
+1

**Comment by ming1016** [comment]
+1 same problem

**Comment by zhaoxy2850** [comment]
+1

**Comment by ZacksTsang** [comment]
+1

**Comment by mjx1003** [comment]
+1

**Comment by jl322137** [comment]
+1

**Comment by KyleXie** [comment]
+1

**Comment by ppt04025** [comment]
+1

**Comment by ZacksTsang** [comment]
+1

**Comment by cr185** [comment]
+1

**Comment by cr185** [comment]
+1

**Comment by zxwo0o** [comment]
+11

**Comment by takikoma** [comment]
+10086

竟然被这么多人报了这么久了还没修复 -。-
是自己重现不出？
other linker flags 加 -all_load就挂啦

**Comment by yaopuxin** [comment]
同样的错误 +1

**Comment by xiongoal** [comment]
+1

**Comment by inonomori** [comment]
之前微信也是，加 -all_load 就不行，还是有full bitcode support.    但后来微信出了新版解决了。
微博怎么一直没动作。

**Comment by cr185** [comment]
+1

**Comment by aBigShark** [comment]
希望得到微博的重视，能够尽快解决，苹果的iOS9推出已经很久了，现在就是因为微博SDK不支持，所以整个应用都无法应用AppThinning

**Comment by TristenChen** [comment]
+1

**Comment by JasonXue** [comment]
+1

**Comment by zhudengdengdeng** [comment]
+1

**Comment by devxoul** [comment]
Why they're not updating?
