### ISSUE TITLE
授权 WebView 应该禁用 cookie

### ISSUE THREAD

**Issue by an0** [sinaweibosdk/weibo_ios_sdk#153]
Bug：
多帐户应用，应用内自带网页浏览器（UIWebView），网页浏览器中登录了新浪微博。此时再用 SDK 登录授权（未安装官方客户端），授权 WebView 会再跳出后立马自动关闭，完全不给用户输入帐户信息的机会。

原因：
SDK  中授权 WebView 直接使用了应用网页浏览器所存储的新浪微博的 cookie，认为用户已经登录。

解决方案：
[WBSDKAuthorizeWebViewController urlRequestFromWeiboSDKRequest:andExtraPara:] 中生成 NSMutableURLRequest，将其 HTTPShouldHandleCookies 设为 NO。这样就可以让 WBSDKBasicWebViewController 的 WebView 禁用 cookie。

另外：
SDK 一定要用 binary 发布吗？直接开源代码的话，大伙可以直接提交 Pull Request。

**Comment by smoothdvd** [comment]
3.1.1版SDK里没看到有这个方法啊。

**Comment by an0** [comment]
@smoothdvd 我是写给 SDK 开发者的，让他们修正；不是写给使用者的。
