### ISSUE TITLE
为何一定要AdSupport.framework，就不能弄个没有AdSupport.framework的版本吗？

### ISSUE THREAD

**Issue by guoguoli** [sinaweibosdk/weibo_ios_sdk#156]
为何一定要AdSupport.framework，就不能弄个没有AdSupport.framework的版本吗？审核过不了啊！！！！

**Comment by tianglin** [comment]
11月13号提交了审核，没有勾选IDFA，卧槽了，咋办这？

**Comment by guoguoli** [comment]
你有植入广告吗？我们的没有植入广告，审核被拒了

**Comment by neufeng** [comment]
客服跟我说：“外部版sdk是不含adsupport的，只有新浪微博内部版sdk才有。请更新为官方对外SDK”。结果我用 grep -r advertisingIdentifier . 这命令再次检测，还是包含，看来他们的话不可信啊。再说我咋可能不是对外的SDK呢，你内部的SDK我怎么可能下到，逗我玩啊！！！
![5de98fe4-c788-493d-812c-ddb114b12137](https://cloud.githubusercontent.com/assets/3053458/11173573/37268e3e-8c53-11e5-8e9a-9571fab28589.png)

**Comment by KyleXie** [comment]
我查了下，好早之前的版本里就包含 advertisingIdentifier 了，但是之前一直都没有被拒，看最近这么多人因为这个被拒，难道是苹果开始严查了？前两天刚提交了一个新版本，忐忑ing

**Comment by bawn** [comment]
不知道微博是怎么考虑开发者的，也不做个说明

**Comment by KyleXie** [comment]
我用了 3.1.3 的版本， 审核通过了。。。

**Comment by linshaolie** [comment]
我提交的时候开始也是选了否，然后苹果提示了说我们使用了IDFA，然后我就选了是了，还在审核不知道能不能通过

发自我的 iPhone

**Comment by wantry** [comment]
昨晚审核被拒了，因为使用IDFA，而苹果没看见广告。

**Comment by neufeng** [comment]
今天开始到29号，苹果休息，审核关闭，兄弟节哀顺便。

**Comment by kevin-geng** [comment]
@KyleXie 哥们儿，哪里有3.1.3的版本？不是才3.1.1吗？
