### ISSUE TITLE
已经按照readme添加进白名单 还是授权获取access_token报错9824

### ISSUE THREAD

**Issue by baiyidjp** [sinaweibosdk/weibo_ios_sdk#158]
Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9824, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x146896ce0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9824, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9824}}, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSErrorFailingURLKey=https://api.weibo.com/oauth2/access_token, NSErrorFailingURLStringKey=https://api.weibo.com/oauth2/access_token, _kCFStreamErrorDomainKey=3}

**Comment by SeanChense** [comment]
明显是白名单添加失败了。
