### ISSUE TITLE
用了最新版本还是提示bitcode不支持

### ISSUE THREAD

**Issue by daohunliwei** [sinaweibosdk/weibo_ios_sdk#159]
用的是github下的3.1.1的版本，编译的时候依旧是不支持bitcode
ld: bitcode bundle could not be generated because '/Users/daodao/Documents/CodeWorld/OCProjects/Caishenkezhan/framework/libWeiboSDK.a(WBSDKNormalWebViewController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64

**Comment by inonomori** [comment]
我也是，无法Archive

**Comment by zhudengdengdeng** [comment]
+1
