### ISSUE TITLE
bitcode support支持问题

### ISSUE THREAD

**Issue by fxhpower** [sinaweibosdk/weibo_ios_sdk#160]
HI， 最近在archive bitcode support工程时，一直报错。
通过命令“ otool -l libWeiboSDK.a” 查看相关的编译信息， 没有发现
Section
  sectname __bitcode 
信息，看了微信等库是有相关信息的，麻烦重新编译下最新的静态库，在用上述命令查看下是否还有相关字节段

**Comment by zhudengdengdeng** [comment]
+1
