### ISSUE TITLE
无客户端打不开网页授权登陆页

### ISSUE THREAD

**Issue by witchnana** [sinaweibosdk/weibo_ios_sdk#161]
debug一直提示这个NSURLConnection/CFURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9814)

**Comment by TonnyTao** [comment]
因为这个bug, 被苹果拒了。

**Comment by xylinuxkernel** [comment]
我也是  我决定上线的时候 屏蔽掉微博三方登陆了 早知道就用sharesdk或者umeng 有新浪sdk 真多问题
