### ISSUE TITLE
求减少 git 库里的重复引用，减小下载体积，每次 pod update 想死的心都有了。

### ISSUE THREAD

**Issue by foxling** [sinaweibosdk/weibo_ios_sdk#162]

**Comment by LiRenee** [comment]
我不是太明白...

**Comment by foxling** [comment]
@LiRenee WebiboSDKDemo 目录下复制了一份 libWeiboSDK，用 pod :git 的方式更新的话，多下载15M+的内容，目前这个国际网络环境，pod update 的时候时间增加一倍。

**Comment by LiRenee** [comment]
我还不熟悉git

**Comment by foxling** [comment]
@LiRenee #167 请直接合并 pull request 吧，demo 目录下的那个 libWeiboSDK 是没有引用到的重复文件，删除后减少了25M的体积。

**Comment by chaixl** [comment]
请求尽快处理或者合并这个PR，pod update更新WeiboSDK简直是灾难！
