### ISSUE TITLE
cordova plugin add cordova-plugin-weibosdk  build 失败帮忙处理。

### ISSUE THREAD

**Issue by gitHubLie** [sinaweibosdk/weibo_ios_sdk#169]
build 一直这样无法成功编译。请处理解决。

while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSURLConnection
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSMutableData
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:@S@_NSRange
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSURLResponse
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSHTTPURLResponse
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSError
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSURL
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBQuickAuth.o):
warning: Could not resolve external type c:objc(cs)NSDate
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(NSDictionary+WBSDKKeyValue.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.0-7A220/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gccnypuzcgdpbcbxkksbfqqsmdwa/WeiboSDK-Prefix.pch.pch: No such file or directory
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(NSDictionary+WBSDKKeyValue.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.0-7A220/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gccnypuzcgdpbcbxkksbfqqsmdwa/WeiboSDK-Prefix.pch.pch: No object file for requested architecture
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(NSDictionary+WBSDKKeyValue.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(NSDictionary+WBSDKKeyValue.o):
warning: Could not resolve external type c:objc(cs)NSMutableDictionary
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.0-7A220/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gccnypuzcgdpbcbxkksbfqqsmdwa/WeiboSDK-Prefix.pch.pch: No such file or directory
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.0-7A220/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gccnypuzcgdpbcbxkksbfqqsmdwa/WeiboSDK-Prefix.pch.pch: No object file for requested architecture
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSUndoManager
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/zhengbin/workspace/zzApp/platforms/ios/zzApp/Plugins/cordova-plugin-weibosdk/libWeiboSDK.a(WBSDKProgressHUD.o):
warning: Could not resolve external type c:objc(cs)NSObject

**Comment by jdleung** [comment]
我是编译成功了，但显示这样的警告！
