### ISSUE TITLE
未安装微博客户端进行网页分享登陆失败

### ISSUE THREAD

**Issue by jianghuxiaoxia** [sinaweibosdk/weibo_ios_sdk#170]
在没有安装微博客户端的时候，用sdk分享是打开webview的一个网页进行授权登陆的，如果我用sdk demo中的 appKey 是成功的，换成我自己申请的AppKey就不行，输入账号密码，又跳转到登陆页面了，这是怎么回事？

**Comment by xylinuxkernel** [comment]
亲 你没发现demo中登陆成功后 在点击还要重新输入用户名和密码吗  这是不合理的
