### ISSUE TITLE
weibosdkjk_collectionClassLoadTimeInitialization 错误，请尽快解决

### ISSUE THREAD

**Issue by qianbodong** [sinaweibosdk/weibo_ios_sdk#171]
我集成了最新的sdk，收到 weibosdkjk_collectionClassLoadTimeInitialization + 0 (WBSDKJSONKit.m:889) 错误日志，请尽快修复，谢谢。

Incident Identifier: 4C50DA08-D541-4CC9-AEBF-76798AAF4450
CrashReporter Key:   6bd790e8d52cf0278d7b0bf2e8e0b6e2540be3dd
Hardware Model:      iPhone7,1
Process:             Data Usage [6348]
Path:                /private/var/mobile/Containers/Bundle/Application/1360C58D-41E5-4020-8A4F-CB8C2C7EE289/xxx.app/xxx
Identifier:          com.xxx.xxx
Version:             2.8.1 (2.8.0)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-12-13 20:22:55.762 +0800
Launch Time:         2015-12-13 20:22:55.601 +0800
OS Version:          iOS 8.4 (12H143)
Report Version:      105

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x000000007a25b94c
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   Data Usage                      0x00000001000868ec weibosdkjk_collectionClassLoadTimeInitialization + 0 (WBSDKJSONKit.m:889)
1   dyld                            0x00000001200253ec ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 32 (ImageLoaderMachO.cpp:1811)
2   dyld                            0x0000000120021688 ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 328 (ImageLoader.cpp:1017)
3   dyld                            0x00000001200214d8 ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 136 (ImageLoader.cpp:489)
4   dyld                            0x00000001200217a0 ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 80 (ImageLoader.cpp:504)
5   dyld                            0x0000000120016150 dyld::initializeMainExecutable() + 196 (dyld.cpp:1122)
6   dyld                            0x00000001200198bc dyld::_main(macho_header const_, unsigned long, int, char const__, char const__, char const__, unsigned long_) + 2664 (dyld.cpp:4864)
7   dyld                            0x0000000120015040 _dyld_start + 64 (dyldStartup.s:301)

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x000000016fdc3b78   x2: 0x000000016fdc3b88   x3: 0x000000016fdc3c18
    x4: 0x000000012003d1e0   x5: 0x0000000000000044   x6: 0x0000000000000000   x7: 0x0000000000000100
    x8: 0x0000000000000000   x9: 0x000000010003c000  x10: 0x000000010003c420  x11: 0x000000000000d800
   x12: 0x0000000000000050  x13: 0x00000000c4653601  x14: 0x00006c50534e5f5f  x15: 0x0000000000000061
   x16: 0x0000000194de9698  x17: 0x00000001945ae6b0  x18: 0x0000000000000000  x19: 0x0000000120041ef8
   x20: 0x000000012003d118  x21: 0x000000012003d1e0  x22: 0x0000000120038b13  x23: 0x00000001000868ec
   x24: 0x0000000000000001  x25: 0x0000000000000000  x26: 0x00000001002c52e8  x27: 0x000000010003caa8
   x28: 0x000000010003c508  fp: 0x000000016fdc01a0   lr: 0x0000000120025238
    sp: 0x000000016fdc0130   pc: 0x00000001000868ec cpsr: 0x20000000

**Comment by pxb2011** [comment]
![Uploading 截屏2024-08-13 17.08.05.png…]()

**Comment by pxb2011** [comment]
<img width="1214" alt="截屏2024-08-14 09 54 15" src="https://github.com/user-attachments/assets/51b6465a-5c3e-49ad-be71-33e80ef86011">
最新版本SDk又遇到这个问题了
