### ISSUE TITLE
新浪微博sdk

### ISSUE THREAD

**Issue by kevin-geng** [sinaweibosdk/weibo_ios_sdk#173]
我的iPhone手机，系统升级到9.2，在真机上运行，新浪微博的部分会报错，模拟器上可以，我用的Xcode版本是7.2。具体错误见下图。
![sina](https://cloud.githubusercontent.com/assets/12066186/11864874/09ecafc0-a4db-11e5-8568-97837595c444.png)

**Comment by wantry** [comment]
bitcode 设为no

**Comment by kevin-geng** [comment]
已经设置为NO了

**Comment by kevin-geng** [comment]
@wantry 已经设置为NO了（）
![image](https://cloud.githubusercontent.com/assets/12066186/12000247/aa8c3d0a-ab0d-11e5-9fdc-bd9ceeccabff.png)
![image](https://cloud.githubusercontent.com/assets/12066186/12000249/bfd2143c-ab0d-11e5-8795-561811114d68.png)

**Comment by kevin-geng** [comment]
谁还可以给出一些解决方案？急急急！

**Comment by Soul-Beats** [comment]
遇到相同问题。

**Comment by Soul-Beats** [comment]
我没有使用CocoaPods集成，但是我这个项目是使用了CocoaPods，是因为这个方面的原因吗

**Comment by kevin-geng** [comment]
![Uploading sinaWeibo.png…]()
看看这里的设置是不是有两个新浪微博的，如果是，去掉旧的，保留最新的。

**Comment by kevin-geng** [comment]
@Soul-Beats

**Comment by kevin-geng** [comment]
![Uploading sinaWeibo.png…]()
