### ISSUE TITLE
关于IDFA被拒，AdSupportFrameworkd处理方法

### ISSUE THREAD

**Issue by wantry** [sinaweibosdk/weibo_ios_sdk#175]
因为众所周知的原因，最新sinaweiboSDK中采集了IDFA（千万只草泥马飞过），我们在公元2015年12月17号提交，苹果在2015年12月22日凌晨1点开始审核，10分钟后被reject说使用了IDFA但是没发现广告。

好吧，说正事
判断项目是否采用IDFA，目前主要两种方法
方法1 terminal
进入工程目录，执行 
$ grep -r advertisingIdentifier .
显示
Binary file ./libWeiboSDK/libWeiboSDK.a matches
Binary file ./WeiboSDKDemo/libWeiboSDK/libWeiboSDK.a matches
说明包含IDFA的文件
<img width="585" alt="qq20151222-2 2x" src="https://cloud.githubusercontent.com/assets/7991302/11947613/735ce3d6-a8a4-11e5-95d4-2c1db8bd8a9e.png">

方法2  AirSign
官网下载后，打开编译生成好的IPA文件，在第二个Advanced标签底部，能看到是否使用了IDFA
![3 pic_hd](https://cloud.githubusercontent.com/assets/7991302/11947528/21a8a7f6-a8a3-11e5-9a90-77d68afc3217.jpg)

前面说了这么多，然并卵
解决方法
1 加广告
找个地方加个banner广告条，审核后关闭
2 移除微博SDK
看见丁香园不支持微博注册登录的
3 替换成老板微博SDK，修改配置
老版本的下载地址 github找
或者国内http://pan.baidu.com/s/1hqPVVTE

最后说几句
北上广深的程序员招聘上拉钩
但是租房呢 都上 http://www.zuber.im/
哈哈，谢谢各位程序员哥哥关注

**Comment by LiweiDong** [comment]
千万只草泥马飞过

**Comment by neufeng** [comment]
@wantry 能给一个AirSign的下载地址吗？这个工具看起来不错，呵呵

**Comment by LiweiDong** [comment]
好好的提供登录分享功能就行了  搞毛的IDFA啊   替换旧版本SDK了

**Comment by kkkelicheng** [comment]
呵呵呵
顶一个。

**Comment by kevin-geng** [comment]
最近使用微博sdk各种问题，该如何是好？

**Comment by LiweiDong** [comment]
用openShare吧

**Comment by kevin-geng** [comment]
@LiweiDong 嗯

**Comment by Yaou** [comment]
千万只草泥马飞过   +1

**Comment by smoothdvd** [comment]
最简单的：只勾选后两项：#2 (Attribute this app installation to a previously served advertisement) and #3 (Attribute an action taken within this app to a previously served advertisement)

**Comment by xylinuxkernel** [comment]
千万只草泥马+2

**Comment by bawn** [comment]
千万只草泥马+3
