### ISSUE TITLE
Pods 集成不了

### ISSUE THREAD

**Issue by bluemap** [sinaweibosdk/weibo_ios_sdk#177]
Pods集成不了，出现如下错误提示：
Specs satisfying the `WeiboSDK (from`https://github.com/sinaweibosdk/weibo_ios_sdk.git`)` dependency were found, but they required a higher minimum deployment target.

**Comment by whf881211** [comment]
pods无法集成。提示：
Pre-downloading: `WeiboSDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk.git`
[!] The `WeiboSDK` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | license: Missing license type.

**Comment by whf881211** [comment]
用的是pod 1.0.0.beta.2

**Comment by BenjaminX** [comment]
pod 1.0.0.beta.4 也会这样

**Comment by heySunMax** [comment]
楼上解决了？

**Comment by liu3399shuai** [comment]
更改pod如下
 
 pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/liu3399shuai/weibo_podspec/master/WeiboSDK.podspec'
 
 这样可以临时解决下
