### ISSUE TITLE
download error！

### ISSUE THREAD

**Issue by KillingOML** [sinaweibosdk/weibo_ios_sdk#178]
[!] Error installing WeiboSDK
[!] /usr/bin/git clone https://github.com/sinaweibosdk/weibo_ios_sdk.git /var/folders/3b/l59h22yn2n93s1fb0yqq84tw0000gn/T/d20151229-789-nzbn3e --single-branch --depth 1 --branch 3.1.3

Cloning into '/var/folders/3b/l59h22yn2n93s1fb0yqq84tw0000gn/T/d20151229-789-nzbn3e'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by todaylover** [comment]
遇到同样问题，这个仓库太大了，能reset --soft +  push -f清理一下么
