### ISSUE TITLE
sina微博 客户端授权页面 弹窗后立即消失 的问题 

### ISSUE THREAD

**Issue by Clear2** [sinaweibosdk/weibo_ios_sdk#182]
bundle Id 回调地址都么有问题，但是弹出授权界面立即返回

**Comment by Clear2** [comment]
[response isKindOfClass:WBAuthorizeResponse.class]

**Comment by Clear2** [comment]
[response isKindOfClass:WBAuthorizeResponse.class] 
[response statusCode] = 0

**Comment by guodong000** [comment]
看你这个情况应该是已经授权成功了，statusCode 如果等于0就表示授权成功。
微博客户端在授权未过期的时候，再次尝试授权时不会再让用户去点击，而是自动返回

**Comment by xylinuxkernel** [comment]
web view登陆 成功后，点击一闪而过
