### ISSUE TITLE
[WBMFPRSA getPublicKey] crash（pod以framework方式集成）

### ISSUE THREAD

**Issue by caojianhua** [sinaweibosdk/weibo_ios_sdk#183]
在swift工程中，pod设置成framework的方式集成，WeiboSDK.bundle会被打包到framework中，运行时[WBMFPRSA getPublicKey] crash

**Comment by keyfun** [comment]
我也是相同情況
做了一個實例測試，只要在 source_files 加了 swift 的文件，就會 crash
https://github.com/keyfun/weibo_ios_sdk

// 這代碼會 crash
WeiboSDK.registerApp("1234")

# no crash
  s.source_files = 'libWeiboSDK/*.{h,m}' 

# crash
  s.source_files = 'libWeiboSDK/*.{h,m}', 'Pod/Classes/SinaWeiboManager.swift'

**Comment by wenxin3262** [comment]
我也是Swift的工程用pod集成的挂在这里，有什么解决办法么？

**Comment by dapenggao** [comment]
这个和 #192 是同样的原因，WeiboSDK.bundle只能放在`mainBundle`.
