### ISSUE TITLE
sso授权登陆，无客户端网页登陆成功后没有logout为什么每次点击授权都要重新来一遍

### ISSUE THREAD

**Issue by xylinuxkernel** [sinaweibosdk/weibo_ios_sdk#189]
sso授权登陆，无客户端网页登陆成功后没有logout为什么每次点击授权都要重新来一遍。如图每次sso授权都要重来一次。
![simulator screen shot 2016 1 25 6 16 38](https://cloud.githubusercontent.com/assets/9544495/12548211/cb47e5cc-c38f-11e5-8944-fdbb31b23a3a.png)

**Comment by xylinuxkernel** [comment]
问题是不会和有客户端一样 登陆成功了 出现授权应用的界面，为什么

**Comment by xylinuxkernel** [comment]
就不能解答下？？

**Comment by wenxin3262** [comment]
授权不是给你token了么？楼主恶补下基本常识吧~
