### ISSUE TITLE
不应当使用[NSBundle mainBundle]来获取WeiboSDK.bundle

### ISSUE THREAD

**Issue by ghost** [sinaweibosdk/weibo_ios_sdk#192]
如下图，若`WeiboSDK.bundle`不放在`mainBundle`的话，就会导致找不到文件，进而引发`+ registerApp`崩溃。所以应当使用[`+ bundleWithIdentifier:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/index.html#//apple_ref/occ/clm/NSBundle/bundleWithIdentifier:)来寻找bundle。苹果对于这一方法的文档也是如此建议：

> This method is typically used by frameworks and plug-ins to locate their own bundle at runtime.

![screen shot 2016-02-19 at 5 05 06 pm](https://cloud.githubusercontent.com/assets/9143914/13170947/f65e9c66-d72a-11e5-8089-25bba249c5fb.png)

**Comment by dapenggao** [comment]
这也是可能导致 #74, #117, #129, #133 等崩溃的原因。

**Comment by wods** [comment]
现在还没解决，pod 现在都用module了，资源文件所在的bundle都是库的bundle啊

**Comment by stonyw** [comment]
2017年都要过去了，readme里面提供的 微博 账号是几年没有更新的，邮箱写了邮件被退信，压根没人管。我也不想加qq群。
这个问题并不复杂，绕过办法也就是要把资源的bundle重新加到主工程里。不过由于并不是主工程的资源，所以这样的临时方案做让人很恼火。

**Comment by DikeyKing** [comment]
同样遇到这个问题...

**Comment by houxg** [comment]
还是没有解决

**Comment by semnyqu** [comment]
感觉这个SDK凉凉了，一直没有人更新，歇菜了吧新郎

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。

**Comment by stonyw** [comment]
1 3年半才有人来看这个问题，真不容易。作为开发者我都放弃这个sdk了。
2 答非所问。sdk做好sdk的事情，要获取main bundle信息就通过正确的方式获取。非要用一个错误的耦合的方法来做另外一件事情。这种项目还是不要假装什么开放了，丢不起人。

**Comment by DikeyKing** [comment]
> 由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。

无论如何，这种让程序直接闪退的代码也是不应该出现的。

**Comment by whde** [comment]
我放在了mainBundle，14.7.1这个版本一天收集到三个，有个用户连续上报两次，但是这个用户第三次启动就没问题了.... 很迷
