### ISSUE TITLE
此工程WeiboSDK.podspec 在 pod lib lint 的时候会出错

### ISSUE THREAD

**Issue by aelam** [sinaweibosdk/weibo_ios_sdk#193]
```
 -> WeiboSDK (3.1.3)
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | license: Missing license type.
```

你这边提交到Specs可能不是用的`pod repo push`

**Comment by BenjaminX** [comment]
Pre-downloading: `WeiboSDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk.git`
[!] The `WeiboSDK` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | license: Missing license type.
