### ISSUE TITLE
使用SDK后 编译警告太多太多了

### ISSUE THREAD

**Issue by MulderLiu** [sinaweibosdk/weibo_ios_sdk#198]
使用SDK后 编译警告太多太多了
xcode 7.2

warning: Could not resolve external type c:objc(cs)NSUndoManager
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSArray
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSString
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSDictionary
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSObject
while processing /Users/vsmac/Desktop/VSIOS/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKRelationshipButton.o):
warning: Could not resolve external type c:objc(cs)NSObject

**Comment by gogozs** [comment]
+1

**Comment by gogozs** [comment]
http://www.swiftmi.com/topic/362.html this will help
