### ISSUE TITLE
pods 无法集成SDK

### ISSUE THREAD

**Issue by woshiqqt** [sinaweibosdk/weibo_ios_sdk#200]
Pre-downloading: `WeiboSDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk.git`, commit `61e4bf36084b3fda1f73e4099e6c29bf8758e335`
[!] The `WeiboSDK` pod failed to validate due to 3 errors:
    - ERROR | attributes: Missing required attribute `authors`.
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `homepage`.
    - ERROR | attributes: Missing required attribute `summary`.
    - WARN  | license: Missing license type.

**Comment by heySunMax** [comment]
我也是这个问题。。什么情况，楼上解决了么？

**Comment by jiangyancong** [comment]
升级到cocoaPod 1.0之后出现的，cocoaPods对于podSpec的处理规则有更新，请新浪赶紧处理！！！！

**Comment by Kojmay** [comment]
将cocoapods版本退回到1.0以下

**Comment by jiangyancong** [comment]
@Kojmay 目测就是podSpec里面这几个字段没有写，authors，homepage， summary。。我不能为了一个SDK将pod降到1.0以下，1.0之后podfile有些语法在旧版本不适用。

**Comment by rocbird** [comment]
自己建一個 podspec,  把缺少的東西補上 .... 然後改用本地的 podspec 可以暫時解決這個問題

pod 'WeiboSDK', :podspec => '~/Projects/weibo.podspec'

我是先這樣解了.  正解當然是請 sina 的人自己把 github 上的 podspec 更新才行

**Comment by jiangyancong** [comment]
@rocbird 谢谢，我也打算这么干。

**Comment by liu3399shuai** [comment]
更改pod如下

pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/liu3399shuai/weibo_podspec/master/WeiboSDK.podspec'

这样可以临时解决下
