### ISSUE TITLE
微博第三方登陆客户端无回调

### ISSUE THREAD

**Issue by furuiCQ** [sinaweibosdk/weibo_ios_sdk#206]
IOS版集成第三方登陆，如果手机上有微博客户端，调用客户端后跳转到微博客户端的授权页面，过会就直接进入微博首页了。无回调返回，无法获得用户信息。

**Comment by xialiuliu** [comment]
遇到相同的问题，而且不是所有手机都出现

**Comment by furuiCQ** [comment]
已解决，检查回调页面以及Appid ，BunldeId，包名是否一致。

**Comment by xialiuliu** [comment]
Appid ，BunldeId一致,而且客户端无回调的情况只出现在个别手机，目前手机型号为Iphone5s 系统为9.2
