### ISSUE TITLE
libWeiboSDK.a在后台输出了日志

### ISSUE THREAD

**Issue by dengzhp** [sinaweibosdk/weibo_ios_sdk#207]
"Cannot do the upload process, the time from last uploadTime is not above 30 seconds!"

并没有做任何微博操作，好像会自动偷偷上传数据？

**Comment by jinxiansen** [comment]
查出来原因了吗，这句话从哪里出来的卧槽，我也是控制台莫名其妙就有这个。

**Comment by dengzhp** [comment]
@jinxiansen 没回应，看来要搞个大新闻吧

**Comment by fq050766** [comment]
我这也是，Cannot do the upload process, the time from last uploadTime is not above 90 seconds!

**Comment by jinxiansen** [comment]
无奈。

**Comment by jinxiansen** [comment]
但是不影响上线审核。

**Comment by qiaoxueshi** [comment]
我这也遇到了 不太好重现

**Comment by douxinchun** [comment]
Cannot do the upload process, the time from last uploadTime is not above 30 seconds!

**Comment by sixleaves** [comment]
Cannot do the upload process, the time from last uploadTime is not above 90 seconds!

**Comment by zhangdan** [comment]
我也出现了，应该如何修复呢？
Cannot do the upload process, the time from last uploadTime is not above 30 seconds!
