### ISSUE TITLE
出现链接错误：duplicate symbols for architecture i386

### ISSUE THREAD

**Issue by xinchrome** [sinaweibosdk/weibo_ios_sdk#208]
编译官方iOS SDK，会出现duplicate symbols链接错误，错误信息就像下面这样：
duplicate symbol _llvm.cmdline in:
    /Users/xin/ref/code/ios/weibo_ios_sdk-master/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o)
    /Users/xin/ref/code/ios/weibo_ios_sdk-master/libWeiboSDK/libWeiboSDK.a(WBSDKUtil.o)

需要的静态库都已经被导入，但还是无法通过编译，也就没办法用。

**Comment by xinchrome** [comment]
有没有人知道怎么解决？我用的Xcode6

**Comment by aelam** [comment]
Xcode应该会告诉你到底是哪两个文件和哪个symbol重复定义
