### ISSUE TITLE
在没安装微博应用程序的情况下发送SSO认证请求，微博网络界面显示无记录或超时导致连接消失。

### ISSUE THREAD

**Issue by graeme** [sinaweibosdk/weibo_ios_sdk#21]
您好，

在没安装微博应用程序的情况下发送SSO认证请求，微博网络界面显示无记录或超时导致连接消失。屏幕显示的是一个空白的页面而且不关闭。我们希望当上述的情况发生时，界面能显示一个错误信息。

希望在上述问题上得到您的协助。

谢谢。
Graeme

**Comment by toby20130333** [comment]
我使用最新版本也是这样的情况，显示网络错误，我的网络是好的
