### ISSUE TITLE
-[NSConcreteMutableData wbsdk_base64EncodedString]: unrecognized selector sent to instance 这种错误楼主也不修复一下，让我们拿来就可以用了

### ISSUE THREAD

**Issue by haojianyun** [sinaweibosdk/weibo_ios_sdk#215]
-[NSConcreteMutableData wbsdk_base64EncodedString]: unrecognized selector sent to instance
这种错误楼主也不修复一下，让我们拿来就可以用了，每次都得在网上找方案，修改build设置，不想修改设置啊

**Comment by devjia** [comment]
因为SDK里面用了category, 所以需要在Other Linker Flag 里添加-ObjC.
PS,这并不是错误哦,而且文档中有说明哦.
