### ISSUE TITLE
CocoaPods WeiboSDK为什么不更新？

### ISSUE THREAD

**Issue by Dwarven** [sinaweibosdk/weibo_ios_sdk#231]
能靠谱点么？

**Comment by itdongbaojun** [comment]
同问关于最新版本的3.1.4的cocoapods问题

**Comment by wujianbotju** [comment]
原因是他们没有更新pod spec的版本号，虽然代码改了，但是版本还是3.1.4. 而CocoaPods检测更新的唯一依据就是pod的version，所以在CocoaPods看来根本就没有更新。还有别的库我也遇到了同样的问题，然后我去CocoaPods的论坛反馈，他们虽然帮我刷新了他们那边的代码缓存，但是建议遇到这种情况应该联系库的开发者。

说了这么多，我已经联系了WeiSDK github的开发，他们应该会很快release a new version.

**Comment by Dwarven** [comment]
@wujianbotju 没更新版本号CocoaPods是push不上去的，而且pod上WeiboSDK根本就没有3.1.4，更别说新的版本号了，我就不明白他们官方pod为啥不做更新？
