### ISSUE TITLE
SDK包太大了(24.2MB!!!)

### ISSUE THREAD

**Issue by JasonWorking** [sinaweibosdk/weibo_ios_sdk#236]
一个libWeiboSDK.a 有24MB多, 能否支持自定义裁剪? 比如我们只通过微博客户端来分享内容, 那就不需要登录等模块在SDK中.

**Comment by MulderLiu** [comment]
同意 我只需要一个客户端分享的功能 不需要认证授权那些

**Comment by BennieAtGitHub** [comment]
这么大的包，在国内，几KB下载速度里面，加上公司内外网交叉引用的Pod，更到我想吐。
