### ISSUE TITLE
为什么weiboSDK 与SBJSON 有冲突呢？

### ISSUE THREAD

**Issue by leewaycn** [sinaweibosdk/weibo_ios_sdk#240]
为什么weiboSDK 与SBJSON 有冲突呢？

我一加入weiboSDK就报SBJSON duplicate symbols

**Comment by xiaoyuAhaha** [comment]
大兄弟 还在用SBJSON啊  赶紧换了吧

**Comment by LSsoftware** [comment]
@leewaycn 一些全局参数命名冲突。是weiboSDK也用了SBJSON的缘故，把你自己的SBJSON删了，或者把你自己SBJSON中的一些全局参数删掉或重新命名。
