### ISSUE TITLE
跳转到微博授权界面确认后，不需要人工点击确认，会自动确认登陆

### ISSUE THREAD

**Issue by nenhall** [sinaweibosdk/weibo_ios_sdk#241]
跳转到微博授权界面确认后，不需要人工点击确认，会自动确认登陆，而且登陆结果是登陆成功的！不知是我哪个参数错了还是怎么回事，谁知道是怎么回事，提供下解决方案，谢谢！

**Comment by DikeyKing** [comment]
同遇……楼主找到原因了？

**Comment by giantss** [comment]
同遇……以前是好的最近测试就这样了，楼主找到原因了？

**Comment by cocos543** [comment]
个人认为这个微博一个非常不合理的设定.按照文档说的就是access_token有效期内会自动登录不需要人工点确认.所以你想解决这个问题,办法就是做一个让access_token失效的操作.iOS代码就是这样
[WeiboSDK logOutWithToken:authCode delegate:nil withTag:@"251"];
我强烈建议微博把这个功能去掉,参考QQ第三方登录吧.

**Comment by NegHao** [comment]
后面仔细研究发现时微博内部这样设置的，具体哪个版本开始就没深入了

**Comment by nenhall** [comment]
我已确认这个是微博的设计，我们没办法解决
