### ISSUE TITLE
当工程修改为生成dSYM文件时，sdk报出警告，该如何解决

### ISSUE THREAD

**Issue by holyhan** [sinaweibosdk/weibo_ios_sdk#242]
警告如下：
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.3-7D175/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-fjkxjmlcdvnxhndamneukgcqsgbl/WeiboSDK-Prefix.pch.pch: No such file or directory

**Comment by whlsxl** [comment]
strip -S libWeiboSDK.a
can clean the warning, but will lost debug information.
