### ISSUE TITLE
现在 https TLS 1.0 在 iOS10 是无效的了

### ISSUE THREAD

**Issue by li6185377** [sinaweibosdk/weibo_ios_sdk#243]
在 pull request 里面 已经有人提交了解决办法

**Comment by wodear** [comment]
IOS10 不能授权啊

**Comment by li6185377** [comment]
https://github.com/sinaweibosdk/weibo_ios_sdk/pull/181 需要在info.plist 里面修改下

**Comment by wodear** [comment]
怎么改呢？求赐教

**Comment by wodear** [comment]
<key>NSTemporaryExceptionMinimumTLSVersion</key>
			  	<string>TLSv1.1</string>
