### ISSUE TITLE
最新版3.1.4在开启Bitcode下不能Archive

### ISSUE THREAD

**Issue by Cliplay** [sinaweibosdk/weibo_ios_sdk#245]
你好，我直接拿你们的Demo，Enable Bitcode后Archive时报错：

clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)

Enable Bitcode选No后就正常了。

请帮忙看一下是什么问题。谢谢！

PS：如果不能用Bitcode，整个App会变的很大，导致没办法集成weibo这个sdk。

**Comment by yzxcool123** [comment]
微博的SDK好像很久没有更新了, 也不支持bitcode实在是蛋疼.
