### ISSUE TITLE
授权登录跳往授权页面后，登录完成自动跳回了我的app界面了

### ISSUE THREAD

**Issue by giantss** [sinaweibosdk/weibo_ios_sdk#250]
授权登录跳往授权页面后，登录完成自动跳回了我的app界面了，调试发现获取用户信息接口在浏览器中显示如下图，求解。。
![5645a500-9fe5-2555-0dcf-31e4cd1ca754](https://cloud.githubusercontent.com/assets/13778798/18416265/0f5b19a2-7842-11e6-956c-9927261165e1.png)

**Comment by giantss** [comment]
@nickcheng @yirenjun @dannion @iBcker @hongtaozhy @

**Comment by walker-ll** [comment]
+1

**Comment by giantss** [comment]
@walker-ll @nickcheng @yirenjun @dannion @iBcker 能麻烦告诉一下怎么回事吗？
