### ISSUE TITLE
紧急：微博libWeiboSDK.a包含苹果私有API

### ISSUE THREAD

**Issue by pingguoilove** [sinaweibosdk/weibo_ios_sdk#253]
审核时候被拒，原因是由于使用了records这个私有API。
经过以下步骤进行排查
1. 到workspace中grep了一下records，发现libWeiboSDK等一系列的文件包含records关键字
2.经过和其它SDK的技术人员沟通，发现没有用records这个私有API，都是在注释里面
3. 怀疑libWeiboSDK,但无法确认，github找了一个私有API检测工具，发现里面列出了records。去掉weiboSDK后，发现不再包含records。

望紧急解决一下

**Comment by itdongbaojun** [comment]
@pingguoilove 我想确认一下你们使用的什么版本的SDK

**Comment by pingguoilove** [comment]
@itdongbaojun ```[WebSDK getSDKVersion]```输出是```003143000```

**Comment by huakucha** [comment]
@itdongbaojun 请问一下 能定位到具体哪个头文件包含了records吗

**Comment by pingguoilove** [comment]
@itdongbaojun 这个问题确认了吗？董神
