### ISSUE TITLE
[紧急]未安装微博客户端时 网页登录失效

### ISSUE THREAD

**Issue by yxztj** [sinaweibosdk/weibo_ios_sdk#255]
同时存在于安卓和iOS客户端，测试了只要使用以下新登录方式的app都存在问题（即刻，穷游等）
输入完用户名密码，点击登录没有反应。
![img_0003](https://cloud.githubusercontent.com/assets/3334458/18898496/a5441502-8564-11e6-8458-ff17a41a1eac.PNG)

而使用另一种网页登录的app没有问题
![img_0374](https://cloud.githubusercontent.com/assets/3334458/18898573/11a57894-8565-11e6-9de8-b85e8b7caf70.PNG)

**Comment by WangXiaoxi** [comment]
+1

**Comment by yxztj** [comment]
使用sdk官方demo也能复现问题

**Comment by yaroslavubisoft** [comment]
+1 
this issue first occurred yesterday, the day before that login page was working.

**Comment by Binglin** [comment]
+1

**Comment by yaroslavubisoft** [comment]
Seems to be working now

**Comment by erinsnow** [comment]
Seems to not be working again
