### ISSUE TITLE
libWeiboSDK.a 2.4在 iPad上没有判断是否安装了微博HD.

### ISSUE THREAD

**Issue by JasonWorking** [sinaweibosdk/weibo_ios_sdk#262]
在iPad上安装了微博HD时, [WeiboSDK isWeiboAppInstalled]返回NO. 
Hopper看了下你们的实现,isWeiboAppInstalled里你们只尝试了canOpenURL: sinaweibo:// 没有尝试 sinaweibohd://. 

![图片](https://zos.alipayobjects.com/rmsportal/wMUJFwqIqzSjGYy.png)

**Comment by hite** [comment]
赞，分析
