### ISSUE TITLE
sdk 数据库操作 crash

### ISSUE THREAD

**Issue by volcno** [sinaweibosdk/weibo_ios_sdk#263]
hi 开发者，最新的sdk上数据库操作有比较严重的crash，在fabric上统计影响面比较广，麻烦帮忙看下
Crashed: wbsdk_statistics_io_queue
0  libsqlite3.dylib               0x191cc9b80 (null) + 111248
1  libsqlite3.dylib               0x191cc9b78 (null) + 111240
2  libsqlite3.dylib               0x191cc9b98 (null) + 111272
3  libsqlite3.dylib               0x191c490cc (null) + 37504
4  libsqlite3.dylib               0x191ccaab4 (null) + 115140
5  libsqlite3.dylib               0x191c41d2c (null) + 7904
6  libsqlite3.dylib               0x191c23348 (null) + 10664
7  libsqlite3.dylib               0x191c22ca0 (null) + 8960
8  libsqlite3.dylib               0x191c21ed0 (null) + 5424
9  libsqlite3.dylib               0x191c214c4 (null) + 2852
10 libsqlite3.dylib               0x191c21178 (null) + 2008
11 LINK                           0x100aa7c28 -[WBSDKFMDatabase executeQuery:withArgumentsInArray:orDictionary:orVAList:](WBSDKFMDatabase.m:530)
12 LINK                           0x100aa8100 -[WBSDKFMDatabase executeQuery:](WBSDKFMDatabase.m:655)
13 LINK                           0x100aba068 +[WBSDKStatisticsRecord(WBSDKDataBaseStore) selectDB:fromTime:toTime:](WBSDKStatisticsRecord.m:157)
14 LINK                           0x100acdf30 __57-[WBSDKDBObjectStore objectsFromTime:toTime:resultBlock:]_block_invoke (WBSDKDBObjectStore.m:185)
15 LINK                           0x100aba644 __49-[WBSDKDBManager readDatabaseBlockInTransaction:]_block_invoke (WBSDKDBManager.m:87)
16 libdispatch.dylib              0x1905b9200 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x1905b91c0 _dispatch_client_callout + 16
18 libdispatch.dylib              0x1905c6008 _dispatch_continuation_pop + 576
19 libdispatch.dylib              0x1905c5ccc _dispatch_async_redirect_invoke + 628
20 libdispatch.dylib              0x1905c938c _dispatch_root_queue_drain + 572
21 libdispatch.dylib              0x1905c90ec _dispatch_worker_thread3 + 124
22 libsystem_pthread.dylib        0x1907c12c8 _pthread_wqthread + 1288
23 libsystem_pthread.dylib        0x1907c0db4 start_wqthread + 4

**Comment by handwill** [comment]
我同样也出现了，友盟统计到的。还没有解决吗

**Comment by Jason8Zhang** [comment]
我们项目bugly上面也有收集到
