### ISSUE TITLE
网页分享，登陆微博后，返回{"error":"appkey lost!", "pos":"1"}

### ISSUE THREAD

**Issue by DeepMissea** [sinaweibosdk/weibo_ios_sdk#264]
SDK最新的，有什么解决方法么？

**Comment by GWesley** [comment]
手里有台10.1.1  也是报这个错误

**Comment by RayRiver** [comment]
同出现了，以前好像还可以分享成功的
https://github.com/sinaweibosdk/weibo_android_sdk/issues/47
从14年就有的问题，没有人解答吗？
是后台系统间歇性的问题吗

**Comment by knight2010** [comment]
{"error":"appkey lost!","pos":"1"}

只在某一台手机上重现错误， 抓包也试过，还是不明原因。😂

**Comment by jonz-tech** [comment]
所以这个问题2年了还没找到原因吗？

**Comment by 3minutes** [comment]
测试今天报了这个问题，我用自己的手机可以正常分享。

**Comment by witchnana** [comment]
2020.6.19日也有同样的问题。手机正常，iPad登录完就报这个错误

**Comment by zhaocongqing** [comment]
2020.09.05： 有微博客户端分享正常，网页登录分享报：{"error":"appkey lost!","pos":"2"}

**Comment by c0dingEverything** [comment]
2020.10.23： 有微博客户端分享正常，网页登录分享报：{"error":"appkey lost!","pos":"2"}
