### ISSUE TITLE
调用关注用户https://api.weibo.com/2/friendships/create.json接口，返回403错误

### ISSUE THREAD

**Issue by pujiaxin33** [sinaweibosdk/weibo_ios_sdk#266]
这是response的细节：
<NSHTTPURLResponse: 0x174438880> { URL: https://api.weibo.com/2/friendships/create.json?screen_name=%E5%92%95%E5%92%9A%E7%BD%91&oauth_sign=6ea7cac&aid=01AsOtYMEcmK82NV5FG_aO5ntlRAt8kV7GybjK98nLk2euWx8.&access_token=2.00Y9KeHGbZrvBDf7a5b50e37pcKXUB&oauth_timestamp=1477553309 } { status code: 403, headers {
    "Content-Encoding" = gzip;
    "Content-Type" = "application/json;charset=UTF-8";
    Date = "Thu, 27 Oct 2016 07:28:29 GMT";
    Server = "nginx/1.6.1";
    Vary = "Accept-Encoding";
    "api-server-ip" = "10.75.5.67";
} }
我们APP一直都是这样使用接口，为什么最近报错了呢？

**Comment by WenkyYuan** [comment]
我看API文档里面这个接口是post吧？你这是get哦

**Comment by WenkyYuan** [comment]
我遇到iOS SDK调用这个接口返回10014	Insufficient app permissions错误，但是在我的应用管理-接口管理里面没有看到有关注接口哦，已有权限/申请权限里面都找不到这个接口，是不是我的开发账号级别不够？怎么申请开通？

**Comment by pujiaxin33** [comment]
@WenkyYuan 您好，目前策略调整，friendships/create接口暂时无法开通，关注需求请详见：http://open.weibo.com/wiki/Scope，这是微博的售后工程师给我的回复。我已经没有再使用这个接口，这是直接用safari打开对应微博的主页，不能直接进行关注了。

**Comment by WenkyYuan** [comment]
谢谢。我已经把scope的值设为follow_app_official_microblog，完全符合产品的需求
