### ISSUE TITLE
使用cocoapods引入微博sdk速度巨慢

### ISSUE THREAD

**Issue by ibanezz** [sinaweibosdk/weibo_ios_sdk#269]
为什么使用cocoapods引入微博sdk速度巨慢？可以优化下嘛？

**Comment by LSsoftware** [comment]
@ibanezz  每周空闲时间执行下pod setup，在加入项目的时候执行pod install。
下载慢可能因为更新的东西多，也可能当前网络原因。同比情况下，开着vpn稍快。有的库比如Google的库就要开vpn下，国内网下不了。

**Comment by Chakery** [comment]
开着VPN也是巨慢

**Comment by LSsoftware** [comment]
今天详细看了下微博sdk的.a 文件是25M 😂😂😂
可能用了静态库打包......早点换成动态库吧😂😂😂

**Comment by Chakery** [comment]
够呛吧，凑合着用呗。

**Comment by Chakery** [comment]
反正不是经常pod，就算pod了也是--no-repo-update

**Comment by LSsoftware** [comment]
@Chakery 这确实是个办法，不过repo还是有更新需求的，两者间尺度要把握好

**Comment by Chakery** [comment]
还是期待速度能快一点吧……

**Comment by y500** [comment]
太坑爹了这个.a的文件，经常pod update失败

**Comment by y500** [comment]
pod 'WeiboSDK', :git => "https://git.coding.net/yanqizhou/weibo_ios_sdk.git"

这样会好一点儿

**Comment by x6587305** [comment]
的确巨慢啊。我一大堆 pod的东西。 每次都是卡在它动不了。别人的都没问题。

**Comment by Chakery** [comment]
@LSsoftware 
上次有说道用`--no-repo-update`，当时没意识到，其实也是不行的，一样会重新下载。
因为pod指定了git的路径，所以无论如何，每次pod都会重新去下载。
好像`WeiboSDK `这个名字被占用了，所以只能指定路径。
