### ISSUE TITLE
ios10 下数据库操作闪退

### ISSUE THREAD

**Issue by leung-c** [sinaweibosdk/weibo_ios_sdk#270]
堆栈信息如下：
Start Application received signal SIGSEGV 
	-> translating『 0x1007b59f0 』=> 
	-> translating『 0x100539b24 』=> -[WBSDKFMDatabase executeQuery:withArgumentsInArray:orDictionary:orVAList:] /Users/insomnia/Desktop/weiboSDK/branches/v3.1.2/WeiboSDKSrc/WeiboSDK/WBSDKFMDatabase.m: line 495
	-> translating『 0x100539ffc 』=> -[WBSDKFMDatabase executeQuery:] /Users/insomnia/Desktop/weiboSDK/branches/v3.1.2/WeiboSDKSrc/WeiboSDK/WBSDKFMDatabase.m: line 648
	-> translating『 0x10054bf64 』=> 
	-> translating『 0x10055fe2c 』=> __57-[WBSDKDBObjectStore objectsFromTime:toTime:resultBlock:]_block_invoke /Users/insomnia/Desktop/weiboSDK/branches/v3.1.2/WeiboSDKSrc/WeiboSDK/WBSDKDBObjectStore.m: line 183
	-> translating『 0x10054c540 』=> __49-[WBSDKDBManager readDatabaseBlockInTransaction:]_block_invoke /Users/insomnia/Desktop/weiboSDK/branches/v3.1.2/WeiboSDKSrc/WeiboSDK/WBSDKDBManager.m: line 84
=> End Application received signal SIGSEGV

**Comment by rickytan** [comment]
同，请尽快修复！
![image](https://cloud.githubusercontent.com/assets/1250207/20452276/c4aecdba-ae40-11e6-8cd0-1e021b2349d9.png)

**Comment by seuzxh** [comment]
有sina的developer在维护这个吗？这个问题导致的崩溃还是比较多的，请尽快回复

**Comment by huamiLilg** [comment]
同样

**Comment by Jason8Zhang** [comment]
感觉都没有管了

**Comment by niuxinhuai** [comment]
没有解决方法吗？
