### ISSUE TITLE
所有接口替换为https

### ISSUE THREAD

**Issue by ph661** [sinaweibosdk/weibo_ios_sdk#272]
2017年1月1号之后，iOS审核app的所有接口必须是https的~  这个现在是已经支持了~  没看到相关记录~

**Comment by HugoXX** [comment]
是否已经支持了？

**Comment by danplin** [comment]
同问，是否已经完全支持苹果的ATS标准

**Comment by dulingkang** [comment]
我觉得 以 weibo 的做法，应该不会支持，因为他们技术不行！

**Comment by firebear** [comment]
哈哈，笑死我了。
不是他们技术不行，是新浪不重视这点儿鸟事儿。技术人员可能都换了几茬了，不出事没有人来管。
你们也不用担心，先不说ATS的最后期限看起来坚持不住，就算是坚持住了，你们提交审核的时候，说明一下新浪这个插件应用广泛但是技术支持很差只能这样估计app store会理解的。:D

**Comment by dulingkang** [comment]
weibo 这么大一公司，app做的也不怎么样，定位权限就有问题，现在基本上sdk都支持ATS了，就weibo还是不支持...

**Comment by firebear** [comment]
Android连Gradle都还没支持呢吧，iOS好歹支持Pod啊。
不过现在微博也不断衰弱了，我的用户里面，用微博的比例比较低了。新浪有些团队的技术管理是比较薄弱，跟这个公司太“上市”了有关吧。但是换作你，这个不带来多少收益的产品，你会投入多少资源呢？
大家能凑合就凑合着过吧 。。。。。
