### ISSUE TITLE
isWeiboAppInstalled  检测不到微博客户端

### ISSUE THREAD

**Issue by algorithm9** [sinaweibosdk/weibo_ios_sdk#273]
手机明明已经安装微博客户端，但是 isWeiboAppInstalled接口 返回NO ,手机的操作系统是iOS10.1.1  。求帮助

**Comment by LSsoftware** [comment]
你自己使用canopen试试

**Comment by algorithm9** [comment]
嗯，问题找到了，是没有配LSApplicationQueriesSchemes ,是后来仔细看了主页说明发现的。不好意思，给你们添麻烦了。
