### ISSUE TITLE
微博登录[WeiboSDK registerApp:xxx]闪退

### ISSUE THREAD

**Issue by QminGame** [sinaweibosdk/weibo_ios_sdk#275]
有人碰到这个问题吗 [WeiboSDK registerApp:appkey];直接挂逼！

**Comment by langxuelan** [comment]
碰到过 不知道怎么解决，而且没有日志

**Comment by FelixYin66** [comment]
遇到同一个情况

**Comment by FelixYin66** [comment]
问题已解决：https://github.com/sinaweibosdk/weibo_ios_sdk/issues/133
