### ISSUE TITLE
ATS

### ISSUE THREAD

**Issue by winfredgit** [sinaweibosdk/weibo_ios_sdk#278]
最新版本是否支持HTTPS?

**Comment by melovegithub** [comment]
http://weibo.com/1904178193/EhPhdxk4s?type=comment,,,好像支持了

**Comment by huhudage** [comment]
只要使用最新版本就可以了吗？还是说要在 Info.plist 里添加例外才可以？

github上留的QQ群根本加不进去，留的邮箱也发不了邮件，啥情况啊。。。
