### ISSUE TITLE
使用pod后 当没有安装微博客户端时弹出的网页 左上角关闭按钮不显示

### ISSUE THREAD

**Issue by sagexy** [sinaweibosdk/weibo_ios_sdk#28]
如题 如下图 左上角关闭按钮不显示 使用pod 'Weibo' 添加
![img_0636](https://cloud.githubusercontent.com/assets/4734448/3716312/e072e856-1608-11e4-9e25-c2714f233e97.JPG)

**Comment by jfl913** [comment]
我试了下，也不行。项目里下下来的bundle里有那个close.png，但是代码里那个image就是nil的。

**Comment by dannion** [comment]
spec中bundle文件路径问题描述导致。目前3.0.1版本已修复。
