### ISSUE TITLE
libWeiboSDK.a registerApp崩溃(use_frameworks!)

### ISSUE THREAD

**Issue by dev-gao** [sinaweibosdk/weibo_ios_sdk#284]
您好，
       最近在将 pod 库改为frameworks时遇到了一个必现崩溃问题。

      描述：Podfile 中使用 use_frameworks! 时将会把所有第三方库打成 framework 。这种情况下调用 [WeiboSDK registerApp:appid] 将会必现崩溃，而在非 framwork 环境下运行正常。

       请问是否有什么解决方案呢？use_frameworks! 差不多是大势所趋，期待回复~ 谢谢。

**Comment by odyyy** [comment]
我也遇到了同样的问题，好痛苦

**Comment by welkiner** [comment]
把weibo的bundle手动放到主工程中即可

**Comment by dev-gao** [comment]
"把weibo的bundle手动放到主工程中即可"

**Comment by dev-gao** [comment]
"把weibo的bundle手动放到主工程中即可"    试过了，不可用
