### ISSUE TITLE
ios系统上分享，手机安装新浪客户端的话，可跳转到客户端进行分享，没有安装客户端的时候,调用app内的网页登陆后分享不了

### ISSUE THREAD

**Issue by jxbb012265** [sinaweibosdk/weibo_ios_sdk#297]
手机安装新浪客户端的话，可以跳转到新浪微博客户端，进行分享，没有安装新浪微博客户端的时候，提示
-canOpenURL: failed for URL: "sinaweibo://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
-canOpenURL: failed for URL: "sinaweibohd://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
-canOpenURL: failed for URL: "weibosdk://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

**Comment by Lychoe** [comment]
同求
