### ISSUE TITLE
iOS ipv6微博登陆网页加载不成功

### ISSUE THREAD

**Issue by zhouzhouguoguo** [sinaweibosdk/weibo_ios_sdk#307]
iOS ipv6微博登陆网页加载不成功  提交到app store审查，几次了都被微博登陆不了给拒绝了，但自己搭建ipv6环境却没有问题，，？

**Comment by an0** [comment]
我也是，两个多礼拜，据了 n 次，电话都打过了，刚联系了 Apple Developer Technical Support，等结果中。

**Comment by fifty8** [comment]
此问题 +1

**Comment by fifty8** [comment]
Btw just submit the App Store review 10 times, and you will pass the review one of those times. 

Stupid Weibo server and its slow networks
