### ISSUE TITLE
使用3.2.0版本分享失败

### ISSUE THREAD

**Issue by softwind0214** [sinaweibosdk/weibo_ios_sdk#309]
可以分享，方法返回值显示成功，但是手机微博客户端里面显示发送失败，显示

> 10006 source paramter(appkey) is missing

网上很多人都碰到这个问题。
有能解决的吗？

**Comment by zhrmghgfff** [comment]
同求

**Comment by sinaweibosdk** [comment]
已解决，使用新版sdk
