### ISSUE TITLE
新浪微博客户端更新到4.5版本后，分享图片失败

### ISSUE THREAD

**Issue by wtndcs** [sinaweibosdk/weibo_ios_sdk#31]
更新到4.5版本后，在iOS7上分享图片，图片预览正确但是过于模糊；分享后的微博只有文字没有图片；附带的Demo工程可以重现该问题

**Comment by aelam** [comment]
问题好像依然存在

**Comment by Ming1992** [comment]
WBWebpageObject 多媒体消息是被屏蔽了嘛？为什么分享出去的 看不到图片也看不到链接呢

**Comment by zihang-wu** [comment]
为啥我在没有安装微博客户端时，WBWebpageObject分享 分享出去 不显示连接也不显示图片，谁能解决吗？
