### ISSUE TITLE
微博api 2/statuses/share.json  接口无法调用

### ISSUE THREAD

**Issue by Z-Seven** [sinaweibosdk/weibo_ios_sdk#311]
显示错误：Error Domain=Insufficient app permissions! Code=10014 "(null)" UserInfo={error=Insufficient app permissions!, error_code=10014, request=/2/statuses/upload.json} 但我们开发者平台的权限都有

**Comment by hongliang5623** [comment]
现在遇到的错误是：{"error":"text not find domain!","error_code":10017,"request":"/2/statuses/share.json"}
求看

**Comment by zzy131250** [comment]
需要在微博文本中添加安全域名，见http://open.weibo.com/wiki/2/statuses/share

**Comment by hongliang5623** [comment]
@zzy131250 有没有遇到概率性的失败，比如我试了三次，前两次失败，第三次成功了

**Comment by zzy131250** [comment]
@hongliang5623  在7.31遇到过调用10次成功一次的情况，问开放平台，他说接口最近不稳定，建议移动端使用SDK，PC端使用分享组件。。。不过今天似乎修复了，可以正常发微博了 : )

**Comment by gebitang** [comment]
现在这个接口已经被禁用了吗？ 

```
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.weibo.com/2/statuses/share.json
```
