### ISSUE TITLE
 首次安装微博，分享问题

### ISSUE THREAD

**Issue by whoneedfire** [sinaweibosdk/weibo_ios_sdk#312]
首次安装微博，使用sdk分享
WBSendMessageToWeiboRequest *weiboRequest = [WBSendMessageToWeiboRequest requestWithMessage:message authInfo:authorize access_token:nil];
    weiboRequest.userInfo = nil;
    BOOL isSuccess =  [WeiboSDK sendRequest:weiboRequest];
调起微博后跳回app，-(void)didReceiveWeiboResponse:(WBBaseResponse *)response返回WeiboSDKResponseStatusCodeUnknown。
之后使用正常，有解决方法吗？

**Comment by yangfangkuo** [comment]
同样问题

**Comment by syosan** [comment]
有人回答了？有解决了吗？
