### ISSUE TITLE
关于 WeiBoSDK.bundle 的位置

### ISSUE THREAD

**Issue by stephenwzl** [sinaweibosdk/weibo_ios_sdk#315]
看起来你们在代码里写死了 WeiBoSDK.bundle 是从 MainBundle 下获取的，这就导致一个问题：
当我将 WeiBoSDK 封装在自己的某个 pod 中，并 use_framework，resource bundle 是不会被拷贝到 Main Bundle 下的。只会存在于 framework bundle 下。 

又导致一个更严重的问题：App 启动时初始化 WeiBoSDK，貌似有个后台线程会去读取 WeiBoSDK.bundle 内的 证书，这个线程会 crash 

希望你们能修改 bundle 获取的实现，我是坚决不会把 WeiBoSDK.bundle 放在 MainBundle 下的

**Comment by yimiaodaren** [comment]
微博开发者的路还很长～～～ 如果不行～就不接了～～ 顶你

**Comment by stonyw** [comment]
#192

**Comment by DongDongDongDong** [comment]
> WeiBoSDK

老哥，你后来是怎么处理这个问题的呢？
bundle直接放主工程下了？

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。
