### ISSUE TITLE
+[WeiboSDK firstStart]: unrecognized selector sent to class 0x100ebe4b0

### ISSUE THREAD

**Issue by devjiangzhou** [sinaweibosdk/weibo_ios_sdk#318]
version : 3.2.0

NSInvalidArgumentException
+[WeiboSDK firstStart]: unrecognized selector sent to class 0x100ebe4b0

0 CoreFoundation | ___exceptionPreprocess + 124
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | ___CFExceptionProem
3 CoreFoundation | ____forwarding___ + 916
4 CoreFoundation | _CF_forwarding_prep_0 + 92
5 Hoosho | -[WBAidManager request:didFinishLoadingWithResult:] (WBAidManager.m:434)
6 Hoosho | -[WBHttpRequest handleResponseData:] (WBHttpRequest.m:564)
7 Hoosho | -[WBHttpRequest connectionDidFinishLoading:] (WBHttpRequest.m:522)

@nickcheng @yirenjun @dannion @iBcker @hongtaozhy  麻烦尽快给一个回应谢谢

**Comment by wleii** [comment]
同样遇到了这个问题
再次编译运行项目之后就正常了。 (会不会引起用户下载新版本的第一次运行会 crash 🤔

**Comment by ismilesky** [comment]
我也遇到了，请问会影响用户使用吗？？

**Comment by devjiangzhou** [comment]
@wleii @ismilesky 已经导致我新发版本了。 
我用nm看了下3.2.0 和 3.2.1版本的header。在3.2.1版本已经去掉这个没有IMP的方法了。
再次吐槽。

**Comment by wangyan12** [comment]
3.2.1在哪下载的。我刚下载的怎么还是出现第一次崩溃啊

**Comment by ismilesky** [comment]
同问，最新的sdk还是3.2.0啊

**Comment by ismilesky** [comment]
@devjiangzhou

**Comment by ismilesky** [comment]
我看了最新的sdk，确实没这个 `firstStart` 这个方法，但是首次崩溃比较坑啊，这sdk怎么维护的啊！

**Comment by devjiangzhou** [comment]
@wangyan12 pod search Weibo_SDK
@ismilesky 赶紧升级吧。。 这种低级错误，实在无语

**Comment by zyc410703** [comment]
@devjiangzhou  你下了最新的SDK没有这个问题了吗？我下了最新的官方Demo还有这个问题啊

**Comment by devjiangzhou** [comment]
没了。3.2.1
Sent from Mail Master
在2017年08月10日 23:10，Dynamic Framework 写道： @devjiangzhou  你下了最新的SDK没有这个问题了吗？我下了最新的官方Demo还有这个问题啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sinaweibosdk/weibo_ios_sdk","title":"sinaweibosdk/weibo_ios_sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sinaweibosdk/weibo_ios_sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zyc410703 in #318: @devjiangzhou  你下了最新的SDK没有这个问题了吗？我下了最新的官方Demo还有这个问题啊"}],"action":{"name":"View Issue","url":"https://github.com/sinaweibosdk/weibo_ios_sdk/issues/318#issuecomment-321580750"}}}

**Comment by zyc410703** [comment]
哎，最新一次更新不是八天前嘛，我今晚刚从这里又clone了一份 还是老样子啊 你那边怎么可以了

**Comment by devjiangzhou** [comment]
再检查一次是否是3.2.1版本 ，如果是这个错误 我可以确认没了Sent from Mail Master
            在2017年08月10日 23:34，Dynamic Framework 写道： 哎，最新一次更新不是八天前嘛，我今晚刚从这里又clone了一份 还是老样子啊 你那边怎么可以了

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sinaweibosdk/weibo_ios_sdk","title":"sinaweibosdk/weibo_ios_sdk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/sinaweibosdk/weibo_ios_sdk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zyc410703 in #318: 哎，最新一次更新不是八天前嘛，我今晚刚从这里又clone了一份 还是老样子啊 你那边怎么可以了"}],"action":{"name":"View Issue","url":"https://github.com/sinaweibosdk/weibo_ios_sdk/issues/318#issuecomment-321587913"}}}

**Comment by wangyan12** [comment]
@devjiangzhou ，能把你的3.2.1发一份给我吗？804229142@qq.com.谢谢了

**Comment by ismilesky** [comment]
@devjiangzhou  你升级的最新版本是多少，3.2.1， 还会出现崩溃吗？ 我现在用的就3.2.1还是会出现那个问题

**Comment by ismilesky** [comment]
@devjiangzhou  能把你的更新的3.2.1给我以一份吗？？  923654855@qq.com 。3Q

**Comment by devjiangzhou** [comment]
@ismilesky 
@wangyan12 
@zyc410703 

我使用的是pod方式
pod 'Weibo_SDK', '3.2.1'

**Comment by ismilesky** [comment]
pod search Weibo_SDK  命令有问题啊， ` Unable to find a pod with name, author, summary, or description matching `Weibo_SDK` `  @devjiangzhou

**Comment by ismilesky** [comment]
@wangyan12  @devjiangzhou   看一下你们的sdk版本号， 我的打印的是 003203000

**Comment by wangyan12** [comment]
我的也是WeiboSDK 003203000

**Comment by devjiangzhou** [comment]
![image](https://user-images.githubusercontent.com/1578465/29200068-d61e9386-7e84-11e7-9d89-ecd00c8582d8.png)
如果没有请更新repo
pod repo update

**Comment by devjiangzhou** [comment]
我打印的也是。 @wangyan12 @ismilesky 请再次确认是否是这个错误。我更新了版本后，已经没有这个错误了。
