### ISSUE TITLE
刚开始注册就崩溃，WeiboSDK.registerApp(WeiboAppKey)

### ISSUE THREAD

**Issue by Z-JaDe** [sinaweibosdk/weibo_ios_sdk#319]
![image](https://user-images.githubusercontent.com/12668657/28992238-79903468-79c9-11e7-8494-532ea02e2d0e.png)

Security`SecCertificateCopyPublicKey:
这里报错，坏地址错误

难道是我添加的姿势不对？ 
之前是用pod添加的没事，后来因为我要把第三方的东西封装到framework里面，就用了手动添加，注册的时候就直接不行了

**Comment by webfrogs** [comment]
工程里包含微博的那个 bundle。

**Comment by hannibalzj** [comment]
的确是那个bundle 没包含
