### ISSUE TITLE
pod install 挂了

### ISSUE THREAD

**Issue by yun-percy** [sinaweibosdk/weibo_ios_sdk#320]
昨天你更新之后pod install就挂了，大哥。看下，必现。 你就改了个名称……库没改，版本都没改

**Comment by webfrogs** [comment]
将之前 Podfile 里的

```
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
```

改为

```
pod "Weibo_SDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
```

**Comment by Coolred** [comment]
相關說明文件並未異動，由於更改後原本的引用的路徑需要調整，請問是否確定變更名稱？

**Comment by webfrogs** [comment]
@Coolred 确实是要修改引用路径，我也不清楚这个库的作者基于什么原因，修改了 podspec 文件的名字。

**Comment by FanJianRong** [comment]
为什么要改名字啊？？？Weibo_SDK？？？？以后还会改吗？

**Comment by lv2023100** [comment]
所以之後要用Weibo_SDK??
還是會改回WeiboSDK??

**Comment by ismilesky** [comment]
我是用了 pod Weibo_SDK  , pod install 没反应啊

**Comment by EZElkins** [comment]
强烈建议改完后更新下README

**Comment by 463292462** [comment]
还得引入 AssetsLibrary和Photos框架

**Comment by vitoziv** [comment]
https://github.com/sinaweibosdk/weibo_ios_sdk/commit/c0fb42c35ce6ce6449d7de9755e4c4651b18e3cd
改动在这里，改动原因要开发者自己才知道了，看起来就像是个拍脑袋的决定...... 👎

**Comment by yimingtang** [comment]
新浪微博这 SDK 是来搞笑的吗？不推到 CocoaPods 官方仓库就算了，还瞎改名称。这种 breaking change 太草率了。

**不专业**

**Comment by alfredcc** [comment]
呵呵

**Comment by voidjoker** [comment]
真的是辣鸡

**Comment by FengDeng** [comment]
这是呵呵  readme也不重点说一下。spec重新拉了，pod重新装了，害的我差点系统都重装了。
