### ISSUE TITLE
+[UIDevice wbsdk_plainDeviceID]: unrecognized selector sent to class 0x199f58af0

### ISSUE THREAD

**Issue by yimiaodaren** [sinaweibosdk/weibo_ios_sdk#321]
缺少类么？引入是不是有点问题？

我是把3.2.1的文件下载到我的库中，再项目中引入，启动weibosdk时就报错？

**Comment by atom2ueki** [comment]
@yimiaodaren 额，已经几年了，但还是回复下，要在Other Linker Flags下加上-ObjC, 原因就是这个category是objective c的，这个flag帮忙链接至swift项目
