### ISSUE TITLE
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[WeiboSDK firstStart]: unrecognized selector sent to class 0xa8804'

### ISSUE THREAD

**Issue by zyc410703** [sinaweibosdk/weibo_ios_sdk#322]
开发按照官方文档和Demo进行第三方登录开发，出现模拟器或者真机第一次启动在注册AppKey时直接崩溃报错，第二次就没有问题，并且官方Demo也有同样问题报错如下：
2017-08-10 22:28:24.507 SDKDemo[6726:94113] +[WeiboSDK firstStart]: unrecognized selector sent to class 0xa8804
2017-08-10 22:28:24.514 SDKDemo[6726:94113] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[WeiboSDK firstStart]: unrecognized selector sent to class 0xa8804'
*** First throw call stack:
(
	0   CoreFoundation                      0x03aafded __exceptionPreprocess + 189
	1   libobjc.A.dylib                     0x0357ad6f objc_exception_throw + 49
	2   CoreFoundation                      0x03b214e8 +[NSObject(NSObject) doesNotRecognizeSelector:] + 136
	3   CoreFoundation                      0x03a35a8d ___forwarding___ + 941
	4   CoreFoundation                      0x03a356be _CF_forwarding_prep_0 + 14
	5   SDKDemo                             0x0006cb49 -[WBAidManager request:didFinishLoadingWithResult:] + 668
	6   SDKDemo                             0x00072c6f -[WBHttpRequest handleResponseData:] + 302
	7   SDKDemo                             0x000729ba -[WBHttpRequest connectionDidFinishLoading:] + 49
	8   CFNetwork                           0x06477c00 ___ZL32_NSURLConnectionDidFinishLoadingP16_CFURLConnectionPKv_block_invoke + 52
	9   CFNetwork                           0x064737f7 __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 55
	10  CFNetwork                           0x064737b8 -[NSURLConnectionInternalConnection invokeForDelegate:] + 142
	11  CFNetwork                           0x06473716 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 187
	12  CFNetwork                           0x0647364a -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 42
	13  CFNetwork                           0x06477bc7 _ZL32_NSURLConnectionDidFinishLoadingP16_CFURLConnectionPKv + 36
	14  CFNetwork                           0x06477b1d ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 95
	15  CFNetwork                           0x0660b221 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 107
	16  libdispatch.dylib                   0x06b23cc9 _dispatch_client_callout + 14
	17  libdispatch.dylib                   0x06afcfd8 _dispatch_block_invoke_direct + 384
	18  libdispatch.dylib                   0x06b080cd ___dispatch_block_create_block_invoke + 20
	19  CFNetwork                           0x06473520 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 24
	20  CoreFoundation                      0x03a03d97 CFArrayApplyFunction + 55
	21  CFNetwork                           0x064733e4 _ZN19RunloopBlockContext7performEv + 134
	22  CFNetwork                           0x064d8b0a _ZThn16_N19RunloopBlockContext24multiplexerClientPerformEv + 20
	23  CFNetwork                           0x0647328d _ZN17MultiplexerSource7performEv + 307
	24  CFNetwork                           0x064730b9 _ZN17MultiplexerSource8_performEPv + 61
	25  CoreFoundation                      0x03a54a5f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	26  CoreFoundation                      0x03a3a1c4 __CFRunLoopDoSources0 + 500
	27  CoreFoundation                      0x03a3969c __CFRunLoopRun + 1084
	28  CoreFoundation                      0x03a38fd4 CFRunLoopRunSpecific + 372
	29  CoreFoundation                      0x03a38e4b CFRunLoopRunInMode + 123
	30  GraphicsServices                    0x05e97a7a GSEventRunModal + 71
	31  GraphicsServices                    0x05e9795f GSEventRun + 80
	32  UIKit                               0x012a3cb9 UIApplicationMain + 148
	33  SDKDemo                             0x0005e3a1 main + 96
	34  libdyld.dylib                       0x06b5e779 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException 
请问是什么问题呢，谢谢~

**Comment by wangyan12** [comment]
我也遇到这个问题，不知道上线会不会出现问题

**Comment by zyc410703** [comment]
@wangyan12 对呀 关键查不到什么解决方案 不知道到底是不是官方的问题 那个人说他的就可以 但是明明我昨晚下的都还不行

**Comment by wangyan12** [comment]
@zyc410703 我新下载的3.2.1也不行。我考虑先找个以前的版本试一试

**Comment by tobatha** [comment]
我们线上就遇到了....fuck, 怎么办!

**Comment by tobatha** [comment]
微博sdk开发这帮人, 先是自己乱改pod库名, 现在这种完全无解的崩溃问题.......以后再也不敢集成微博sdk了沃日~

**Comment by ismilesky** [comment]
这就是个坑啊！ sdk开发的人呢，没人来解释解释啊啊！！ 邮件都不能发

**Comment by zyc410703** [comment]
@tobatha @ismilesky 很忧伤啊 解决了吗？我这边没啥卵用啊

**Comment by ismilesky** [comment]
我换了别的版本了，3.1.1的版本， 只能这样了。。 。。 @zyc410703

**Comment by zyc410703** [comment]
@wangyan12 @tobatha @ismilesky 

import Foundation

// MARK: - WeiboFix - firstStart
extension WeiboSDK {
    class func firstStart() {
        print("-->:firstStart")
    }
}
写一个扩展 把这个方法重写一次 你们看看行不行

**Comment by gonghao** [comment]
同样的问题，线上一堆 Crashlog，关注

**Comment by chaoyakai** [comment]
@ismilesky 我想知道历史版本从哪里下载啊

**Comment by ismilesky** [comment]
pod的有3.1.3，可以下下来 @chaoyakai

**Comment by gongdandan** [comment]
最新的SDK终于解决了这个问题了，终于能好好好用了

**Comment by zhugexiaobo** [comment]
#327  问题还是存在，微博有没有活人能 @ 一下的？

**Comment by LoyaltyWu** [comment]
最新版本的sdk解决了这个问题了吗？哪个版本是没有这个问题的呀？

**Comment by Z-JaDe** [comment]
也是醉了，微博是倒闭了吗？这么久的问题还没解决。在自己手机上测试都没问题，上线时苹果却说崩溃。+[WeiboSDK firstStart]: unrecognized selector sent to class

**Comment by Z-JaDe** [comment]
要不是老板要求 我早就把微博分享去掉了

**Comment by ismilesky** [comment]
不知道这个方法有没有用到，不行写个分类把这个方法替换掉
