### ISSUE TITLE
[!] Unable to find a specification for 'WeiboSDK'.

### ISSUE THREAD

**Issue by zzyspace** [sinaweibosdk/weibo_ios_sdk#323]
```
pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'
```

pod install 的时候一直显示这个错误.

**Comment by DevNewbee** [comment]
我也是。。还以为我的repo出了问题 
还`remove, setup`浪费了一个小时了。

**Comment by zzyspace** [comment]
@DevNewbee 看来很多人这样, 我朋友也这样. 官方引起关注一下啊, 这都没法用了

**Comment by zzyspace** [comment]
@DevNewbee #320 这个解决方法可行.

**Comment by DevNewbee** [comment]
@zzyspace 终于可以了！！ 后来搞的整个pod编译一直报错缺失文件，只能重新整合，发现微博这个sdk完全没法加载，幸好还有这个方法。谢谢！
他们难道忙到连更新ReadMe的时间都没有了，好气。

**Comment by zzyspace** [comment]
@DevNewbee 毕竟是大厂[摊手]

**Comment by sinaweibosdk** [comment]
已解决，使用新版sdk
