### ISSUE TITLE
WBNewVideoObject will save a copy of video file to Camera Roll

### ISSUE THREAD

**Issue by alexiscn** [sinaweibosdk/weibo_ios_sdk#324]
Using `WBNewVideoObject` to share video to Weibo will save a copy of video file to user's Camera Roll. Can you add a property to auto-delete that copy when share completed.

**Comment by vitoziv** [comment]
@alexiscn 你可以正常分享出视频吗？我使用 WBNewVideoObject 不管我传了什么视频文件，分享的时候都会报错说视频文件找不到

**Comment by alexiscn** [comment]
@vitoziv Yes, I can share video to Weibo. 

1. first make sure that your video is in your application sandbox or in Photo Library
2. creat a weibo message

```swift
let videoObject = WBNewVideoObject()
videoObject.delegate = self
videoObject.isShareToStory = false
videoObject.addVideo(videoURL) // videoURL should be filePath URL within your app

self.message = WBMessageObject()
self.message?.text = "test"
self.message?.videoObject = videoObject
```

3. and in `wbsdk_TransferDidReceive` delegate do actual send.

```swift
if let msg = self.message {
            let request = WBSendMessageToWeiboRequest.request(withMessage: msg) as! WBSendMessageToWeiboRequest
            WeiboSDK.send(request)
}
```

**Comment by hannibalzj** [comment]
@alexiscn 您好, 有个问题请教下. 使用WBNewVideoObject分享视频, 在我的应用启动后第一次分享视频是正常的, 再次分享视频就会出现跳转到微博客户端.但是一直都停留在微博的启动页.
您出现过这个问题吗?

**Comment by alexiscn** [comment]
@hannibalzj nope.. everything work likes a charm except this topic issue

**Comment by zyy18758064815** [comment]
@alexiscn  如果微博相册权限没开的话，我直接分享视频，跳转到微博后，微博直接闪退或者出现异常
