### ISSUE TITLE
在某些机型上初次启动就崩溃

### ISSUE THREAD

**Issue by imadeit** [sinaweibosdk/weibo_ios_sdk#327]
在某些iPhone上存在初次启动闪退的问题：以下是错误日志

0  CoreFoundation                 0x186ba51b8 __exceptionPreprocess
1  libobjc.A.dylib                0x1855dc55c objc_exception_throw
2  CoreFoundation                 0x186bac1a8 __CFExceptionProem
3  CoreFoundation                 0x186ba9270 ___forwarding___
4  CoreFoundation                 0x186aa280c _CF_forwarding_prep_0
5  Ufunwow                        0x1003a584c -[WBAidManager request:didFinishLoadingWithResult:] (WBAidManager.m:434)
6  Ufunwow                        0x1003ab070 -[WBHttpRequest handleResponseData:] (WBHttpRequest.m:564)
7  Ufunwow                        0x1003aade4 -[WBHttpRequest connectionDidFinishLoading:] (WBHttpRequest.m:522)
8  CFNetwork                      0x1874015bc __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke
9  CFNetwork                      0x18740154c -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]
10 CFNetwork                      0x1874016c0 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:]
11 CFNetwork                      0x1873238bc ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke
12 CFNetwork                      0x1873217ac ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2
13 libdispatch.dylib              0x185a2e1bc _dispatch_client_callout
14 libdispatch.dylib              0x185a39ab0 _dispatch_block_invoke_direct
15 CFNetwork                      0x1873de598 RunloopBlockContext::_invoke_block(void const*, void*)
16 CoreFoundation                 0x186a7dc18 CFArrayApplyFunction
17 CFNetwork                      0x1873de47c RunloopBlockContext::perform()
18 CFNetwork                      0x1873df7a4 MultiplexerSource::perform()
19 CFNetwork                      0x1873df510 MultiplexerSource::_perform(void*)
20 CoreFoundation                 0x186b52b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
21 CoreFoundation                 0x186b524a4 __CFRunLoopDoSources0
22 CoreFoundation                 0x186b500a4 __CFRunLoopRun
23 CoreFoundation                 0x186a7e2b8 CFRunLoopRunSpecific
24 GraphicsServices               0x188532198 GSEventRunModal

该问题困扰我们很久了，麻烦尽快解决！谢谢！
Leon

**Comment by 416215983** [comment]
我也遇到同样的问题  麻烦解决的同学 可以提供一下解决方法

**Comment by jonsnowwinterfell** [comment]
嗯 老版本的 会出现问题，新版本的又有idfa  adsupport.framework 这样的问题 欲哭无泪
