### ISSUE TITLE
sdk 3.2.3 crash (demo app crash too)

### ISSUE THREAD

**Issue by cissusnar** [sinaweibosdk/weibo_ios_sdk#332]
使用最新sdk分享图片和文字, 会crash, demo app也会crash

![img_0031](https://user-images.githubusercontent.com/2087003/31652278-34471af8-b2e4-11e7-8391-c38a437e9f1e.PNG)
![2017-10-17 3 36 59](https://user-images.githubusercontent.com/2087003/31652287-3913f3da-b2e4-11e7-9a02-5c44b3620405.png)

**Comment by igiu1988** [comment]
这个问题解决了吗？我也遇到了同样的问题
