### ISSUE TITLE
不能通过WBImageObject的addImages方法在分享中加入图片

### ISSUE THREAD

**Issue by doluvor** [sinaweibosdk/weibo_ios_sdk#334]
**问题描述**:

  分享到微博不能通过WBImageObject的**addImages:(NSArray<UIImage *>*)imageArray**方法加入图片，使用imageData分享没有问题。
  错误描述为：
  “**WeiboSDK send WBSendMessageToWeiboRequest error : 消息的图片内容中，图片数据与图片数组只能存在一项，图片数据不能为空并且大小不能超过10M,图片数组元素个数需要在1-9之间**”

**期望结果**:

  能通过addImages方法分享多张图片

**相关代码**:

```swift
        let message = WBMessageObject()      
        let imageObject = WBImageObject()   
        imageObject.add([image])
        message.imageObject = imageObject
        let request = WBSendMessageToWeiboRequest.request(withMessage: message) as! WBBaseRequest    
        WeiboSDK.send(request)
```

**微博SDK版本**

```
  3.2.3
```

**开发平台**

  - [*] iOS

**Xcode version**:

```
  9.0
```

**Swift version**:

```
  4.0
```

**Comment by doluvor** [comment]
原来addImages是一个异步方法，需要在delegate回调中再调用sendMessage

**Comment by weifans** [comment]
这鬼设计，不说谁知道，哥们你怎么知道的？
