### ISSUE TITLE
微博分享图片必须传imageData的问题

### ISSUE THREAD

**Issue by EverMe** [sinaweibosdk/weibo_ios_sdk#339]
微博分享图片内容时，需要创建WBImageObject对象 给imageData属性赋值，这就要求分享时，客户端必须拿到了imageData，也就是图片已经下载到了本地，可我的项目中，分享时的图片是后端指定的url，本地不一定有，我需要先从本地缓存中查询，没有的话再去下载得到Data 赋值给imageData属性，微博SDK中不支持只传递图片URL便可完成图片分享，这让我感到很苦恼。而且我发现微信和QQ的SDK中，都已经添加了对只传递imageUrl便可完成图片分享的支持，不知道微博有没有打算添加这样的支持呢？
ps:多媒体的分享时，缩略图字段也只有thumbnailData，没有thumbnailUrl。。。。

**Comment by shevakuilin** [comment]
我想问多图该怎么传imageData...合并data也没效果，只显示第一张图
