### ISSUE TITLE
网页分享WBWebpageObject，为啥指定了thumbnailData，但在微博里面却看不到图片

### ISSUE THREAD

**Issue by nuoxia** [sinaweibosdk/weibo_ios_sdk#340]
如题所示，网页分享WBWebpageObject中指定了thumbnailData，但分享到微博里却看不到图片

**Comment by wendongsheng** [comment]
我遇到了同样的问题，请问楼主解决了么？

**Comment by kaynewbie** [comment]
WeiboSDK demo 中，WebPage 分享缩略图也是不显示的。
并且，注释说 `WBBaseMediaObject（WBWebpageObject 的父类）会被废弃，不再显示为linkcard样式，只显示为普通网络连接`。
这可能就是导致缩略图不显示的原因。

一个替代方案就是用 `image 分享` 替代 `url 分享`。
