### ISSUE TITLE
Xamarin iOS Binding 找不到 symbol 的问题。

### ISSUE THREAD

**Issue by u8621011** [sinaweibosdk/weibo_ios_sdk#342]
你好，

在尝试使用 Xamarin iOS binding 时，它(pcl-type ios project) 的 linker 会有以下讯息，不知道是否是有 symbol 没有 compile 到 static library 内又不知道这情况如何处理呢?

Undefined symbols for architecture arm64:
2>    "_OBJC_CLASS_$_PHAsset", referenced from:
2>        objc-class-ref in libWeiboSDK.a(WBImageObject.o)
2>        objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
2>    "_OBJC_CLASS_$_PHAssetChangeRequest", referenced from:
2>        objc-class-ref in libWeiboSDK.a(WBImageObject.o)
2>        objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
2>    "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
2>        objc-class-ref in libWeiboSDK.a(WBImageObject.o)
2>        objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
2>    "_SCNetworkReachabilityGetFlags", referenced from:
2>        -[WBSDKReachability connectionRequired] in libWeiboSDK.a(WBSDKReachability.o)
2>        -[WBSDKReachability currentReachabilityStatus] in libWeiboSDK.a(WBSDKReachability.o)
2>    "_SCNetworkReachabilityScheduleWithRunLoop", referenced from:
2>        -[WBSDKReachability startNotifier] in libWeiboSDK.a(WBSDKReachability.o)
2>    "_SCNetworkReachabilityUnscheduleFromRunLoop", referenced from:
2>        -[WBSDKReachability stopNotifier] in libWeiboSDK.a(WBSDKReachability.o)
2>    "_SCNetworkReachabilitySetCallback", referenced from:
2>        -[WBSDKReachability startNotifier] in libWeiboSDK.a(WBSDKReachability.o)
2>    "_SCNetworkReachabilityCreateWithAddress", referenced from:
2>        +[WBSDKReachability reachabilityWithAddress:] in libWeiboSDK.a(WBSDKReachability.o)
2>    "_SCNetworkReachabilityCreateWithName", referenced from:
2>        +[WBSDKReachability reachabilityWithHostName:] in libWeiboSDK.a(WBSDKReachability.o)
2>  ld: symbol(s) not found for architecture arm64
2>  clang: error: linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined Objective-C class: PHAsset. The symbol '_OBJC_CLASS_$_PHAsset' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined Objective-C class: PHAssetChangeRequest. The symbol '_OBJC_CLASS_$_PHAssetChangeRequest' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined Objective-C class: PHPhotoLibrary. The symbol '_OBJC_CLASS_$_PHPhotoLibrary' could not be found in any of the libraries or frameworks linked with your application.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilityGetFlags. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilityScheduleWithRunLoop. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilityUnscheduleFromRunLoop. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilitySetCallback. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilityCreateWithAddress. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed, undefined symbol: _SCNetworkReachabilityCreateWithName. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(777,3): error : Native linking failed. Please review the build log.

**Comment by u8621011** [comment]
我想我找到原因啦，我 xamarin 下的解法给你参考。原因是还少了 Photos.framework

[assembly: LinkWith("libWeiboSDK.a", LinkTarget.Simulator | LinkTarget.ArmV7 | LinkTarget.ArmV7s, ForceLoad = true, SmartLink = true,
    Frameworks = "QuartzCore ImageIO SystemConfiguration Security CoreTelephony CoreText UIKit Foundation CoreGraphics Photos",
    // -lsqlite3.0 ==> link libsqlite3.dylib, -lz ==> link libz.dylib
    LinkerFlags = "-ObjC -all_load -lc++ -lsqlite3.0 -lz"
    )]

**Comment by van8tka** [comment]
@u8621011 Thanks so much for answer this issue, I tried binding TikTokOpenSDK and had this problem and loose three days. Thank's and good luck!
