### ISSUE TITLE
WBSDKWebView 导航栏问题

### ISSUE THREAD

**Issue by Dombo-Y** [sinaweibosdk/weibo_ios_sdk#348]
![cc148768-7351-45b9-9caf-a011aa862940](https://user-images.githubusercontent.com/11814460/34604382-824ecece-f242-11e7-99fe-a887f92bd986.png)
导入项目里，这个进度条的y 轴不对，我想更改 nav 的 字体颜色怎么更改呢，这个WBSDKWebView没有外漏

**Comment by zqybin** [comment]
同样的问题
![simulator screen shot - iphone 8 - 2018-03-16 at 15 32 34](https://user-images.githubusercontent.com/11238545/37508729-50e04934-292f-11e8-826b-2aad26001390.png)

**Comment by sinaweibosdk** [comment]
请使用sdk自带的webview
