### ISSUE TITLE
网页分享后手动关闭网页没有成功回调

### ISSUE THREAD

**Issue by abcjjy** [sinaweibosdk/weibo_ios_sdk#350]
调出网页分享，分享提交以后，出现3秒后自动关闭的网页。这时如果手动关闭，就会只有一个用户取消的回调，而没有分享成功的回调。如果等待3秒后自动关闭，就会有分享成功回调。

**Comment by wendongsheng** [comment]
哥们，你那边网页分享是分享的图片和文字么？为什么我这网页分享图片和文字报错了，方便给指导一下吗？我的QQ:925771631

**Comment by wushiyu541** [comment]
没有微博客户端，调起网页分享，同样遇到了这个问题，但是分享成功后，如果点击关闭，回调的响应是 WBAuthorizeResponse ,而且状态码是 ‘用户取消’。可否有个回复呢？开发人员不维护这个SDK的吗？
