### ISSUE TITLE
ADsupport.framework的问题

### ISSUE THREAD

**Issue by jonsnowwinterfell** [sinaweibosdk/weibo_ios_sdk#356]
我这的app不集成ADsupport.framework  ，项目里没有这个东西，苹果还以这个问题拒掉我的App，看你们的说明说删掉即可，但是我这项目都没有用，让我我删掉什么东西，把你们的 SDK  删掉么 ，如果删掉，微博分享还能用么？求大神速度解答。谢谢了。

**Comment by jonsnowwinterfell** [comment]
换成老版本SDK的 会崩溃（第一次装机的时候  会崩溃）因为你们 sdk  的问题被拒了两次。。

**Comment by sinaweibosdk** [comment]
微博sdk需要这个库
