### ISSUE TITLE
未安装微博客户端时 授权登录完成自动跳回，但被卡住在 __45+[WeiboSDK directlySendResponseToCurrentApp:]_block_invoke

### ISSUE THREAD

**Issue by MyBar** [sinaweibosdk/weibo_ios_sdk#360]
未安装微博客户端时 授权登录完成自动跳回，但被卡住在 __45+[WeiboSDK directlySendResponseToCurrentApp:]_block_invoke
<img width="1280" alt="2018-04-05 16 39 15" src="https://user-images.githubusercontent.com/14836585/38355698-50ea92b0-38f0-11e8-979d-ca01f548f5d7.png">

**Comment by fremaksim** [comment]
解决了没？

**Comment by JosephPoplar** [comment]
同样问题

**Comment by ghjang** [comment]
I have an iOS app to maintain.

The app uses Weibo SDK to sign-in to Weibo. The app crashes with a similar screenshot to this issue when clicking some kind of cancel button on the left-top of the login page.

I'm not sure my problem is directly related to this issue. Anyway, do you have any idea what I am doing wrong?

![img_0168](https://user-images.githubusercontent.com/13075164/38656985-d9b92440-3e58-11e8-8616-560ef8aab6c1.png)

Following is a screenshot when the app is crashed:
![screen shot 2018-04-12 at 1 25 44 pm](https://user-images.githubusercontent.com/13075164/38656900-5f7516da-3e58-11e8-80ce-740bac5c9a70.png)

**Comment by AlvinZheng** [comment]
me too

**Comment by EricYellow** [comment]
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any?) -> Bool  

Xcode 9.3 中这个代理方法Any不是可选的了, sdk中传了nil

**Comment by EricYellow** [comment]
嗯，要么你等着他官方更新




| |
黄继平
邮箱：hjphfut@163.com
|

签名由 网易邮箱大师 定制

在2018年04月23日 10:56，AlvinZheng 写道：

看来只有自己解决了？

**Comment by AlvinZheng** [comment]
我另外加了个方法 func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any?) -> Bool    (Any改为Any?)后没有崩了。weibo会调到这个方法来。其他的还是调用原来的。

**Comment by JqyModi** [comment]
AlvinZheng：正解  通过他的方法成功解决了

**Comment by chenshipeng** [comment]
AlvinZheng：我也试试这个方法

**Comment by JeanKit** [comment]
OC有解决了的吗

**Comment by Running2snail** [comment]
OC怎么解决？

**Comment by mavivian** [comment]
> OC怎么解决？
我加了这个，没问题了，你试试
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return false;
}
