### ISSUE TITLE
 Failed to download 'Weibo_SDK'.

### ISSUE THREAD

**Issue by ymjmaster** [sinaweibosdk/weibo_ios_sdk#362]
[!] Error installing Weibo_SDK
[!] Failed to download 'Weibo_SDK'.

谁遇到过？？？

**Comment by kanluo91** [comment]
同求   怎么解决的？ 我都pod install  3次了 同样的问题

**Comment by jinjuezhou** [comment]
部分网络不行，打开全局代理也无用；
尝试 git config --global http.https://github.com.proxy socks5://127.0.0.1:1080
