### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x6853746573003ade)

### ISSUE THREAD

**Issue by initialj** [sinaweibosdk/weibo_ios_sdk#364]
使用3.2.1版本SDK，自己做了个微博分享的私有组件。在部分iPhone 6设备上，App启动时调取注册方法会crash。crash显示运行到[WBMFPRSA getPublicKey]的时候抛异常的。

**Comment by initialj** [comment]
一般崩溃的位置都在[WBMFPRSA getPublicKey] 、[WBMFPRSA encrypt:] 、[WBMFPRSA generateMFPString]。
具体原因和解决办法：
手动添加WeiBoSDK.bundle.
Target -> Build Phase -> Copy Bundle Resources
这样是能解决问题，但是我这个是私有库的形式啊，spec文件就是照着SDK里面的spec写的，很是郁闷。如果有知其所以然的同学，还希望求教育。

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。
