### ISSUE TITLE
3.2.1分享图片，分享完后图片会保存到系统相册，有没有办法解决

### ISSUE THREAD

**Issue by amovexu** [sinaweibosdk/weibo_ios_sdk#365]
3.2.1分享图片，分享完后图片会保存到系统相册，有没有办法解决？这个太影响用户体验了，我们深度使用的用户一天要分享好多次，结果系统相册里全是垃圾图片，这个非常影响体验的。

**Comment by vegbbk** [comment]
请问这个问题解决了吗
