### ISSUE TITLE
iOS11.4直接崩溃

### ISSUE THREAD

**Issue by semnyqu** [sinaweibosdk/weibo_ios_sdk#367]
Weibo_SDK (3.2.3)
iOS11.4
![0774dfde3fe347684fd7c4d7daa18a73](https://user-images.githubusercontent.com/14885293/41145549-0868a08e-6b33-11e8-89cf-6e2e3ab9f763.jpg)

**Comment by Fairtoys** [comment]
老哥改好了吗？我这也是会崩

**Comment by semnyqu** [comment]
@Fairtoys 
他们自己库有问题，又是封装的，要是开源出来早就给他改好了，WB SDK维护效率就是垃圾
