### ISSUE TITLE
奇葩的[WeiboSDK registerAppWithApp] Crash --- 内有调用栈

### ISSUE THREAD

**Issue by huakucha** [sinaweibosdk/weibo_ios_sdk#370]
![3a6cf27a-54b3-472e-b349-1d90dbfe016c](https://user-images.githubusercontent.com/5646613/43188626-25781740-9027-11e8-900d-e9a9b75d96a6.png)

**Comment by GWesley** [comment]
200多个issue 没人管，真垃圾

**Comment by wyt328412339** [comment]
兄弟，真机没这问题

**Comment by wb145230** [comment]
太垃圾了

**Comment by DongDongDongDong** [comment]
改好了吗

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中
