### ISSUE TITLE
3.1.4->3.2.3WBHttpRequest+WeiboUser是否还支持？

### ISSUE THREAD

**Issue by dudwchina** [sinaweibosdk/weibo_ios_sdk#375]
如题，微博[SDK3.1.4](https://github.com/sinaweibosdk/weibo_ios_sdk/tree/3.1.4/libWeiboSDK)中包括以下4个category，用于请求相关类别信息
[WBHttpRequest+WeiboGame.h](https://github.com/sinaweibosdk/weibo_ios_sdk/blob/3.1.4/libWeiboSDK/WBHttpRequest%2BWeiboGame.h),
[WBHttpRequest+WeiboShare.h](https://github.com/sinaweibosdk/weibo_ios_sdk/blob/3.1.4/libWeiboSDK/WBHttpRequest%2BWeiboShare.h),
[WBHttpRequest+WeiboToken.h](https://github.com/sinaweibosdk/weibo_ios_sdk/blob/3.1.4/libWeiboSDK/WBHttpRequest%2BWeiboToken.h)
[WBHttpRequest+WeiboUser.h](https://github.com/sinaweibosdk/weibo_ios_sdk/blob/3.1.4/libWeiboSDK/WBHttpRequest%2BWeiboUser.h)

在最新版本的[SDK3.2.3](https://github.com/sinaweibosdk/weibo_ios_sdk/tree/3.2.3/libWeiboSDK)中这4个文件已被移除。

以上信息在3.2.3中如何获取？

**Comment by sinaweibosdk** [comment]
您好，这些已经不支持了
