### ISSUE TITLE
注册一个应用，填写多个Bundle ID问题

### ISSUE THREAD

**Issue by huipengo** [sinaweibosdk/weibo_ios_sdk#376]
![image](https://user-images.githubusercontent.com/9402895/46255704-eb9e5a80-c4d2-11e8-85f4-0dbf01aec830.png)

你好，在开放平台注册一个应用，假设填写两个Bundle ID，当手机安装了这两个Bundle ID的APP时，点微博授权登录，跳回来的时候总是跳到先安装的APP，后安装的APP无法微博授权登录了！
这种情况怎么解决同时支持俩APP都可以微博授权登录？谢谢

**Comment by sinaweibosdk** [comment]
暂不支持
