### ISSUE TITLE
弹出新浪微博WebView登录窗口被遮挡问题

### ISSUE THREAD

**Issue by izhexi** [sinaweibosdk/weibo_ios_sdk#377]
看了下其他人提交的issue（编号#66），issues里提了个bug，使用keyWindow的rootViewController present的问题。
如果项目里，有个多个window，keyWindow不一定是最上层的window，使用keyWindow 的最上层viewController来present，登录窗口也是被遮挡的。
希望能把这个问题修复一下。

**Comment by bingri** [comment]
使用最新版本，仍有此问题！
不一定是多个window才有此问题。只要你的界面已经Present了一个新的窗口时调用微博的接口，就会有问题。
