### ISSUE TITLE
集成微博授权登录报错

### ISSUE THREAD

**Issue by shiios** [sinaweibosdk/weibo_ios_sdk#379]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PHAsset", referenced from:
      objc-class-ref in libWeiboSDK.a(WBImageObject.o)
      objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
  "_OBJC_CLASS_$_PHAssetChangeRequest", referenced from:
      objc-class-ref in libWeiboSDK.a(WBImageObject.o)
      objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
  "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
      objc-class-ref in libWeiboSDK.a(WBImageObject.o)
      objc-class-ref in libWeiboSDK.a(WBNewVideoObject.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sinaweibosdk** [comment]
为引入库
