### ISSUE TITLE
微博故事分享视频，微博发布页面黑屏

### ISSUE THREAD

**Issue by NNZ** [sinaweibosdk/weibo_ios_sdk#380]
你好，近期我们的线上版本遇到一个问题，app里面录制的视频通过微博故事分享，进入微博故事的发布页面显示黑色。依然点击发布后，发布后可以正常查看该视频。但由于发布页视频预览是黑色，分享的用户就不会继续分享了。

**Comment by onebutterflyW** [comment]
已解决

**Comment by sinaweibosdk** [comment]
已经解决
