### ISSUE TITLE
急！未安装微博客户端，iOS12.1.1 微博SDK 网页登录，点击登录无效或者报错

### ISSUE THREAD

**Issue by huipengo** [sinaweibosdk/weibo_ios_sdk#381]
当设备未安装微博APP时，微博授权登录，打开网页登录页面，输入账号密码（账号密码无误），点击登录按钮无反应（要多次点击），偶尔还会报错

![21544330967_ pic](https://user-images.githubusercontent.com/9402895/49693548-e46d8a00-fbb0-11e8-904b-248b84d49666.jpg)

**Comment by sinaweibosdk** [comment]
已解决
