### ISSUE TITLE
未安装App，网页登陆时崩溃，崩溃日志如下

### ISSUE THREAD

**Issue by zhangdongpo** [sinaweibosdk/weibo_ios_sdk#385]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIWebBrowserView selectionHighlightColor]: unrecognized selector sent to instance 0x10722aa00'
*** First throw call stack:
(0x1b45bcec4 0x1b378da40 0x1b44d5c24 0x1e14c0cd8 0x102ba595c 0x1b45c24d8 0x1b45c448c 0x1e17687b8 0x1e1768934 0x1e1765948 0x1e17658e4 0x1e198fb64 0x1b45c4630 0x1b44a2450 0x1b44a3034 0x1e1974ca0 0x1b45c24d8 0x1b45c448c 0x1e19772bc 0x1e1977158 0x10501cdc8 0x10502b9a0 0x10501cdc8 0x10502aa78 0x1b454cdf4 0x1b4547cbc 0x1b45471f0 0x1b67c0584 0x1e14934c0 0x100f3631c 0x1b4006bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by onebutterflyW** [comment]
SDK支持的最低版本为iOS8，iOS8以上系统，需要实现-application：openURL：sourceApplication：annotation方法
