### ISSUE TITLE
微博回调 Response 中的 requestUserInfo 没有包含原 request.userInfo 中的所有数据

### ISSUE THREAD

**Issue by langyanduan** [sinaweibosdk/weibo_ios_sdk#386]
WBAuthorizeRequest 中设置的了 userInfo， 对 `[UIApplication openURL:]` 打了符号断点，里面的 url 如下
```
weibosdk://request?id=xxxx&sdkversion=003233000&luicode=xxxxx&lfid=xxxx
```
并没有包含 userInfo 中设置的数据，同理回调中也没有包含自定义的 userInfo

SDK 版本号: 003233000

**Comment by onebutterflyW** [comment]
在代理方法中didReceuveWeiboResponse中可获得原请求数据
