### ISSUE TITLE
微博评论问题

### ISSUE THREAD

**Issue by liujunliuhong** [sinaweibosdk/weibo_ios_sdk#387]
你好，如何通过SDK评论某条指定微博？需要做到像分享那样，调起微博的评论面板，目前我在SDK里面只看到+ (void)commentToWeibo:(NSString *)mid;这个方法，但是我需要调起评论面板时，在输入框里面填充我们自己指定的内容

**Comment by sinaweibosdk** [comment]
暂时还不支持，目前评论，只能吊起微博的评论面板，有用户自己输入内容
