### ISSUE TITLE
Xcode 11 crash

### ISSUE THREAD

**Issue by leisurehuang** [sinaweibosdk/weibo_ios_sdk#390]
Xcode 11上，App编译运行后crash在websdk，麻烦定位下。

![image](https://user-images.githubusercontent.com/1477111/58926921-64029d00-877f-11e9-91ea-6cf515c13bba.png)

**Comment by zhengzheng** [comment]
遇到一样的问题，只在模拟器出现。请尽快解决。。

**Comment by iBCode** [comment]
Assertion Failed. 

Assertion failed: (NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]), function +[UIDevice(WBSDKHelpers) getUniqueStrByUUID], file /Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m, line 116.

麻烦尽快修复。

**Comment by caiwb** [comment]
麻烦尽快修复

**Comment by RunningChicken-K** [comment]
麻烦尽快修复

**Comment by 328712339** [comment]
同样的问题

**Comment by BoySimonHu** [comment]
和这个issue崩溃的状态一样，现在iOS 13上必现
https://github.com/sinaweibosdk/weibo_ios_sdk/issues/357

**Comment by sinaweibosdk** [comment]
已经修复
