### ISSUE TITLE
客户端未安装微博时，提示用户去下载微博客户端，点击确定后，去到的网页http://app.sina.cn/appdetail.php?appID=84560一片空片

### ISSUE THREAD

**Issue by lnking2013** [sinaweibosdk/weibo_ios_sdk#393]
/**
 返回一个 WBSendMessageToWeiboRequest 对象
 此方法生成对象被[WeiboSDK sendRequest:]会唤起微博客户端的发布器进行分享，如果未安装微博客户端或客户端版本太低
 会根据 shouldOpenWeiboAppInstallPageIfNotInstalled 属性判断是否弹出安装/更新微博的对话框
 @param message 需要发送给微博客户端的消息对象
 @return 返回一个*自动释放的*WBSendMessageToWeiboRequest对象
 */
+ (id)requestWithMessage:(WBMessageObject *)message;
调用此方法分享时，若用户未下载微博客户端时，用户提示下载客户端，点确定之后，sdk跳转的地址：http://app.sina.cn/appdetail.php?appID=84560 是无效的。

**Comment by sinaweibosdk** [comment]
已i修改，下期发版可测试
