### ISSUE TITLE
微博SDK在XCode11 beta5上会命中Assert Crash问题

### ISSUE THREAD

**Issue by game3108** [sinaweibosdk/weibo_ios_sdk#394]
Assertion failed: (NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]), function +[UIDevice(WBSDKHelpers) getUniqueStrByUUID], file /Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m, line 116.

在/UIDevice+WBSDKHelpers有一个断言，在XCode 11beta5上会命中，导致crash，这个有谁可以看一下吗？

**Comment by CuteBaber** [comment]
I got this error too.  Help!

**Comment by lixiangsanxun** [comment]
我也遇到了

**Comment by CuteBaber** [comment]
Owner在https://github.com/sinaweibosdk/weibo_ios_sdk/issues/390#issuecomment-512675542修复了，3.2.4。但是cocoapods上面没更新到3.2.4

**Comment by sinaweibosdk** [comment]
已更新3.2.5
