### ISSUE TITLE
openURL回调希望可以支持到最新

### ISSUE THREAD

**Issue by ZhangTonghai** [sinaweibosdk/weibo_ios_sdk#395]
application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation;
希望可以支持上面最新的回调方法，对支持9以上的系统比较友好

**Comment by Ekulelu** [comment]
+1

**Comment by ChenPingSheng** [comment]
如果工程只支持iOS9以上，AppDelegate里不实现上面这个方法会崩溃。SDK里应该做版本兼容。

**Comment by sinaweibosdk** [comment]
谢谢提醒，下版会更新，并在qq群里通知
