### ISSUE TITLE
iOS13兼容版本3.2.4在cocoapods上未更新

### ISSUE THREAD

**Issue by CuteBaber** [sinaweibosdk/weibo_ios_sdk#397]
@sinaweibosdk  hi，iOS13兼容版本v3.2.4在cocoapods上未更新，目前搜到的还是3.2.3。麻烦更新下cocoapods上的版本
![image](https://user-images.githubusercontent.com/50360644/63000404-a5ac7400-bea3-11e9-8b70-8e0e7d52fd3a.png)

**Comment by QiaoBangZhu** [comment]
我说呢 咋更新完了还不对呢

**Comment by tzqiang** [comment]
> @sinaweibosdk hi，iOS13兼容版本v3.2.4在cocoapods上未更新，目前搜到的还是3.2.3。麻烦更新下cocoapods上的版本
> ![image](https://user-images.githubusercontent.com/50360644/63000404-a5ac7400-bea3-11e9-8b70-8e0e7d52fd3a.png)


podspec文件中是tag：3.2.4，tags标签中是tag：v3.2.4，两者不匹配造成的问题
>![podspec](https://s2.ax1x.com/2019/09/10/nNYJzR.png)
>![tag](https://s2.ax1x.com/2019/09/10/nNtZkD.png)

**Comment by leonylcatwork** [comment]
真是服了微博的团队。。。 一个多月过去了也不修正一下？

**Comment by sinaweibosdk** [comment]
谢谢提示，已更新3.3.5版本
