### ISSUE TITLE
3.2.5 模拟器编译失败

### ISSUE THREAD

**Issue by sunyanyan** [sinaweibosdk/weibo_ios_sdk#401]
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      l052 in libWeiboSDK.a(WeiboSDK.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sinaweibosdk** [comment]
lipo -info libWeiboSDK.a,静态库是支持x86_64的

**Comment by sunyanyan** [comment]
看见支持 armv7 arm64 x86_64 了； 但是使用sdk自带的工程 WeiboSDKLibDemo ，也会提示 ___isPlatformVersionAtLeast 这个问题，辛苦看一下

**Comment by sinaweibosdk** [comment]
已经更新静态库
