### ISSUE TITLE
更新最新的SDK，直接报错了

### ISSUE THREAD

**Issue by melo30** [sinaweibosdk/weibo_ios_sdk#404]
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      l052 in libWeiboSDK.a(WeiboSDK.o)

**Comment by sinaweibosdk** [comment]
现在是一下是否还报错，

**Comment by melo30** [comment]
还是有这个问题呢

**Comment by bangjier** [comment]
> 现在是一下是否还报错，

还是会报错
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      l052 in libWeiboSDK.a(WeiboSDK.o)

**Comment by iPermanent** [comment]
报一样的错...没法用了

**Comment by melo30** [comment]
而且，为啥有的项目执行pod update 会把Weibo_SDK 更新到3.2.5， 而有的项目pod update 不会更新到3.2.5，还是3.2.3

**Comment by chatwyn** [comment]
报一样的错...没法用了

**Comment by sinaweibosdk** [comment]
请使用3.2.5.1

**Comment by melo30** [comment]
现在更新到最新，可以了
