### ISSUE TITLE
新版SDK不支持i386

### ISSUE THREAD

**Issue by sunyanyan** [sinaweibosdk/weibo_ios_sdk#405]
如题。 请问是基于什么原因没有加入i386架构呢？ 会给开发自测兼容带来很大不便

**Comment by iPermanent** [comment]
32位支持的别想了，浪费空间

**Comment by iPermanent** [comment]
收回我的话，这TM就是个坑啊，做组件化的必须依这个SDK，没有i386的版本,lint不过，必须得修改lint源码去掉这个，加大工作量

**Comment by lucktail** [comment]
遇到同样的问题，虽然可以绕过，但是毕竟不安全，还是希望增加i386

**Comment by sinaweibosdk** [comment]
好的，处于版本与微博的统计数据，将i386去除，下期会加上

**Comment by lucktail** [comment]
请问3.2.6版本支持i386了吗

**Comment by misakatao** [comment]
https://github.com/CocoaPods/CocoaPods/issues/9210
Add s.pod_target_xcconfig = { 'VALID_ARCHS' => 'armv7 arm64 x86_64' } to podspec.
