### ISSUE TITLE
最低版本支持变成iOS 9了么

### ISSUE THREAD

**Issue by zisulu** [sinaweibosdk/weibo_ios_sdk#406]
如果我自己fork，修改为8.0，会不会有影响？因为Xcode没更新前，想发个版本，但是这个版本还没放弃iOS 8

**Comment by zisulu** [comment]
我看了下，改成8.0有警告，我还是修改项目最低版本吧。

**Comment by felixbupt** [comment]
相同问题，还得继续支持iOS8，有人解决了吗？

**Comment by zisulu** [comment]
> 我看了下，改成8.0有警告。。

只能暂时不更新了。 https://github.com/sinaweibosdk/weibo_ios_sdk/issues/400
