### ISSUE TITLE
cocoapod 的版本还是3.2.3 此版本还未兼容ios13

### ISSUE THREAD

**Issue by puhahalx** [sinaweibosdk/weibo_ios_sdk#408]
ios13 weibo_sdk版本3.2.3 报错:
 Reachability Flag Status: -R ------- networkStatusForFlags
Assertion failed: (NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]), function +[UIDevice(WBSDKHelpers) getUniqueStrByUUID], file /Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m, line 116.

**Comment by LuoPengFei** [comment]
https://github.com/sinaweibosdk/weibo_ios_sdk/issues/394

**Comment by puhahalx** [comment]
![image](https://user-images.githubusercontent.com/28496967/65476237-d923ea80-deb4-11e9-9f27-f31e4e0940bb.png)
但是cocoapod 搜出来的最新版还是3.2.3 这样我只能手动导入库了

**Comment by LuoPengFei** [comment]
pod 'Weibo_SDK', '3.2.5'

**Comment by puhahalx** [comment]
![image](https://user-images.githubusercontent.com/28496967/65477798-fc9d6400-deb9-11e9-9695-964d8599b6fb.png)

**Comment by LuoPengFei** [comment]
![屏幕快照 2019-09-24 下午1 57 02](https://user-images.githubusercontent.com/10494635/65485036-434b8800-ded3-11e9-856b-660aabd0de98.png)

**Comment by puhahalx** [comment]
咦你到底是咋升级的 我pod repo刚更新到最新 搜出来的最新还是3.2.3 
![image](https://user-images.githubusercontent.com/28496967/65486674-a2ab9700-ded7-11e9-85cd-5a9db13252ae.png)

**Comment by puhahalx** [comment]
![image](https://user-images.githubusercontent.com/28496967/65497195-63d40c00-deec-11e9-96b7-2734f66fb72e.png)
![image](https://user-images.githubusercontent.com/28496967/65497205-69c9ed00-deec-11e9-8a83-6bf2caab8d84.png)
我哭了 还是搜不到3.2.5

**Comment by jiehailong** [comment]
> 更新下pod本地库，pod setup
> ![20190924143745](https://user-images.githubusercontent.com/12853558/65487188-e9e65780-ded8-11e9-95a6-217ad24a9655.jpg)

Weibo_SDK Minimum version only supports ios9，Modify your podfile file

**Comment by jiehailong** [comment]
> ![image](https://user-images.githubusercontent.com/28496967/65497195-63d40c00-deec-11e9-96b7-2734f66fb72e.png)
> ![image](https://user-images.githubusercontent.com/28496967/65497205-69c9ed00-deec-11e9-8a83-6bf2caab8d84.png)
> 我哭了 还是搜不到3.2.5

Weibo_SDK Minimum version only supports ios9，Modify your podfile file
