### ISSUE TITLE
最低版本只能支持到ios9了么？

### ISSUE THREAD

**Issue by zxfmpy** [sinaweibosdk/weibo_ios_sdk#410]
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Weibo_SDK":
  In Podfile:
    Weibo_SDK (~> 3.2.5.1)

Specs satisfying the `Weibo_SDK (~> 3.2.5.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by zxfmpy** [comment]
Pod::Spec.new do |s|
  s.name         = "Weibo_SDK"
  s.homepage     = "https://github.com/sinaweibosdk/weibo_ios_sdk"
  s.summary      = "WeiboSDK on iOS."
  s.description  = <<-DESC
                   New weibosdk pod.
                   DESC
  s.author       = { "meimei" => "meimei@staff.weibo.com" }
  s.version      = "3.2.5.1"
  s.source       = { :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git", :tag => "3.2.5.1" }
  s.platform     = :ios, '9.0'
  s.requires_arc = false
  s.license      = 'MIT'
  s.source_files = 'libWeiboSDK/*.{h,m}'
  s.resource     = 'libWeiboSDK/WeiboSDK.bundle'
  s.vendored_libraries  = 'libWeiboSDK/libWeiboSDK.a'
  s.frameworks   = 'Photos', 'ImageIO', 'SystemConfiguration', 'CoreText', 'QuartzCore', 'Security', 'UIKit', 'Foundation', 'CoreGraphics','CoreTelephony','WebKit'
  s.libraries = 'sqlite3', 'z'
end

果然是只支持ios9以上版本了啊，只能先不升级了，我还要支持ios8系统

**Comment by zisulu** [comment]
> Pod::Spec.new do |s|
> s.name = "Weibo_SDK"
> s.homepage = "https://github.com/sinaweibosdk/weibo_ios_sdk"
> s.summary = "WeiboSDK on iOS."
> s.description = <<-DESC
> New weibosdk pod.
> DESC
> s.author = { "meimei" => "[meimei@staff.weibo.com](mailto:meimei@staff.weibo.com)" }
> s.version = "3.2.5.1"
> s.source = { :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git", :tag => "3.2.5.1" }
> s.platform = :ios, '9.0'
> s.requires_arc = false
> s.license = 'MIT'
> s.source_files = 'libWeiboSDK/*.{h,m}'
> s.resource = 'libWeiboSDK/WeiboSDK.bundle'
> s.vendored_libraries = 'libWeiboSDK/libWeiboSDK.a'
> s.frameworks = 'Photos', 'ImageIO', 'SystemConfiguration', 'CoreText', 'QuartzCore', 'Security', 'UIKit', 'Foundation', 'CoreGraphics','CoreTelephony','WebKit'
> s.libraries = 'sqlite3', 'z'
> end
> 
> 果然是只支持ios9以上版本了啊，只能先不升级了，我还要支持ios8系统

我也是，没法儿升级，暂时丢不掉iOS 8

**Comment by sinaweibosdk** [comment]
是的，经过讨论和商议，以及看到系统版本的使用，支持iOS 9以上
