### ISSUE TITLE
iOS13 微博登录 didReceiveWeiboResponse代理没有走

### ISSUE THREAD

**Issue by wangxun0618** [sinaweibosdk/weibo_ios_sdk#413]

**Comment by appletesting2** [comment]
已碰到类似问题，SendRequest返回一直是NO，微博的同学们，看得到这个问题不？

**Comment by sariel89** [comment]
也碰到这个问题，不过我是有一半概率出现这个情况

**Comment by azureland** [comment]
这个问题有解决方案吗？ didReceiveWeiboResponse 一直没回调。

**Comment by sinaweibosdk** [comment]
实现application 打开url的相关delegate方法，在其中实现+ (BOOL)handleOpenURL:(NSURL *)url delegate:(id)delegate

**Comment by Superwang888** [comment]
@sinaweibosdk iOS13 分享，didReceiveWeiboResponse没有走，你的方案行不通，你用xcode11 新建个项目试试。
