### ISSUE TITLE
SDK内置的webview授权之后didReceiveWeiboResponse没有调用

### ISSUE THREAD

**Issue by YangXiaoYu123123** [sinaweibosdk/weibo_ios_sdk#417]
iOS 13.1 唤起内置的webview授权登录之后，微博没有调用didReceiveWeiboResponse

**Comment by rakeyang** [comment]
发现如果bundleid包含大写字母会出现sso失败的问题

**Comment by sinaweibosdk** [comment]
> iOS 13.1 唤起内置的webview授权登录之后，微博没有调用didReceiveWeiboResponse
实现application  打开url的相关delegate方法，在其中实现+ (BOOL)handleOpenURL:(NSURL *)url delegate:(id<WeiboSDKDelegate>)delegate
