### ISSUE TITLE
iOS13下编译模拟器报异常

### ISSUE THREAD

**Issue by DanielDanielDanielDaniel** [sinaweibosdk/weibo_ios_sdk#418]
+[UIDevice(WBSDKHelpers) getUniqueStrByUUID]:
    0x1050fd178 <+0>:   pushq  %rbp
    0x1050fd179 <+1>:   movq   %rsp, %rbp
    0x1050fd17c <+4>:   pushq  %r15
    0x1050fd17e <+6>:   pushq  %r14
    0x1050fd180 <+8>:   pushq  %r13
    0x1050fd182 <+10>:  pushq  %r12
    0x1050fd184 <+12>:  pushq  %rbx
    0x1050fd185 <+13>:  pushq  %rax
    0x1050fd186 <+14>:  leaq   0x1d37c93(%rip), %rdi     ; @"ASIdentifierManager"
    0x1050fd18d <+21>:  callq  0x10684795e               ; symbol stub for: NSClassFromString
    0x1050fd192 <+26>:  movq   %rax, %rbx
    0x1050fd195 <+29>:  testq  %rbx, %rbx
    0x1050fd198 <+32>:  je     0x1050fd2d2               ; <+346> at UIDevice+WBSDKHelpers.m:127:29
    0x1050fd19e <+38>:  movq   0x2334353(%rip), %r14     ; "class"
    0x1050fd1a5 <+45>:  movq   0x1c8f224(%rip), %r13     ; (void *)0x00007fff50b93780: objc_msgSend
    0x1050fd1ac <+52>:  movq   %rbx, %rdi
    0x1050fd1af <+55>:  movq   %r14, %rsi
    0x1050fd1b2 <+58>:  callq  *%r13
    0x1050fd1b5 <+61>:  movq   0x2335964(%rip), %rdx     ; "sharedManager"
    0x1050fd1bc <+68>:  movq   0x233435d(%rip), %rsi     ; "respondsToSelector:"
    0x1050fd1c3 <+75>:  movq   %rax, %rdi
    0x1050fd1c6 <+78>:  callq  *%r13
    0x1050fd1c9 <+81>:  testb  %al, %al
    0x1050fd1cb <+83>:  je     0x1050fd2d2               ; <+346> at UIDevice+WBSDKHelpers.m:127:29
    0x1050fd1d1 <+89>:  movq   %rbx, %rdi
    0x1050fd1d4 <+92>:  movq   %r14, %rsi
    0x1050fd1d7 <+95>:  callq  *%r13
    0x1050fd1da <+98>:  movq   0x2350d6f(%rip), %r12     ; "isAdvertisingTrackingEnabled"
    0x1050fd1e1 <+105>: movq   0x2335368(%rip), %rsi     ; "instancesRespondToSelector:"
    0x1050fd1e8 <+112>: movq   %rax, %rdi
    0x1050fd1eb <+115>: movq   %r12, %rdx
    0x1050fd1ee <+118>: callq  *%r13
    0x1050fd1f1 <+121>: testb  %al, %al
    0x1050fd1f3 <+123>: je     0x1050fd2d2               ; <+346> at UIDevice+WBSDKHelpers.m:127:29
    0x1050fd1f9 <+129>: movq   %rbx, %rdi

**Comment by yang152412** [comment]
我也碰到了，必现问题

**Comment by sinaweibosdk** [comment]
使用的是最新sdk吗？添加adSupport库了吗？

**Comment by DanielDanielDanielDaniel** [comment]
已经添加了的，adSupport.framework一直都存在。

**Comment by sinaweibosdk** [comment]
刚才试了一下，没有问题。添加这个群263989257

**Comment by sinaweibosdk** [comment]
是否使用最新版sdk
