### ISSUE TITLE
weibo ios sdk  在 ipad pro 12.9 3rd ios13.2.2中直接crash 了

### ISSUE THREAD

**Issue by westeast** [sinaweibosdk/weibo_ios_sdk#421]
在 ipad pro 12.9 3rd ios13.2.2中直接crash 了 crash在了引用weibo sdk的地方，其它版本ipad没有问题。

2019-12-04 00:44:24.649648+0800 chushe[90439:6944639] [Runtime][DEBUG:] JSWindow_closeSplashscreen
2019-12-04 00:44:28.222577+0800 chushe[90439:6944639] [LOG] : tap mine/index.html
2019-12-04 00:44:28.352560+0800 chushe[90439:6944799] -canOpenURL: failed for URL: "weixin://" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2019-12-04 00:44:28.362378+0800 chushe[90439:6944639] [Runtime][DEBUG:] show NWindow--[login/index.html]
2019-12-04 00:44:28.487442+0800 chushe[90439:6944639] Reachability Flag Status: -R ------- networkStatusForFlags
Assertion failed: (NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]), function +[UIDevice(WBSDKHelpers) getUniqueStrByUUID], file /Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m, line 116.
(lldb)

错误stack:

chushe`+[UIDevice(WBSDKHelpers) getUniqueStrByUUID]:
0x109cc6e6a <+0>: pushq %rbp
0x109cc6e6b <+1>: movq %rsp, %rbp
0x109cc6e6e <+4>: pushq %r15
0x109cc6e70 <+6>: pushq %r14
0x109cc6e72 <+8>: pushq %r13
0x109cc6e74 <+10>: pushq %r12
0x109cc6e76 <+12>: pushq %rbx
0x109cc6e77 <+13>: pushq %rax
0x109cc6e78 <+14>: leaq 0x9310d9(%rip), %rdi ; @"ASIdentifierManager"
0x109cc6e7f <+21>: callq 0x109f75a7c ; symbol stub for: NSClassFromString
0x109cc6e84 <+26>: movq %rax, %rbx
0x109cc6e87 <+29>: testq %rbx, %rbx
0x109cc6e8a <+32>: je 0x109cc6fc4 ; <+346> at UIDevice+WBSDKHelpers.m:127:29
0x109cc6e90 <+38>: movq 0xb2ea81(%rip), %r14 ; "class"
0x109cc6e97 <+45>: movq 0x8a3aaa(%rip), %r13 ; (void )0x00000001134ea780: objc_msgSend
0x109cc6e9e <+52>: movq %rbx, %rdi
0x109cc6ea1 <+55>: movq %r14, %rsi
0x109cc6ea4 <+58>: callq %r13
0x109cc6ea7 <+61>: movq 0xb2ffb2(%rip), %rdx ; "sharedManager"
0x109cc6eae <+68>: movq 0xb2e883(%rip), %rsi ; "respondsToSelector:"
0x109cc6eb5 <+75>: movq %rax, %rdi
0x109cc6eb8 <+78>: callq %r13
0x109cc6ebb <+81>: testb %al, %al
0x109cc6ebd <+83>: je 0x109cc6fc4 ; <+346> at UIDevice+WBSDKHelpers.m:127:29
0x109cc6ec3 <+89>: movq %rbx, %rdi
0x109cc6ec6 <+92>: movq %r14, %rsi
0x109cc6ec9 <+95>: callq %r13
0x109cc6ecc <+98>: movq 0xb48e9d(%rip), %r12 ; "isAdvertisingTrackingEnabled"
0x109cc6ed3 <+105>: movq 0xb34ee6(%rip), %rsi ; "instancesRespondToSelector:"
0x109cc6eda <+112>: movq %rax, %rdi
0x109cc6edd <+115>: movq %r12, %rdx
0x109cc6ee0 <+118>: callq %r13
0x109cc6ee3 <+121>: testb %al, %al
0x109cc6ee5 <+123>: je 0x109cc6fc4 ; <+346> at UIDevice+WBSDKHelpers.m:127:29
0x109cc6eeb <+129>: movq %rbx, %rdi
0x109cc6eee <+132>: movq %r14, %rsi
0x109cc6ef1 <+135>: callq %r13
0x109cc6ef4 <+138>: movq 0xb31845(%rip), %r15 ; "performSelector:"
0x109cc6efb <+145>: movq %rax, %rdi
0x109cc6efe <+148>: movq %r15, %rsi
0x109cc6f01 <+151>: movq 0xb2ff58(%rip), %rdx ; "sharedManager"
0x109cc6f08 <+158>: callq %r13
0x109cc6f0b <+161>: movq %rax, %rdi
0x109cc6f0e <+164>: movq %r15, %rsi
0x109cc6f11 <+167>: movq 0xb2ff48(%rip), %r15 ; "sharedManager"
0x109cc6f18 <+174>: movq %r12, %rdx
0x109cc6f1b <+177>: callq %r13
0x109cc6f1e <+180>: testq %rax, %rax
0x109cc6f21 <+183>: je 0x109cc6fc4 ; <+346> at UIDevice+WBSDKHelpers.m:127:29
0x109cc6f27 <+189>: movq %rbx, %rdi
0x109cc6f2a <+192>: movq %r14, %rsi
0x109cc6f2d <+195>: callq %r13
0x109cc6f30 <+198>: movq 0xb2ff31(%rip), %r12 ; "advertisingIdentifier"
0x109cc6f37 <+205>: movq %rax, %rdi
0x109cc6f3a <+208>: movq 0xb34e7f(%rip), %rsi ; "instancesRespondToSelector:"
0x109cc6f41 <+215>: movq %r12, %rdx
0x109cc6f44 <+218>: callq %r13
0x109cc6f47 <+221>: testb %al, %al
0x109cc6f49 <+223>: je 0x109cc6fc4 ; <+346> at UIDevice+WBSDKHelpers.m:127:29
0x109cc6f4b <+225>: movq %rbx, %rdi
0x109cc6f4e <+228>: movq %r14, %rsi
0x109cc6f51 <+231>: callq %r13
0x109cc6f54 <+234>: movq %rax, %rdi
0x109cc6f57 <+237>: movq 0xb317e2(%rip), %rbx ; "performSelector:"
0x109cc6f5e <+244>: movq %rbx, %rsi
0x109cc6f61 <+247>: movq %r15, %rdx
0x109cc6f64 <+250>: callq %r13
0x109cc6f67 <+253>: movq %rax, %rdi
0x109cc6f6a <+256>: movq %rbx, %rsi
0x109cc6f6d <+259>: movq %r12, %rdx
0x109cc6f70 <+262>: callq %r13
0x109cc6f73 <+265>: movq %rax, %rdi
0x109cc6f76 <+268>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc6f7b <+273>: movq %rax, %r14
0x109cc6f7e <+276>: movq 0xb2f113(%rip), %rsi ; "UUIDString"
0x109cc6f85 <+283>: movq %r14, %rdi
0x109cc6f88 <+286>: callq %r13
0x109cc6f8b <+289>: movq %rax, %rdi
0x109cc6f8e <+292>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc6f93 <+297>: movq %rax, %r15
0x109cc6f96 <+300>: movq 0xb2ec4b(%rip), %rsi ; "isEqualToString:"
0x109cc6f9d <+307>: leaq 0x944bb4(%rip), %rdx ; @"00000000-0000-0000-0000-000000000000"
0x109cc6fa4 <+314>: movq %r15, %rdi
0x109cc6fa7 <+317>: callq %r13
0x109cc6faa <+320>: testb %al, %al
0x109cc6fac <+322>: jne 0x109cc709a ; <+560> at UIDevice+WBSDKHelpers.m:116:25
0x109cc6fb2 <+328>: movq %r14, %rdi
0x109cc6fb5 <+331>: callq 0x8a399d(%rip) ; (void )0x0000000113504000: objc_release
0x109cc6fbb <+337>: testq %r15, %r15
0x109cc6fbe <+340>: jne 0x109cc7084 ; <+538> at UIDevice+WBSDKHelpers.m:140:1
0x109cc6fc4 <+346>: movq 0xb5399d(%rip), %rdi ; (void )0x00000001234d04b8: UIDevice
0x109cc6fcb <+353>: movq 0xb2f6fe(%rip), %rsi ; "currentDevice"
0x109cc6fd2 <+360>: movq 0x8a396f(%rip), %r13 ; (void )0x00000001134ea780: objc_msgSend
0x109cc6fd9 <+367>: callq %r13
0x109cc6fdc <+370>: movq %rax, %rdi
0x109cc6fdf <+373>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc6fe4 <+378>: movq %rax, %rbx
0x109cc6fe7 <+381>: movq 0xb2fc8a(%rip), %rsi ; "identifierForVendor"
0x109cc6fee <+388>: movq %rbx, %rdi
0x109cc6ff1 <+391>: callq %r13
0x109cc6ff4 <+394>: movq %rax, %rdi
0x109cc6ff7 <+397>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc6ffc <+402>: movq %rax, %r12
0x109cc6fff <+405>: movq %rbx, %rdi
0x109cc7002 <+408>: callq 0x8a3950(%rip) ; (void )0x0000000113504000: objc_release
0x109cc7008 <+414>: testq %r12, %r12
0x109cc700b <+417>: je 0x109cc703b ; <+465> at UIDevice+WBSDKHelpers.m:130:5
0x109cc700d <+419>: movq 0xb2f084(%rip), %r14 ; "UUIDString"
0x109cc7014 <+426>: movq %r12, %rdi
0x109cc7017 <+429>: movq %r14, %rsi
0x109cc701a <+432>: callq 0x8a3928(%rip) ; (void )0x00000001134ea780: objc_msgSend
0x109cc7020 <+438>: movq %rax, %rdi
0x109cc7023 <+441>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc7028 <+446>: movq %rax, %r15
0x109cc702b <+449>: movq %r12, %rdi
0x109cc702e <+452>: callq 0x8a3924(%rip) ; (void )0x0000000113504000: objc_release
0x109cc7034 <+458>: testq %r15, %r15
0x109cc7037 <+461>: jne 0x109cc7084 ; <+538> at UIDevice+WBSDKHelpers.m:140:1
0x109cc7039 <+463>: jmp 0x109cc704b ; <+481> at UIDevice+WBSDKHelpers.m:135:24
0x109cc703b <+465>: movq %r12, %rdi
0x109cc703e <+468>: callq 0x8a3914(%rip) ; (void )0x0000000113504000: objc_release
0x109cc7044 <+474>: movq 0xb2f04d(%rip), %r14 ; "UUIDString"
0x109cc704b <+481>: movq 0xb5385e(%rip), %rdi ; (void )0x000000010dda8f48: NSUUID
0x109cc7052 <+488>: movq 0xb2f037(%rip), %rsi ; "UUID"
0x109cc7059 <+495>: callq %r13
0x109cc705c <+498>: movq %rax, %rdi
0x109cc705f <+501>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc7064 <+506>: movq %rax, %rbx
0x109cc7067 <+509>: movq %rbx, %rdi
0x109cc706a <+512>: movq %r14, %rsi
0x109cc706d <+515>: callq %r13
0x109cc7070 <+518>: movq %rax, %rdi
0x109cc7073 <+521>: callq 0x109f770c6 ; symbol stub for: objc_retainAutoreleasedReturnValue
0x109cc7078 <+526>: movq %rax, %r15
0x109cc707b <+529>: movq %rbx, %rdi
0x109cc707e <+532>: callq 0x8a38d4(%rip) ; (void )0x0000000113504000: objc_release
0x109cc7084 <+538>: movq %r15, %rdi
0x109cc7087 <+541>: addq $0x8, %rsp
0x109cc708b <+545>: popq %rbx
0x109cc708c <+546>: popq %r12
0x109cc708e <+548>: popq %r13
0x109cc7090 <+550>: popq %r14
0x109cc7092 <+552>: popq %r15
0x109cc7094 <+554>: popq %rbp
0x109cc7095 <+555>: jmp 0x109f7700c ; symbol stub for: objc_autoreleaseReturnValue
0x109cc709a <+560>: leaq 0x706f0c(%rip), %rdi ; "+[UIDevice(WBSDKHelpers) getUniqueStrByUUID]"
0x109cc70a1 <+567>: leaq 0x706f32(%rip), %rsi ; "/Users/insomnia/Desktop/git_Weibo_sdk/WeiboSDKSrc/WeiboSDK/UIDevice+WBSDKHelpers.m"
0x109cc70a8 <+574>: leaq 0x706f7e(%rip), %rcx ; "NO == [udid_string isEqualToString:@"00000000-0000-0000-0000-000000000000"]"
0x109cc70af <+581>: movl $0x74, %edx
0x109cc70b4 <+586>: callq 0x109f76778 ; symbol stub for: __assert_rtn

**Comment by sinaweibosdk** [comment]
您用的是最新的sdk吗？

**Comment by westeast** [comment]
> 您用的是最新的sdk吗？

应该不是最新的，好久没更新了，最新的已经修复这个总是了是吗？

**Comment by sinaweibosdk** [comment]
是的，新版本已修复
