### ISSUE TITLE
麻烦修改下这2个方法的命名，消除警告

### ISSUE THREAD

**Issue by iOSCountry** [sinaweibosdk/weibo_ios_sdk#423]
instance method 'wbsdk_stringByReplacingRange:with:' in category from /Volumes/Code/ios_jihai/jihai/Resource/SDK/WeiboSDK/libWeiboSDK.a(WBSDKComposerWebViewController.o) conflicts with same method from another category

instance method 'wbsdk_stringByReplacingRange:with:' in category from /Volumes/Code/ios_jihai/jihai/Resource/SDK/WeiboSDK/libWeiboSDK.a(WBSDKAuthorizeWebViewController.o) conflicts with same method from another category

**Comment by sinaweibosdk** [comment]
3.2.6版本已修改
