### ISSUE TITLE
Make WeiboSDK compatible for an Cocoa Touch Framework.

### ISSUE THREAD

**Issue by wplong11** [sinaweibosdk/weibo_ios_sdk#425]
Currently WeiboSDK cannot be built as Cocoa Touch Framework and imported as module into a Swift Xcode Project.

This would have the advantage, that developers who are only familiar with Swift and not with Objective-C can see the header in the automatically generated Swift syntax.

If you try to build WeiboSDK as Cocoa Touch Framework and import it as module in a Swift Xcode Project, you get compiler errors that can easily be fixed:

```
Include of non-modular header inside framework module 'MyCoreFramework': '/Pods/Headers/Public/WeiboSDK/WeiboSDK.h'

Include of non-modular header inside framework module 'MyCoreFramework': '/Pods/Headers/Public/WeiboSDK/WeiboUser.h'
```

The problem is that WeiboSDK.h and WeiboUser.h imports some headers.

Please check a related issue:
- https://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module
- https://github.com/AFNetworking/AFNetworking/issues/2205

**Comment by sinaweibosdk** [comment]
最新版本已去除WeiboUser.h文件，可以参考相关issue
