### ISSUE TITLE
Same method warning

### ISSUE THREAD

**Issue by honeyeeb** [sinaweibosdk/weibo_ios_sdk#427]
ld: warning: instance method 'wbsdk_stringByReplacingRange:with:' in category from /Pods/Weibo_SDK/libWeiboSDK/libWeiboSDK.a(WBSDKComposerWebViewController.o) conflicts with same method from another category
ld: warning: instance method 'wbsdk_stringByReplacingRange:with:' in category from Pods/Weibo_SDK/libWeiboSDK/libWeiboSDK.a(WBSDKAuthorizeWebViewController.o) conflicts with same method from another category

**Comment by sinaweibosdk** [comment]
最新版sdk已经消除该警告
