### ISSUE TITLE
WBHttpRequest 不再支持 refresh token 了？

### ISSUE THREAD

**Issue by an0** [sinaweibosdk/weibo_ios_sdk#428]
3.2.0版本更新里说：
「SDK不再包装访问openAPI的接口，SDK对外提供的网络访问工具WBHttpRequest也将逐步下线，开发者微博后期使用微博openAPI接口时，需要使用自己网络模块并按照平台的接口文档进行调用。」

我发现 3.2.6 里的 WBHttpRequest 不再支持 requestForRenewAccessTokenWithRefreshToken。那现在的问题是，如何用 openAPI 刷新 token？微博开放平台文档里没有相关内容。

**Comment by sinaweibosdk** [comment]
是的，不在支持
