### ISSUE TITLE
微博sdk版本号：003233010，如果没有微博客户端，分享不会成功。

### ISSUE THREAD

**Issue by changpk** [sinaweibosdk/weibo_ios_sdk#429]
以前的sdk，如果手机没有微博客户端则分享会在app内部模态弹出微博的登录和分享页面，进行登录和分享；
替换为最新的sdk之后，版本显示为003233010，则在微博客户端没有安装的场景下，无法分享；

**Comment by sinaweibosdk** [comment]
您好，新版sdk保留网页分享功能，未安装的情况下可以使用网页分享
