### ISSUE TITLE
libWeiboSDK.a 使用了UIAlertView， 请问在 iOS13 UIScene下会不会有问题？

### ISSUE THREAD

**Issue by ssssuperMan** [sinaweibosdk/weibo_ios_sdk#433]
使用strings命令发现 libWeiboSDK.a 有使用 UIAlertView，请问在iOS 13 UIScene下使用会出现问题吗？

strings libWeiboSDK/libWeiboSDK.a | grep "UIAlertView"

__OBJC_LABEL_PROTOCOL_$_UIAlertViewDelegate
__OBJC_PROTOCOL_$_UIAlertViewDelegate
UIAlertViewDelegate
v32@0:8@"UIAlertView"16q24
v24@0:8@"UIAlertView"16
B24@0:8@"UIAlertView"16

**Comment by sinaweibosdk** [comment]
您好3.2.7版本已经修复了
