### ISSUE TITLE
请问微博sdk支持iOS 8.0吗

### ISSUE THREAD

**Issue by oahgnehzoul** [sinaweibosdk/weibo_ios_sdk#435]
现在podsepc上的最低支持版本是9.0，在8.0上会不会有问题

**Comment by TMTBO** [comment]
ios 8 pod install 运行不起来呀

**Comment by oahgnehzoul** [comment]
> ios 8 pod install 运行不起来呀

可以改下 Podfile ,install之后再改成 8

**Comment by sinaweibosdk** [comment]
不支持iOS8
