### ISSUE TITLE
请求适配 iOS 14 的 v3.3.0 版本的接入文档链接

### ISSUE THREAD

**Issue by Navimark** [sinaweibosdk/weibo_ios_sdk#459]
如题。

在 https://open.weibo.com/wiki/Sdk/ios 上找了一大圈，没有找到相关链接。

**希望能够有一份文档指导如何接入、注意事项、Universal Link 配置/测试要点。**

**Comment by Navimark** [comment]
看到了一个 PDF 文档： https://github.com/sinaweibosdk/weibo_ios_sdk/blob/master/%E5%BE%AE%E5%8D%9AiOS%E5%B9%B3%E5%8F%B0SDK%E6%96%87%E6%A1%A3V3.3.0.pdf

**Comment by caicai0525** [comment]
请问能发一下PDF文档吗，现在的链接打不开了

**Comment by Navimark** [comment]
> 请问能发一下PDF文档吗，现在的链接打不开了

刚刚检查了一下，链接有效可下载

**Comment by caicai0525** [comment]
那可能是我网络的问题，请问你的universal link是怎么配置的，跟微信的一样就行吗
