### ISSUE TITLE
点击微博发布器的关闭按钮会把我们自己弹出来的ModalViewController也一并给dismiss掉

### ISSUE THREAD

**Issue by boyang-chris** [sinaweibosdk/weibo_ios_sdk#47]
比如我自己弹出个ModalViewController，在这个视图里面再弹出SDK内置的发布器，点击关闭按钮会把我自己的ModalViewController也dismiss掉，建议加个可以设置类似RootViewController的属性，利用这个Controller弹出发布器，没设置才使用默认的。
希望这个问题能够尽快得到解决。

**Comment by dannion** [comment]
谢谢您的反馈，该问题会在3.1.0版本中修复。
