### ISSUE TITLE
静态库文件不支持armv7s

### ISSUE THREAD

**Issue by muer2000** [sinaweibosdk/weibo_ios_sdk#48]
只支持armv7 arm64 i386 x86_64

**Comment by dannion** [comment]
目前提交商店审核的应用也都需要支持64位架构。arm64+armv7是官方推荐的架构组合。若仍需要支持armv7s架构的SDK，请邮件告知原由，WeiboSDK会根据情况给你单独打一个含armv7s的SDK包。
