### ISSUE TITLE
在Xcode6.1创建的项目中， 直接崩溃

### ISSUE THREAD

**Issue by huangwangxin** [sinaweibosdk/weibo_ios_sdk#50]
在Xcode6.1创建的项目中，一运行[WeiboSDK registerApp:kAppKey]; 这一步直接崩溃

**Comment by leenjewel** [comment]
我做了比较详细的分析，希望能帮你解决问题：

http://leenjewel.github.io/blog/2015/01/08/ios-ping-tai-cocos2d-x-xiang-mu-jie-ru-xin-lang-wei-bo-sdk-de-keng/
