### ISSUE TITLE
3.3.4 没有推到 CocoaPods

### ISSUE THREAD

**Issue by zisulu** [sinaweibosdk/weibo_ios_sdk#507]
麻烦尽快推到 CocoaPods，现在搜不到 @sinaweibosdk

**Comment by chunxige** [comment]
已经反馈了多久了，到现在还不推，也不知道为什么

**Comment by zisulu** [comment]
> 

我也不懂，看昨天更新的，podspec只改了版本，没改tag，也是醉了。。

**Comment by zisulu** [comment]
> 
我也不懂，看昨天更新的，podspec只改了版本，没改tag，也是醉了。。@chunxige

**Comment by zisulu** [comment]
> @zisulu 由于权限问题，目前还没法发布到cocoapods，正在解决这个问题，请耐心等待，可以直接下载放到项目中哦
好的明白了，谢谢

**Comment by sinaweibosdk** [comment]
@zisulu 已经提到cocoapods了，3.3.5，需要的话可以更新了

**Comment by zisulu** [comment]
> @zisulu 已经提到cocoapods了，3.3.5，需要的话可以更新了

好的，我去看下

**Comment by zisulu** [comment]
> @zisulu 已经提到cocoapods了，3.3.5，需要的话可以更新了

可是podspec里面的tag还没改哎，麻烦再看看呢
![image](https://user-images.githubusercontent.com/15645270/197926986-b72850ac-cb85-4a38-a217-1db979debac7.png)

**Comment by sinaweibosdk** [comment]
> > @zisulu 已经提到cocoapods了，3.3.5，需要的话可以更新了
> 
> 可是podspec里面的tag还没改哎，麻烦再看看呢 ![image](https://user-images.githubusercontent.com/15645270/197926986-b72850ac-cb85-4a38-a217-1db979debac7.png)

这个没有影响的，已经更正了

**Comment by sinaweibosdk** [comment]
> 已经反馈了多久了，到现在还不推，也不知道为什么

3.3.5已经同步到cocoapods
