### ISSUE TITLE
3.3.0之后的版本编译报错

### ISSUE THREAD

**Issue by xygkevin** [sinaweibosdk/weibo_ios_sdk#508]
error build: Undefined symbol: _OBJC_CLASS_$_WBAuthorizeRequest

**Comment by sinaweibosdk** [comment]
@xygkevin demo可以编译通过吗？

**Comment by xygkevin** [comment]
demo是可以正常编译的

我的报错环境是
iMac M1

**Comment by xygkevin** [comment]
xcode14.01
ios16.1

**Comment by xygkevin** [comment]
真机
iphone13promax

**Comment by xygkevin** [comment]
使用cocoapods导入，3.3.0编译正常，之后的版本就报错
<img width="532" alt="image" src="https://user-images.githubusercontent.com/19592642/198501718-f0ba83e9-a76b-45f1-a96d-9c4b9deb3ec5.png">

**Comment by xygkevin** [comment]
> @xygkevin demo可以编译通过吗？

以上

**Comment by xygkevin** [comment]
这个问题发现是在导入广告 Ads-CN 库之后出现的，单独导入pod 'Weibo_SDK' 3.3.5版本是没有问题的，不知道是不是有啥冲突

**Comment by sinaweibosdk** [comment]
> 这个问题发现是在导入广告 Ads-CN 库之后出现的，单独导入pod 'Weibo_SDK' 3.3.5版本是没有问题的，不知道是不是有啥冲突

这个不太清楚，看一下buildsetting linking那是不是有weibo_SDK对应的路径

**Comment by xygkevin** [comment]
> > 这个问题发现是在导入广告 Ads-CN 库之后出现的，单独导入pod 'Weibo_SDK' 3.3.5版本是没有问题的，不知道是不是有啥冲突
> 
> 
> 
> 这个不太清楚，看一下buildsetting linking那是不是有weibo_SDK对应的路径

手动导入的，没问题啦

**Comment by XiaoXiuXiuYe** [comment]
xcode14.01
ios15.4我也是报上面这个

**Comment by XiaoXiuXiuYe** [comment]
同样的编译环境，新建一个工程，使用pod，就会编译出错，手动导入就不会报错，希望能够解决这个问题！！！
