### ISSUE TITLE
Swift中调用SDK，抛出异常 'NSInvalidArgumentException', reason: '-[__NSDictionaryM weibosdk_WBSDKJSONString]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by mebusw** [sinaweibosdk/weibo_ios_sdk#51]
XCode6.1   Swift项目
WeiboSDK 2.4.2

在AppDelegate中一运行 [WeiboSDK registerApp:kAppKey]; 这一步直接抛出异常：

'NSInvalidArgumentException', reason: '-[__NSDictionaryM weibosdk_WBSDKJSONString]: unrecognized selector sent to instance

尝试加过linking flag：`-Objc`或`-all_load`，都没用，

**Comment by leenjewel** [comment]
大家说的解决办法都比较片面，我做了比较详细的分析：

http://leenjewel.github.io/blog/2015/01/08/ios-ping-tai-cocos2d-x-xiang-mu-jie-ru-xin-lang-wei-bo-sdk-de-keng/
