### ISSUE TITLE
在keyWindow的rootVC上通过presentViewController跳转的视图中，调用授权接口提示Warning: Attempt to present <UINavigationController

### ISSUE THREAD

**Issue by lwsitachi** [sinaweibosdk/weibo_ios_sdk#52]
错误场景：
A（视图控制器）通过presentViewController跳转到了B（视图控制器）中，然后在B的按钮事件中调用了授权接口。无法实现跳转，并且出现的错误提示如下：

Warning: Attempt to present <UINavigationController: 0xa8ad560> on <ViewController: 0xa53afb0> whose view is not in the window hierarchy!

自己猜测原因大概是微博的sdk中，先通过keyWindow的rootVC的继承关系获得“根视图”。再通过presentViewController跳转到授权页面。
大概是类似这样吧：
[[SomeInstance getRootViewController] presentViewController:authorVC animated:YES completion:nil];

请相关技术人员帮忙看下：
这边的获取跳转到授权页面的源视图的方法即getRootViewController，是否应该做相应的修改。
或者说，如果我已经通过presentViewController跳转到了自己的某个视图控制器中，如何在这个控制器中调用授权接口吧。

**Comment by joshuafeldman** [comment]
I am experiencing this issue as well. It seems like if a modal is presenting authorization does not work

**Comment by Mfk759853063** [comment]
我也遇到了从a present 到b，在b 调用授权接口，也是出现这个错误

**Comment by haitaoli** [comment]
Same issue here. Version 2.5.1 works fine. The fix will look like this:

UIViewController * topViewController = window.rootViewController;

while (topViewController.presentingViewController)
    topViewController = topViewController.presentingViewController;

**Comment by keeploading** [comment]
3.0.1版本里还有这个问题，能否赶紧解决这个问题，等着release。

**Comment by dannion** [comment]
谢谢反馈，这个问题会在3.1.0版本中修复。3.1.0版本应该在3月份上旬前后发布。

**Comment by chenlin8** [comment]
3.1.0何时发啊。我们也碰到同样的问题了。等着发布呢。谢谢。

**Comment by joshuafeldman** [comment]
Any update on when this will be fixed?

**Comment by doggy** [comment]
Have you guys forget to release new version in early march?

**Comment by joshuafeldman** [comment]
Would love to see a fix for this since currently I am using method swizzling to fix the issue myself

**Comment by doggy** [comment]
@joshuafeldman  Which function name did you swizzling on?

**Comment by joshuafeldman** [comment]
I made a category on `UIViewController` and swizzled the presentation method. My code is below although some of the methods are categories I have made on other classes but you get the idea. It isn't my favorite solution and hopefully it will be fixed so I can remove it.

```@implementation UIViewController (FGSinaWeiboPresenterFix)

#pragma mark - NSObject Class Methods

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        /* strongify:ignore */
        [self swizzleInstanceMethod:@selector(presentViewController:animated:completion:)
                           toMethod:@selector(_weibo_fix_presentViewController:animated:completion:)];
    });
}

#pragma mark - Private Methods

- (void)_weibo_fix_presentViewController:(UIViewController *)viewControllerToPresent
                                animated:(BOOL)flag
                              completion:(void (^)(void))completion
{
    // determine if the class name prefix is for the weibo SDK and be safe to make sure the length
    NSString * weiboSDKPrefix = @"WBSDK";
    NSString * className = [self classNameFromViewControllerToPresent:viewControllerToPresent];
    if ( className.length >= weiboSDKPrefix.length ) {
        NSString * prefix = [[className substringWithRange:NSMakeRange(0, weiboSDKPrefix.length)] uppercaseString];
        if ( [prefix isEqualToString:weiboSDKPrefix] ) {
            [[UIViewController topViewController] _weibo_fix_presentViewController:viewControllerToPresent
                                                                          animated:flag
                                                                        completion:completion];
            return;
        }
    }
    
    // call the original method
    [self _weibo_fix_presentViewController:viewControllerToPresent animated:flag completion:completion];
}

- (NSString *)classNameFromViewControllerToPresent:(UIViewController *)viewController
{
    if ( [viewController isKindOfClass:[UINavigationController class]] ) {
        return [self classNameFromViewControllerToPresent:((UINavigationController *)viewController).topViewController];
    }
    return NSStringFromClass([viewController class]);
}```

**Comment by doggy** [comment]
Most appreciate @joshuafeldman

**Comment by manymingge** [comment]
still not updated?

**Comment by phnessu4** [comment]
微博果然还是黄了～

**Comment by SeanChense** [comment]
same with @joshuafeldman .

Presented to a, then use sdk to request token but failed.

**Comment by SeanChense** [comment]
@sinaweibosdk This issue should close.

**Comment by wujianbotju** [comment]
作为一个前微博员工，感到丢脸，为什么这个bug到现在都还没有修复，我去...
