### ISSUE TITLE
3.0.1无法使用

### ISSUE THREAD

**Issue by nypisces** [sinaweibosdk/weibo_ios_sdk#53]
从2.4.2直接升上来，报错
感觉是mfp.cer的问题

**Comment by dismory** [comment]
FYI，可以暂时修改 Podfile 这样凑合一下。
`pod 'WeiboSDK', :git => "git@github.com:sinaweibosdk/weibo_ios_sdk.git"`

**Comment by dannion** [comment]
关闭。
