### ISSUE TITLE
[__NSDictionaryM weibosdk_WBSDKJSONString]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by topcpper** [sinaweibosdk/weibo_ios_sdk#56]
调用微博api会出现如上问题，定位问题出自于：
[WeiboSDK registerApp: app_key]
断点进入后问题出自于：[WBMFPRSA getPublicKey ]
连接选项中 已经开启了-ObjC

关键第一次调用会出现此问题，第二次调用就不出现了，请排查问题，谢谢

**Comment by dannion** [comment]
Bundle文件路径错误导致，请参照Demo程序设置Bundle。

**Comment by Whirlwind** [comment]
我也存在相同问题，采用 Pod 引入3.0.1版本，检查了 App 包，weibo.bundle 在程序包的根目录。

**Comment by Whirlwind** [comment]
发现好像是 Cocoapods 0.36.0 的问题。

**Comment by aelam** [comment]
所以问题是如何解决的？

**Comment by Whirlwind** [comment]
不要用 CocoaPods 官方的 spec 文件，用 weibo 项目中的那个 spec 文件。
```
pod 'WeiboSDK', :git=>'微博 SDK 仓库地址'
```

**Comment by Limon-catch** [comment]
`pod 'WeiboSDK', :podspec => 'https://raw.github.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'`

**Comment by Augus007** [comment]
解决方案：
Build Settings -> Search Paths -> Library Search Paths 路径设置为 libWeiboSDK 文件夹目录路径

**Comment by aelam** [comment]
问题没有解决就关了？
