### ISSUE TITLE
授权webview弹窗后立即消失

### ISSUE THREAD

**Issue by robotbear2077** [sinaweibosdk/weibo_ios_sdk#6]
从[以前的版本](https://raw.github.com/mobileresearch/weibo_ios_sdk_sso-oauth/b24060e4caa5596a585462525a526f36f63dcd96/sinaweibo_ios_sdk&demo/sinaweibo_ios_sdk/SinaWeibo/SinaWeiboAuthorizeView.m)中看到webview是通过加到UIWindow上实现的,而UIWindow是这样获得的:

```
UIWindow* window = [UIApplication sharedApplication].keyWindow; 
```

我的应用中是先弹出系统actionsheet(ios7)后让用户选择分享平台, 调试时发现这时候通过这样的方式获得的window为_UIAlertOverlayWindow类型
**怀疑**现在的sdk也是这样实现的,导致我的应用中授权webview无法显示,然后在我在请求授权之前加了这句代码:

```
[[[[UIApplication sharedApplication] delegate] window] makeKeyWindow];
```

结果webview能正常显示了......

**Comment by yaoyaozhang** [comment]
我使用3.1.1的验证码登录，点击“获取验证码”直接弹出“错误”的alert

**Comment by sheaxu** [comment]
Bundle ID填写是正确的，但是仍旧存在这个问题

**Comment by edwardean** [comment]
我现在存在和@sheaxu一样的问题，手机上没安装微博客户端时，授权页面弹出后授权后无反应，跳转的微博客户端授权后也没有任何反应，我的bundleID是正确的，请问这个是怎么回事？

**Comment by Clear2** [comment]
我的bundle ID 填写是正确的，plist添加		<string>sinaweibosso</string>，调起新浪客户端时，提示package or sign error

**Comment by xylinuxkernel** [comment]
sso授权登陆，无客户端网页登陆成功后没有logout为什么每次点击授权都要重新来一遍 ，安装了客户端则不会这样 ，这是为什么，因为这个问题已经被苹果拒绝了

**Comment by huangwendong1988** [comment]
1、看看info.plist文件里有没添加加url types，在url schems里填上wb+APPKEY，如：wb8728171
2、微博平台上设置的bundle id 是否与你的应用一致

**Comment by wlflovesj** [comment]
客户端分享成功然后返回的时候崩溃了

**Comment by getgetsetset1** [comment]
ios swift, 我用github上最新的SDK进行认证，如果没有安装客户端的话无法弹出网页进行认证，why?, 如果安装了客户端就可以, 3Q
