### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Vincent-z** [sinaweibosdk/weibo_ios_sdk#64]
通过 cocoapod 安装完编译直接报错：Undefined symbols for architecture x86_64，还需要设置什么吗？

**Comment by dannion** [comment]
麻烦提供进一步信息以帮助排查，目前看起来是由于你使用的是老版本不支持64位的sdk导致，请尝试集成3.0.1版本SDK

**Comment by ithinco** [comment]
同样的问题（3.0，xcode 6.1.1，最低支持8.0），加入SystemConfiguration和ImageIO两个框架就没报错了，太坑了，pdf里没更新

**Comment by Vincent-z** [comment]
![screen shot 2015-02-25 at 14 56 59](https://cloud.githubusercontent.com/assets/9880993/6366303/a18b898e-bcfe-11e4-8a81-7c0e5bfcfc48.jpg)

添加了框架还是报错。。

**Comment by Vincent-z** [comment]
谢谢，这回编译成功了
