### ISSUE TITLE
Cocoapods方式引入3.0.1调用注册方法crash

### ISSUE THREAD

**Issue by zsk425** [sinaweibosdk/weibo_ios_sdk#65]
调用[WeiboSDK registerApp:kWeiboAppKey]会出现EXC_BAD_ACCESS，请核实

**Comment by zsk425** [comment]
重新试过之后又正常了

**Comment by zsk425** [comment]
又出现了，看来不是特例

**Comment by zsk425** [comment]
补充：使用cocoapods本地引入的方式就不会出现

**Comment by yirenjun** [comment]
其实这个问题是已经解决了的 只是podspec没有更新到中央库
你直接将pod指向到本repo吧

**Comment by zsk425** [comment]
@yirenjun 我目前确实用的是本地引入。

另一个问题：
现在我想分享分享音乐到微博：
    WBMusicObject *musicObj = [WBMusicObject object];
            musicObj.objectID = @"identifier1";
            musicObj.title = @"title";
            musicObj.description = @"some desc";
            musicObj.thumbnailData = UIImageJPEGRepresentation(cover, 0.2);
            musicObj.musicUrl = webLink;
            musicObj.musicStreamUrl = audioURL;
            
            WBMessageObject *msg = [WBMessageObject message];
            msg.mediaObject = musicObj;
            
            WBSendMessageToWeiboRequest *request = [WBSendMessageToWeiboRequest requestWithMessage:msg];
            [WeiboSDK sendRequest:request];

我分享出去的仅仅是一个连接，而不是那种播放器效果？
申请加群，两天都没有反应。

**Comment by kvting** [comment]
+1

`pod 'WeiboSDK', '~> 3.0.1'`

**Comment by wanyakun** [comment]
+1

pod 'WeiboSDK', '~> 3.0.1'

**Comment by xuty** [comment]
我也遇到了该问题，我的原因是忘了添加WeiboSDK.bundle

**Comment by wanyakun** [comment]
管理员不维护吗？对新的podspec做次pod trunk push吧
