### ISSUE TITLE
无法弹出新浪微博WebView登录窗口

### ISSUE THREAD

**Issue by yirenjun** [sinaweibosdk/weibo_ios_sdk#66]
我也是醉了~

![image](https://cloud.githubusercontent.com/assets/273997/5900234/dafc51ae-a5a1-11e4-9048-7d6609f07162.png)

没装新浪客户端，想着会弹出个WebView登录界面吧.. 
竟然在WeiboSDK的sendRequest:里面弹，好吧~
你妹的，直接拿keyWindow的rootViewController来presentViewController
我勒个去，我已经弹了个模态Controller了好不好

你拿栈顶的presentedViewController来presentViewController会屎么 逻辑能再严谨一点么 ？

**Comment by yirenjun** [comment]
实在不行 就全开源吧 大伙来帮你们改进代码 ~

**Comment by zsk425** [comment]
@yirenjun 我以为你是新浪的，感觉根本就没人维护，微博开放平台文档下面的更新时期是2013年某月，我就吓尿了

**Comment by zeejuncode** [comment]
醉了。

**Comment by jayni** [comment]
同问题，何时解决！？？？

**Comment by dannion** [comment]
将在3.1.0版本SDK中修复。

**Comment by jayni** [comment]
谢谢问下 3.1.0 SDK有时间计划么？大概啥时候可以发布？

**Comment by dannion** [comment]
目前3月份上旬前后。

**Comment by epingwang** [comment]
三月份了，敲碗等更新啊！

**Comment by tingatcoconut** [comment]
沒辦法之下，只好override rootViewController，實在太Hacky了，自己也不大想用
- (void)presentViewController:(UIViewController *)viewControllerToPresent animated:(BOOL)flag completion:(void (^)(void))completion
{
    UIViewController *topController = self;
    while (topController.presentedViewController) {
        topController = topController.presentedViewController;
    }
    [topController presentViewController:viewControllerToPresent animated:flag completion:completion];
}

**Comment by chunguiLiu** [comment]
楼上的思路是对的，不过，这么写当正常调用模态的时候会进入死循环，修改一下，如下：
- (void)presentViewController:(UIViewController *)viewControllerToPresent animated:(BOOL)flag completion:(void (^)(void))completion {
    UIViewController *topController = self;
    while (topController.presentedViewController){
        topController = topController.presentedViewController;
    }
    if(topController == self){
        [super presentViewController:viewControllerToPresent animated:flag completion:completion];
    }
    else{
        [topController presentViewController:viewControllerToPresent animated:flag completion:completion];
    }
}

**Comment by redihd** [comment]
想请问一下3.1.0 版本什么时候能上呢

**Comment by phaibin** [comment]
碰到同样的问题，马上6月了，3.1.0还不出来？

**Comment by zhilshi** [comment]
都7月份了，问下什么时候可以解决呀

**Comment by codefei** [comment]
这个issue还没解决么，也太垃圾了

**Comment by bingri** [comment]
马上就要2019年了，现在的版本是3.2.3了，还是有这个问题啊。。。
@dannion 亲，你还在新浪吗
