### ISSUE TITLE
请完善文档，增加分享音乐示例

### ISSUE THREAD

**Issue by zsk425** [sinaweibosdk/weibo_ios_sdk#67]
没有找到官方示例，我尝试了好多次分享出来的效果都不对，我的代码如下：

    WBMusicObject *musicObj = [WBMusicObject object];
    musicObj.objectID = @"identifier1";
    musicObj.title = @"title";
    musicObj.description = @"some desc";
    musicObj.thumbnailData = UIImageJPEGRepresentation(cover, 0.2);
    musicObj.musicUrl = webLink;
    musicObj.musicStreamUrl = audioURL;

    WBMessageObject *msg = [WBMessageObject message];
    msg.mediaObject = musicObj;

    WBSendMessageToWeiboRequest *request = [WBSendMessageToWeiboRequest requestWithMessage:msg];
    [WeiboSDK sendRequest:request];

效果却是这样的：
![错误的效果](http://7u2iw4.com1.z0.glb.clouddn.com/imageserror_weibo_share_audio.jpg)

预期效果：
![预期的效果](http://7u2iw4.com1.z0.glb.clouddn.com/imagesweibo_share_audio_normal.png)

**Comment by dannion** [comment]
请查看FAQ中关于Linkcard的说明。
