### ISSUE TITLE
调用sdk分享时，分享文案中有链接的情况的一个bug

### ISSUE THREAD

**Issue by redihd** [sinaweibosdk/weibo_ios_sdk#68]
当调用微博sdk做分享时，如果分享的文案里面有链接  且链接中有&字符，&字符后面的文案都消失了

**Comment by redihd** [comment]
对了，增加一个说明，是在没有客户端的情况
而且不是&符号一定要在链接中,在文本中就会吞掉

**Comment by xcy1231** [comment]
分享的文案中有url，而url中包含中文的话，中文以及以后的字符都不会被识别到url中，导致url出错
