### ISSUE TITLE
为什么现在的包这么大??

### ISSUE THREAD

**Issue by Creolophus** [sinaweibosdk/weibo_ios_sdk#69]
9MB???

**Comment by dannion** [comment]
打包以后，集成SDK的应用程序只会增加大概900k大小。

**Comment by dannion** [comment]
集成WeiboSDK的应用打包以后只会增加大概900k大小。

On 2015年1月30日 at 上午9:30:02, Creolophus (notifications@github.com) wrote:

9MB???
