### ISSUE TITLE
使用cocoapods 搜索不到微博的SDK了  是不是出什么问题了

### ISSUE THREAD

**Issue by lijie19900317** [sinaweibosdk/weibo_ios_sdk#71]
使用cocoapods 搜索不到微博的SDK了

**Comment by dannion** [comment]
这是由于第三方开发者在Cocoapods库中创建了WeiboSDK的pod。导致开发者通过“Pod 'WeiboSDK'”所引进的pod并非官方Pod，而是一个podspec配置错误的pod。微博官方已经尝试联系Cocoapods找回Pod库的所有权。在此之前，开发者可以通过在Podfile中填写以下语句：pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"  来实现集成官方的、正确的WeiboSDK Pod的目的。
