### ISSUE TITLE
[WBMFPRSA getPublicKey]  导致app崩溃

### ISSUE THREAD

**Issue by TonnyTao** [sinaweibosdk/weibo_ios_sdk#74]
```
-[WBMFPRSA getPublicKey](self=<unavailable>, _cmd=<unavailable>) + 190 at WBAidManager.m:475
-[WBMFPRSA encrypt:](self=0x16de0290, _cmd=<unavailable>, plainText=0x16d64a70) + 28 at WBAidManager.m:666
-[WBAidManager generateMFPString](self=<unavailable>, _cmd=<unavailable>) + 1056 at WBAidManager.m:281
-[WBAidManager fetchAid:](self=0x16d44c20, _cmd=<unavailable>, shouldRetryIfErrorHappened='\0') + 128 at WBAidManager.m:307
-[WBAidManager advertisementIdentifier](self=<unavailable>, _cmd=<unavailable>) + 84 at WBAidManager.m:173
-[WBAidManager fetchAidIfNeededWithApp:](self=<unavailable>, _cmd=<unavailable>, app=<unavailable>) + 44 at WBAidManager.m:341
+[WeiboSDK registerAppWithApp:](self=<unavailable>, app=<unavailable>, _cmd=<unavailable>) + 620 at WeiboSDK.m:1013
+[WeiboSDK registerAppWithAppKey:](self=0x00602048, _cmd=<unavailable>, appKey=<unavailable>) + 134 at WeiboSDK.m:1034
`+[WeiboSDK registerApp:](self=<unavailable>, _cmd=<unavailable>, appKey=<unavailable>) + 20 at WeiboSDK.m:1039

```

**Comment by Whirlwind** [comment]
是 CocoaPods 引入的吧？官方 Podspec 库的 spec 有问题，weibo 的 spec 更新了，没同步到 Pod 那里

**Comment by Yaou** [comment]
完全一样的错误信息，lz可解决了？

**Comment by Yaou** [comment]
我这么搞定的
pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'

**Comment by PangPangPangPangPang** [comment]
我这边不是用CocoaPods引入的 出现同样的问题

**Comment by guiyang** [comment]
按照 Yaou 同学的方法解决掉了 @Yaou

**Comment by hewigovens** [comment]
除了podspec的问题, 还有可能是WeiboSDK.bundle没有添加到bundle resources里

**Comment by cute** [comment]
发现把WeiboSDK.bundle手工添加到工程里就可以了。

**Comment by shivanraptor** [comment]
@Yaou 這個方法 OK !

**Comment by kevin-geng** [comment]
我这么写怎么错了
pod 'IQKeyboardManager', '~> 3.2.3'
pod 'DXYTencentOpenAPI', '~> 2.3'
pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'
pod 'AFNetworking', '~> 2.5.4'

然后就报错。

**Comment by guiyang** [comment]
AFNetworking 后面的逗号是中文字符？

**Comment by toby20130333** [comment]
WBMFPRSA getPublicKey 我也遇到这个问题 之前是-OBJC的问题 那个问题解决了 现在又是这个问题 调试 直接调到WBMFPRSA getPublicKey这个crash了

**Comment by cute** [comment]
@toby20130333  @kevin-geng 

找到WeiboSDK.bundle手工添加到工程里就可以了

**Comment by kevin-geng** [comment]
全是英文符号

**Comment by kevin-geng** [comment]
他已经在pod里面了，如何再手工添加呢？

**Comment by kevin-geng** [comment]
@cute 怎么手工添加？

**Comment by cute** [comment]
@kevin-geng 
Targets -> Build Phases->Copy Bundle Resources

**Comment by dannion** [comment]
这是由于第三方开发者在Cocoapods库中创建了WeiboSDK的pod。导致开发者通过“Pod 'WeiboSDK'”所引进的pod并非官方Pod，而是一个podspec配置错误的pod。微博官方已经尝试联系Cocoapods找回Pod库的所有权。在此之前，开发者可以通过在Podfile中填写以下语句：pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"  来实现集成官方的、正确的WeiboSDK Pod的目的。

**Comment by xiaopin** [comment]
刚也遇到这问题了，我是pod 'WeiboSDK', '~> 3.0.1'这样引入的，如果是pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk" 这样引入的话，发现会卡在Pre-downloading: `WeiboSDK` from `https://github.com/sinaweibosdk/weibo_ios_sdk.git`，半天都动不了

**Comment by summer-wu** [comment]
参考#129

**Comment by jasperwanglin** [comment]
第三方的podspec有问题的原因一般类似于下面：
```
xxx.resource_bundles = {'XXX' => ['Pod/Assets/**/*.bundle']}
```
明显有问题啊。属性`resource_bundles`是提供给开发库的开发者定义资源文件名和资源，并且来避免与其他库之间的可能出现的命名冲突。[这是用法](https://guides.cocoapods.org/syntax/podspec.html#resource_bundles)可不是上面这样用的。解决方法如下：
* 直接使用官方的。在Podfile中添加
```
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"
```
* 如果是自己封装，则使用`resource`，[这是用法](https://guides.cocoapods.org/syntax/podspec.html#resources)。
```
xxx.resource = "Pod/Assets/**/WeiboSDK.bundle"
```

**Comment by WillYuSir** [comment]
@cute 谢谢！

**Comment by willonboy** [comment]
@cute txs

**Comment by enefry** [comment]
敢改成 [nsbundle bundleforclass: self.class] 么 ?
为什么一定要 mainbundle 里面...

**Comment by graydang** [comment]
@jasperwanglin 完美解决，多谢！

**Comment by sinaweibosdk** [comment]
由于微博SDK需要获取第三方app中main bundle里面的信息，保证微博sdk在main bundle中。
