### ISSUE TITLE
podspec 里面缺少声明依赖系统的 ImageIO

### ISSUE THREAD

**Issue by Whirlwind** [sinaweibosdk/weibo_ios_sdk#75]
缺少下面这个依赖：

```
  s.frameworks = 'ImageIO'
```

麻烦添加到官方 podspec。

**Comment by Whirlwind** [comment]
好像这个库里面的 podspec 已经修复了，但是没有更新 CocoaPods 官方库，能不能更新一下。

**Comment by dannion** [comment]
这是由于第三方开发者在Cocoapods库中创建了WeiboSDK的pod。导致开发者通过“Pod 'WeiboSDK'”所引进的pod并非官方Pod，而是一个podspec配置错误的pod。微博官方已经尝试联系Cocoapods找回Pod库的所有权。在此之前，开发者可以通过在Podfile中填写以下语句：pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"  来实现集成官方的、正确的WeiboSDK Pod的目的。

**Comment by fayhot** [comment]
@dannion 
你是新浪微博的人么，你不能把你这个说明更新到首页的readme里么。

这样大家踩雷的几率就小很多了，不然主要手贱 直接写的 pod 'weibosdk' 基本都要上来体验一遍你们操蛋的服务。
QQ群跟死人群一样。

腾讯这点儿就做的非常nice，产品PM还各种安慰，主动提供各种帮助。
连环信这种小团队都有非常贴心的客服服务，你们的真是扶不起的阿斗。

一群煞笔。
