### ISSUE TITLE
SDK 带有图片的分享跳转到微博客户端后 提示：发送队列中有未发送的内容，确定要继续发送么？

### ISSUE THREAD

**Issue by tonglesu** [sinaweibosdk/weibo_ios_sdk#76]
SDK 带有图片的分享跳转到微博客户端后 提示：发送队列中有未发送的内容，确定要继续发送么？点击确定也只是存到了草稿里，没有发送。
复现场景：首先彻底关闭微博客户端     然后打开微博的Demo  分享图片   然后吊起微博客户端收到提示。
附：
如果之前微博客户端是开启的状态就不会有这个问题，所以怀疑是SDK的Bug,git上的Demo也能复现这个问题。

**Comment by lichenglong001** [comment]
问题解决了吗？同样地问题在iOS8上还会引起新浪分享页面异常。

**Comment by neil-wu** [comment]
同样遇到了
