### ISSUE TITLE
handleOpenURL的结果

### ISSUE THREAD

**Issue by aelam** [sinaweibosdk/weibo_ios_sdk#81]
weiboxxx://response?ID=xxxxxxx
这种结果 在不用WeiboSDK处理的情况能否通过前面的字符串得到是什么类型的结果
比如 微信的用的 wx://safepay/xxxx  wx://oauth/xxxx
这特殊情况的完全不能自理了。。

**Comment by clowwindy** [comment]
联系过微博的工作人员，他们是这么回复的：
> weibo:"https://github.com/sinaweibosdk/weibo_ios_sdk/issues/81 这个问题说的是希望我们把内部消息的协议公开，使得第三方可以直接处理我们内部消息而不是通过SDK，目前来说这是不可以的。"

Seems they have no ideas what they're doing.

**Comment by aelam** [comment]
应该把response改成对应的功能域更方便
