### ISSUE TITLE
通过微博客户端得到授权的话 WBAuthorizeResponse.refreshToken 为 nil 

### ISSUE THREAD

**Issue by an0** [sinaweibosdk/weibo_ios_sdk#82]
虽然 WBAuthorizeResponse.userInfo 中是有 refresh_token 的。

相比之下，如果没有安装官方微博客户端，通过页面授权，WBAuthorizeResponse.refreshToken 正常。

**Comment by crossle** [comment]
通过 HD 版的 weibo， refreshToken nil

**Comment by BelinChung** [comment]
今天下午确认了，Android 和 iOS 最新的 v3.1.1 SDK 修复了这个问题
