### ISSUE TITLE
发布在Cocoapods的podspec文件缺少系统依赖库

### ISSUE THREAD

**Issue by yanzhiwei147** [sinaweibosdk/weibo_ios_sdk#83]
[发布文件路径](https://github.com/CocoaPods/Specs/blob/b1ae5926beb0daa3060113981f3ada98cca292a6/Specs/WeiboSDK/3.0.1/WeiboSDK.podspec.json)存在问题，缺少两个依赖的系统库链接：`ImageIO`,`SystemConfiguration`，希望能更新解决该问题

**Comment by feikang** [comment]
改版本号重新 push podspec文件

**Comment by Yaou** [comment]
我这么搞定的
pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'

**Comment by kevinke** [comment]
其实还缺一个libsqlite3.dylib。

**Comment by yanzhiwei147** [comment]
诚意不足，既然支持cocoapods，为何不测试完全再放出来？
