### ISSUE TITLE
pod引入3.0.1出现问题

### ISSUE THREAD

**Issue by stone19880815** [sinaweibosdk/weibo_ios_sdk#86]
pod引入后缺少两个系统依赖库，手动添加以后编译不通过，出现 rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23错误

**Comment by dannion** [comment]
这是由于第三方开发者在Cocoapods库中创建了WeiboSDK的pod。导致开发者通过“Pod 'WeiboSDK'”所引进的pod并非官方Pod，而是一个podspec配置错误的pod。微博官方已经尝试联系Cocoapods找回Pod库的所有权。在此之前，开发者可以通过在Podfile中填写以下语句：pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk"  来实现集成官方的、正确的WeiboSDK Pod的目的。
