### ISSUE TITLE
测试账号web页面授权之后可以回调，应用授权不可以

### ISSUE THREAD

**Issue by williamhqs** [sinaweibosdk/weibo_ios_sdk#88]
通过sso方式授权，添加的15个账户可以通过web网页授权，但是通过应用授权之后不能回调回我的应用

**Comment by coolzc** [comment]
我也遇到这个问题，楼主解决了吗？

**Comment by williamhqs** [comment]
太久了 记不清楚了 你看下应该是应用名或者回调地址还是哪里填写的不对 和SDK没有关系

**Comment by coolzc** [comment]
刚刚才发现在8.1的系统上可以成功，9.0的系统就不行，是同样的设置，我猜测可能是iOS9的适配问题，但是，我已经按照read me的设置做了适配，没有头绪。。。

**Comment by williamhqs** [comment]
嗯 按理说应该不会 你好好看看吧 GOODLUCK
