### ISSUE TITLE
分享网页WBWebpageObject，微博显示错误的问题。

### ISSUE THREAD

**Issue by xuzhiming** [sinaweibosdk/weibo_ios_sdk#9]
demo中：
WBWebpageObject *webpage = [WBWebpageObject object];
        webpage.objectID = @"identifier1";
        webpage.title = @"分享网页标题";
        webpage.description = [NSString stringWithFormat:@"分享网页内容简介-%.0f", [[NSDate date] timeIntervalSince1970]];
        webpage.thumbnailData = [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"image_2" ofType:@"jpg"]];
        webpage.webpageUrl = @"http://sina.cn?a=1";
        message.mediaObject = webpage;

如果把webpage.title="xxx" 修改后分享到微博，发现微博显示的title还是“分享网页标题”；
另外webpage.thumbnailData 这张图在微博上也没有显示出来。

MARK：此功能需要商务合作。

**Comment by skyzizhu** [comment]
解决了嘛？

**Comment by skyzizhu** [comment]
我也遇到这个问题。

**Comment by starLover** [comment]
使用WBWebpageObject后界面显示空白
![Uploading 0D37997F-C54F-4B61-BCB3-0A8B8381F1DE.png…]()
