### ISSUE TITLE
Cancel function

### ISSUE THREAD

**Issue by AnaTudor** [sinaweibosdk/weibo_ios_sdk#92]
I am trying to integrate the sdk and I encountered the cancel problem . I've been looking throw sdk and  demo and I wasn't able to find a delegate to be called  when the user push the CANCEL button on login . On Android there the OnCancel function which handles this but on iOS  i didn't find it .Could someone tell me , please , if this issue can be solved ?

**Comment by dannion** [comment]
Please use the latest SDK(3.1.1), which has already fixed the bug above.
