### ISSUE TITLE
分享到微博，微博SDK在IOS 9 下会导致Crash

### ISSUE THREAD

**Issue by nuoxia** [sinaweibosdk/weibo_ios_sdk#93]
thread #38: tid = 0x151f5c, 0x0000000100e38d58 TBMainClient`wbsdkjk_encode_add_atom_to_buffer(encodeState=0x0000000111814000, objectPtr=0xa00656e6f6850696) + 872 at WBSDKJSONKit.m:2863, queue = 'com.apple.root.user-initiated-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0xa00656e6f6850696)
- frame #0: 0x0000000100e38d58 TBMainClient`wbsdkjk_encode_add_atom_to_buffer(encodeState=0x0000000111814000, objectPtr=0xa00656e6f6850696) + 872 at WBSDKJSONKit.m:2863
  frame #1: 0x0000000100e39fe0 TBMainClient`wbsdkjk_encode_add_atom_to_buffer(encodeState=0x0000000111814000, objectPtr=<unavailable>) + 5616 at WBSDKJSONKit.m:3075
  frame #2: 0x0000000100e38600 TBMainClient`-[WBSDKJKSerializer serializeObject:options:encodeOption:block:delegate:selector:error:](self=<unavailable>, _cmd=<unavailable>, object=0x0000000138b026c0, optionFlags=<unavailable>, encodeOption=10, block=<unavailable>, delegate=<unavailable>, selector=<unavailable>, error=0x0000000000000000) + 988 at WBSDKJSONKit.m:3140
  frame #3: 0x0000000100e38208 TBMainClient`+[WBSDKJKSerializer serializeObject:options:encodeOption:block:delegate:selector:error:](self=<unavailable>, _cmd=<unavailable>, object=<unavailable>, optionFlags=<unavailable>, encodeOption=<unavailable>, block=<unavailable>, delegate=<unavailable>, selector=<unavailable>, error=0x0000000000000000) + 148 at WBSDKJSONKit.m:3095
  frame #4: 0x0000000100e3aab8 TBMainClient`-[NSDictionary(self=<unavailable>, _cmd=<unavailable>) weibosdk_WBSDKJSONString] + 68 at WBSDKJSONKit.m:3282
  frame #5: 0x0000000100e1e0d0 TBMainClient`-[WBAidManager generateMFPString](self=<unavailable>, _cmd=<unavailable) + 1036 at WBAidManager.m:278
  frame #6: 0x0000000100e1e254 TBMainClient`-[WBAidManager fetchAid:](self=0x0000000138b924c0, _cmd=<unavailable>, shouldRetryIfErrorHappened=false) + 148 at WBAidManager.m:307
  frame #7: 0x0000000100e1dcb4 TBMainClient`-[WBAidManager advertisementIdentifier](self=0x0000000138b924c0, _cmd=<unavailable) + 96 at WBAidManager.m:173
  frame #8: 0x0000000100e1e4e0 TBMainClient`-[WBAidManager fetchAidIfNeededWithApp:](self=<unavailable>, _cmd=<unavailable>, app=<unavailable>) + 60 at WBAidManager.m:341
  frame #9: 0x0000000100e32150 TBMainClient`+[WeiboSDK registerAppWithApp:](self=<unavailable>, _cmd=<unavailable>, app=<unavailable) + 588 at WeiboSDK.m:1013
  frame #10: 0x0000000100e3248c TBMainClient`+[WeiboSDK registerAppWithAppKey:](self=0x0000000103452d18, _cmd=<unavailable>, appKey=<unavailable) + 160 at WeiboSDK.m:1034

**Comment by dannion** [comment]
最新版3.1.1已修复上述iOS9问题，烦请更新SDK
