### ISSUE TITLE
iOS9.0 beta2 启动crash

### ISSUE THREAD

**Issue by RyouZhang** [sinaweibosdk/weibo_ios_sdk#96]
![33f9538e-2d0e-4a6b-8b9d-468b0e972ede](https://cloud.githubusercontent.com/assets/2154569/8401721/4833d3be-1e65-11e5-934f-cc8a8a828c37.png)

启动registerApp然后crash

**Comment by csevenr** [comment]
遇到同样的问题，需要sdk author check下代码

**Comment by suxinde2009** [comment]
iOS 9.0 beta启动crash， 同样问题
https://github.com/suxinde2009/Practical_Algorithms/blob/master/weibosdk_ios9.0-beta_crash.png

**Comment by TristenChen** [comment]
我也是遇到同样的问题

**Comment by dannion** [comment]
WeiboSDK3.1.1已修复该问题，烦请替换SDK。

**Comment by backslash112** [comment]
同样的问题，更新到3.1.1正常了
