### ISSUE TITLE
3.1.1 启动直接crash

### ISSUE THREAD

**Issue by bluekurk** [sinaweibosdk/weibo_ios_sdk#97]
+[WeiboSDK registerApp:] 时挂在
 [NSConcreteMutableData wbsdk_base64EncodedString]: unrecognized selector

iOS 7&8 都是如此

**Comment by bluekurk** [comment]
OTHER_LDFLAGS  里加个 -all_load 解决。

**Comment by tuyuanyou** [comment]
我在工程里加了-all_load，这样与我自己的工程就冲突，怎么解决啊
