### ISSUE TITLE
3.1.1的SDK  真机调试crash  ios8.4

### ISSUE THREAD

**Issue by yishuiliunian** [sinaweibosdk/weibo_ios_sdk#99]
![1a8bc711-9baf-4af4-9c5a-f6e9a4a670bc](https://cloud.githubusercontent.com/assets/846525/8637269/a20c48a2-28bb-11e5-9ac8-2a95d845ad61.png)

集成了之后，register调用就crash，！！！！！

**Comment by fayhot** [comment]
我也遇到这个问题了，害的我还被拒审核了。我真是日了狗了，新浪微博这帮畜生。

**Comment by fayhot** [comment]
@yishuiliunian 
我已经搞定了。

我估计你也是直接  pod 'WeiboSDK'
这个源是有问题的， 你需要额外指定 git: 地址

pod 'WeiboSDK', :podspec => 'https://raw.githubusercontent.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'
